### ISSUE TITLE
Boost casters a bit to address new movement?

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#108]
Casters have always been weaker than melee early on, and relied on kiting and luring because they simply cannot survive otherwise. With the new movement, this is just amplified and you're really pushed to going hybrid over pure caster.

The mana pool is a big limiting factor, so one solution would be reduce mana cost on spells / increase the size of the mana pool / increase mana regen. 

Another possibility would be to give casters a better chance to survive hits. Maybe reduce penalty for casting in heavier armour, based on your spellcasting skill? I don't like this as much as beefing the mana reserves though.

**Comment by jeremygurr** [comment]
I'm fine with boosting mana reserves. Anyone against this?

There are three ways we can do this:

Straight across the board 50% increase.

Same amount of magic, but increase amount of magic capacity per spellcasting skill point, so those that invest more heavily in spellcasting get more magic. This makes late game easier. 

Fixed addition to magic pool, say 10 or 15 points, so that late game will be close to what it has now, but early game has 2 - 3 times more magic. This favors early game, and does little for late game. 

I would lean towards the 3rd possibility, since I don't want to overpower late game, but I'm open to any of these.

**Comment by G0rg0** [comment]
I think option 2 or 3 are worth giving a try. 

I'm not so concerned about the implications of option 2 as late game casters generally have "unlimited" mana already due to items/god choice etc.

**Comment by jeremygurr** [comment]
Ok I gave hard mode players an extra 4 mp, normal 8 mp, easy 12 mp. That will have an impact on early game, but have very little impact on late game. Tell me if this doesn't feel like enough still. This should take effect even for existing games.
