### ISSUE TITLE
tree form should make player unnoticable to creatures that haven't seen them yet. 

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#127]
It's the perfect camoflage

**Comment by Sandman25DCSS** [comment]
That would make Vine Stalker OP IMHO. 3 turns penalty for ending transformation would not matter much in most situations since you don't care about monsters which come into view when you are already in tree form. It would result in easy splitting of packs: transform, kill all, untransform, get noticed, transform, kill all and so on.

**Comment by jeremygurr** [comment]
Good point. I think if monsters already are attacking a player in tree form, and other monsters enter into view, the monsters that are aware of the player should communicate with the others and share the "noticed" status. Then the pack mostly stays together. I think the same thing should apply when trying to escape in any form, monsters should communicate with others in LOS of the location of the player. This makes stealth not very valuable in large groups, but work best against smaller, less intelligent groups. Seems a bit more realistic. And if that makes stealth too weak, we can buff it a little, but I don't think it would, since this is close to how the group ai works anyway as far as I can tell.

**Comment by Sandman25DCSS** [comment]
Is the new "tell others location of player" mechanic applied to natural form also? It could make life of stabbers extremely hard, there would be very little reason to try stabbing a pack because it is very likely to be noticed by 1 monster. Previously being noticed by 1 monster was not a big deal, you still had time to retreat or to stab unaware (and often even still sleeping) monsters.

**Comment by jeremygurr** [comment]
Yeah I'm worried about that too. There is already some kind of communication in place for that, because when I go and try to stab a monster in a pack, they almost always notice all in the same turn, not one at a time, and that's before I attempt to stab, just because of the stealth check. I don't want to make that worse. It's possible the game already does what I want to in this case. Maybe we just need to try the stealth tree form and see how it goes.

**Comment by Sandman25DCSS** [comment]
According to wiki, Tree Form already can make characters very stealthy: almost doubles stealth for most species by changing stealth factor to 27 (most species have 15). If you want to buff Tree Form, you can just replace 27 with greater value.

**Comment by jeremygurr** [comment]
Cool. Maybe I don't need to do anything here then.
