### ISSUE TITLE
Default skills training for Earth Elelmentalists

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#128]
Should stealth always turned on as a default? 
I just started a Moon Troll EE and there's no way I want to dump my XP into stealth even if it wasn't a -4 apt.

**Comment by Sandman25DCSS** [comment]
Stealth is still useful for EE since just LRD is loud, I considered training Stealth during middle game (I was using 2 items with Stlth+ on MTEE) but was stopped by aptitude. I mean I wouldn't like Stealth being removed for EE. Moon Troll does not need stealth as much (mana regen and size penalty) but most other species still benefit a lot.

**Comment by G0rg0** [comment]
Yeah I guess that makes sense, I always check my training when I start anyway.
