### ISSUE TITLE
Cave Troll is too easy

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#129]
I cleared D1-10 and Lair 1-6 and am at XL 17 in hard mode.

**Comment by Sandman25DCSS** [comment]
Version 1.1, old_experience=true

**Comment by jeremygurr** [comment]
Yeah you can use v1.2 with old_experience=true and it should be just like before. I expect it will take some serious testing to get the new one balanced right. It's easy to tweak though, we just have to figure out exactly where the numbers should be. I just had to take a wild guess with this initial run.

**Comment by jeremygurr** [comment]
What level are you normally at by the end of lair?

**Comment by jeremygurr** [comment]
If I gave half as much experience, then you would be at level 14 instead. Does that sound close to where it should be? Also, how do the skill levels feel? Too much or too little? Those are separately tweakable from the main experience level advancement code.

**Comment by Sandman25DCSS** [comment]
I just checked my last winner, Moon Troll got to XL 13 in Lair 7.

I am going to try SpEn who kills nothing just to prove my point that monsters still should give some EXP... Running away from every melee-only normal speed monster is boring.

I am not sure why XP were changed for Cave Troll, my understanding is it is exactly standard Troll. Am I missing something?

**Comment by jeremygurr** [comment]
I've got an update going out in just a minute that cuts the experience gain in half. This feels closer to the right balance. 

Cave Troll XP hasn't been changed. I'm not sure what you are referring to? You read the readme updates right?

**Comment by jeremygurr** [comment]
Ok update is deployed. This should be closer, but it is easily tweaked as we test it further.

**Comment by Sandman25DCSS** [comment]
Yes, I read readme, this is why I don't understand why Cave Troll got to XL 17 in hard mode
 14178 | Lair:6   | Reached XP level 17. HP: 122/122 MP: 20/20
http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt

while standard Troll got to XL 13 (in normal mode of course)
16727 | Lair:6   | Reached XP level 13. HP: 104/127 MP: 15/21
http://dobrazupa.org/morgue/Sandman25/morgue-Sandman25-20140326-230733.txt

**Comment by Sandman25DCSS** [comment]
In standard crawl my Troll got to XL 17 after clearing whole Lair, Dungeon, Orc and Snake

37259 | Snake:4  | Reached XP level 17. HP: 151/172 MP: 6/25
and that's without -2 EXP modifier which is present in hard mode.
I suspect something is wrong.

**Comment by Sandman25DCSS** [comment]
Oh, also look at HP, it's really different.

**Comment by Sandman25DCSS** [comment]
Can it be related to your changes with removing 27 cap?

**Comment by jeremygurr** [comment]
The HP is different because of hard mode vs. normal. 

You were able to get to level 17 more quickly because it's dramatically different to give experience based on one potion per level vs. based on monster kills. How well do you think I can guess how many potions will give the same amount of experience as the average number of kills over many different floors? It's so dramatically different that it's a miracle that it was only 4 levels higher than expected. 

There is more to it though that makes it even more difficult to predict, and thus the need for lots of testing. Old crawl had a wonky experience progression pattern, where players rapidly got to about level 9, and then each level after required twice as much xp, dramatically slowing down level growth mid game, and then after about level 15, things levelled out, and instead of each level requiring twice as much xp as the last, each level required only about 20% more, diminishing as they got higher. Totally crazy and counter-intuitive, also difficult to balance overall. So I put the whole thing on a pure curve, making the progression through the game much smoother and more predictable. The consequence of this is that the first 10 levels go by a little slower, the next 6 levels go by much faster (since it arbitrarily slowed down this section), and then getting through the 20s will be _much_ slower than mainstream crawl. Even without further tweaking, I would be surprised if anyone could pass level 25 in a 3 rune game. It would require 100 level 20 potions to pull off level 26. I might have made it too hard.

There is now a fixed amount of experience in the game, with the only randomness coming from the number of unique and player ghost spawns within a game, which would only tip the balance slightly from one game to the next. This makes it very easy to control how much experience a player gets and destroys a critical scumming practice.

**Comment by Sandman25DCSS** [comment]
I am playing with old_experience=true so I haven't found any potions of experience, I get experience from kills.
I have just cleared Lair, Orc and Dungeon and I am already at XL 24. This is why I think something is wrong.

**Comment by jeremygurr** [comment]
I see what you mean. That is the new experience curve I was talking about. That is independent of the old_experience mechanism. I'll tone that down a bit.

**Comment by jeremygurr** [comment]
Ok the old_experience option now covers the old experience curve as well, so it should behave exactly as before.

**Comment by Sandman25DCSS** [comment]
Thank you, I am XL 16 and lost many skills also.
