### ISSUE TITLE
Uniques not dropping XP potions?

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#136]
I'm not sure about ghosts, but I've killed a number of uniques with no XP potion dropping.

**Comment by jeremygurr** [comment]
Yeah I turned it off and increased the amount of exp each potion gives to balance it out. I can put it back if we think that works better, but I'm trying this for now. The idea is that you get cool items from uniques, and they get out of your way if you kill them, which should be enough incentive. It also makes pure pacifist runs more viable. Which isn't all that important, but interesting. 

This simplifies things a little. Just get the experience potions, killing or avoiding monsters along the way, until you can get the runes and orb. But we may find that it's more fun to have the incentive to take out uniques. It definitely makes it more fun when I see a unique if I know I'm getting an exp potion out of it.

**Comment by jeremygurr** [comment]
But I definitely want to know what you think after playing a few characters with the new system. It's very weird, and I'm sure awkward at first. But see if you can figure out a way to have fun with it. I think there are some interesting strategies that can evolve here.

**Comment by G0rg0** [comment]
Will do. This is a major change for sure.

**Comment by Sandman25DCSS** [comment]
I played one game with the new system and it confirmed my expectations - it's like forced speedrun. If I quaff XP potion immediately, I lose some XP and thus feel stupid. If I delay with quaffing, I have higher chance to die in unlucky events.

**Comment by jeremygurr** [comment]
That is true. But doesn't anything that motivates the player to engage with monsters also increase the chances of them dying? Like limiting stair dancing and kiting? 

Crawl is already all about risk management. This just kicks it up a notch (or 10). The choice to take on higher risk or to accept lower risk, or anything in between, is completely on the player. Many of the features added to standard crawl in the recent past have been about increasing the motivation for players to take on higher risks, to make the game more exciting. 

If a player chooses to take higher risk than they really need to, and then dies, it's not an unpreventable death. More skill can be gained to better manage risk. 

If in one game a player ends up a bit overpowered (because of some lucky equipment for example), they can handle taking on greater risk, for greater reward. If a character is particularly fragile, they can back off on the risks, and play more conservatively, until their character is stronger. It's an automatic difficulty adaption system. 

It's a lot of power to give to a player, and most games make these decisions for the player, trying to guess at the right level of difficulty to match the player with. But what if a player took the time to learn to play this style well? Would they find greater excitement and depth and challenge than before? That's the question I'm trying to get answered. 

But it's quite possible that many players wouldn't give it enough of a chance to discover if it would be worth learning to manage that level of risk. So maybe it should just be a different game mode, like zot defense and the speed runs. I don't know. 

For now what I'd like to do is create a couple more options. One will turn unique potion drops on or off (and balance the potion experience appropriately), and the other will turn potions off, so that a player gains skill only by going to new floors, taking away the intensity created by saving potions for as long as possible. Then you guys can experiment with whatever mode you feel like playing. What I'm after is what ends up to be the most fun with the highest strategic depth, and thus longest replay value.

**Comment by Sandman25DCSS** [comment]
Limiting kiting and stairdancing make diving even more risky. I am a perfectionist player, I try to get as powerful as I can i.e. kill everything that I can kill and run from everything that I can't kill. With new experience system there is no correct answer what to do, it depends on luck. Will I be one-shot by centaur around next corner? Or will I have easy time and be able to go 3 levels deeper? Nobody knows :(

**Comment by Sandman25DCSS** [comment]
By the way I think Crawl does not really need replay value, it already has huge number of species, backgrounds, gods and strategies (spells, armour, evocations).
