### ISSUE TITLE
Reached XL 28 with old_experience=true

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#138]
Also my HP increased:

**Comment by Sandman25DCSS** [comment]
65295 | Vaults:5 | Reached XP level 27. HP: 211/213 MP: 31/33
 67420 | Zig:5    | Reached XP level 28. HP: 222/222 MP: 33/33

I think there is too much XP, though probably it is related to new XL while I was playing until XL 24. Usually I don't get XL 27 before Zot in 3 rune game in hard mode.

**Comment by Sandman25DCSS** [comment]
I got the XL from potion of experience, I guess it is actually possible to reach XL 99 with potion of experience grinding.

**Comment by Sandman25DCSS** [comment]
Ended the game with XL 30.

**Comment by jeremygurr** [comment]
With this latest update I put the level 27 cap back for old_experience=true. Yeah changing how the xp is calculated mid game would do it, because with the new way, the late 20s would have required much more experience than the old way. Also, hard mode should be noticably harder now, since it cuts all experience gained instead of just what applied to your xl, meaning it also affects your skills (which it didn't before).

**Comment by Sandman25DCSS** [comment]
Great, thank you.
