### ISSUE TITLE
MP items are OP

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#152]
I found 2 rings of MP and staff of power. This is how it looks now:

Health: 39/39      AC:  6    Str:  4    XL:     11   Next: 65%
Magic:  60/75      EV: 25    Int: 21    God:    Kikubaaqudgha [*****.]

rFire  . . .      SeeInvis +    M - staff of power {MP+17, !a}
rCold  . . .      Gourm    .    j - +2 robe
rNeg   . . .      Faith    +    (shield currently unavailable)
rPois  .          Spirit   .    (helmet restricted)
rElec  .          Dismiss  .    h - +1 cloak
rCorr  .          Reflect  .    (gloves unavailable)
SustAt .          Harm     .    (boots unavailable)
MR     +....                    w - amulet of faith {Faith}
Stlth  +++++++...               i - ring of magical power {MP+9}
                                K - ring of magical power {MP+9}
- Level 7.9 Spellcasting

**Comment by jeremygurr** [comment]
Why is that OP? You are sacrificing two very valuable ring slots for the ability to cast a couple more high level spells. This is a pretty big boost early game if you happen to be lucky enough to find 2 of them, but by the time you will be able to use high level spells, you will likely have more valuable rings taking up those slots. By having ring of magic add 50% magic instead of just 9 points, it makes the ring valuable even late game, and possibly be worth taking up one of your ring slots in some special cases.

**Comment by Sandman25DCSS** [comment]
It would probably be ok for late game but 75 MP at XL 11 in hard mode seem broken to me. If I was a conjurer of Vehumet, I would probably never need to retreat (natural MP regeneration depends on max MP).

**Comment by Sandman25DCSS** [comment]
Maybe apply the 50% part to easy mode only? And let it work as +9 MP in normal/hard?

**Comment by Sandman25DCSS** [comment]
Also amulet of guardian spirit would almost triple my effective HP. I can imagine an Octopode would love it too, it might have more HP than Ogre.

**Comment by jeremygurr** [comment]
I see your point. Maybe instead of 50% bonus, a 25% bonus? How many rings of magic do people really come across in a game? I think it is still partially balanced by the fact that you really need those ring slots for gaining resistances, etc.

**Comment by Sandman25DCSS** [comment]
25% bonus is probably ok.
Randart rings can have MP+9 too by the way. 
My Spriggan found amulet of guardian spirit so now I can have more MP than HP, maybe hard mode should decrease MP too.

**Comment by jeremygurr** [comment]
fixed
