### ISSUE TITLE
Identify scroll possibly is confused by the double inventory?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#160]
I read an ident scroll

List of unidentified things pops up, the thing I want to identify is a scroll in the F slot (consum-inventory)

I press F

It identifies something from the perm-inventory instead

So I have to read another ident and CLICK the scroll I want to identify to ensure the game isn't confused

**Comment by jeremygurr** [comment]
hmm... keep in mind that the letter that goes with an item in the "unidentified list" is different than the letter you will see with it in the inventory, because it combines the two inventories for that list, if there is a letter conflict it must assign a new letter to the item. Are you sure you typed the letter you saw in the unidentified list, and not the inventory list? This is a common source of confusion unfortunately, and really the only negative side effect of the expanded inventory I haven't figured out how to eliminate. I originally made it ask the player each time they read an identify scroll which inventory they wanted to identify, but when identifying several items in sequence, I found that very annoying. So it's a trade off between being more annoying, or a little confusing the first time.

**Comment by yrmvgh** [comment]
That could be it! I will keep an eye out. It is possible that I looked at my message log and pressed F based on that, instead of based on the new dialog

I am really itching to start a new character, on whom I can re-test ID scrolls, but first to do so I must go through the painful process of VERY carefully getting my 3rd rune ans the Zot with 0 felid lives left, or getting dead. Oh the pressure! But that is a DCSS issue not a DCSSCA issue. ;)
