### ISSUE TITLE
Should Formicid be able to wield large rocks?

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#163]
I'm not sure about this. I know they had this originally, but I also like the distinction that only ogres and trolls can do this. Other thoughts?

**Comment by yrmvgh** [comment]
I think "should" is a hard question to answer. Should minotaurs have a high sword apt? They're already so powerful, and horns are their main shtick. They don't neeeeed swordfulness.

For me the question is - **could** Fo have large rocks? They came packaged with it initially because their shtick is being largeish while technically being medium.

It was removed, for balance reasons... **at a time during Crawl's history when large rocks had piercing**. If that's no longer the case... and Fo have to spend half a turn (w)ielding the rock... I think it could work! :)

It's not so much stepping on troll & ogre's toes, as giving formicids something back!

...but you already knew I wanted this, I hope other player can weigh in on the issue. ;)

**Comment by jeremygurr** [comment]
I could go either way here. It would be nice to be able to use large rocks more. On the other hand, formicids already have a lot of uniqueness, and they would be taking a little away from the ogre and troll's uniqueness.

**Comment by jeremygurr** [comment]
I'd rather give large rocks piercing though. That sounds like it would make ogre hunters way more fun. There must have been a good reason they removed it though. Anyone know why?

**Comment by Sandman25DCSS** [comment]
Ogre hunters are already OP. I won a game where I used nothing but throwing and that was a very easy game. That's why standard crawl nerfed throwing.

**Comment by yrmvgh** [comment]
Throwing is secret tech: incredibly effective on almost any character, if you manage your ammo via god choice or via not being wasteful. Even tomahawks can 1hko many things.
