### ISSUE TITLE
remove mottled draconian

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#165]
I agree with the philosophy of removing things that aren't that good, but prefer to first try and save it, since it's easier to make something that exists more interesting than to add something new. 

So I think it's fair enough to say that it's disappointing for most people when they get the mottled draconian. What can we do to make it more interesting? Maybe increase the power of it's spitting ability? Maybe increase the range or damage of the sticky flame? Or replace the sticky flame resist with a simple fire resist?

**Comment by yrmvgh** [comment]
The range is the most grievous offense in my book. Making it a 2 tile cone instead of one would help a lot.

You could possibly give them a couple of the other "[stupid resistances](http://crawl.chaosforge.org/Resistance#Minor_Resistances)" and make that part of their "charm" or shtick. 

However, the reason I am in favor of axing it is because the other drac types are SO GOOD. They are strong options, with well-defined and unique playstyles. Mottled just feels like a second-rate Red Drac, and if you buffed it enough, it's possible that Red Dracs would feel like second-rate Mottled. I just don't see the need for two flavors of Fire Drac.

The only benefit I can see to having two Fire type dracs is the assurance that you can roll a fire elementalist somewhat more confidently than an ice elementalist.

**Comment by yrmvgh** [comment]
So it's not that mottled is unfixeable, IMO, it's just that removing it would ensure getting one of several highly-distinct and enjoyable drac colors which are what most people are probably looking for anyways,and reduce the odds that you have to play multiple fire-based dracs in a row if you play them a lot.

**Comment by jeremygurr** [comment]
I agree that if mottled can't be good enough and distinct enough then it shouldn't be there. So maybe it could be taken in a different direction than just a variation of the fire draconian. 

So what really is the essence of a mottled dragon or draconian? How are they distinct from others? And maybe they aren't distinct enough and need further distinction. Frankly, when coming across mottled dragons in the game, they really aren't that interesting. The sticky flame is slightly interesting, but really it's just a variation of poison that is hard to find a resistance for, and so rare that it wouldn't be worth it even if you could. 

We have the four major elemental draconians: Red, White, Gray, Black. Then the special but valuable resistance ones: Green, Yellow. Then the powerful magic user: Purple.

Then you get the weird ones: Mottled and Pale. Okay, so pale can do steam clouds, which has some strategic value, but steam resistance is definitely lame. +1 to 3 different skills is alright though. 

So I can see a little help needed with the pale, and a lot with mottled. What if steam resistance also give the ability to see and target through clouds? That would make steam resistance more useful. Still pretty weak though. 

What if pale had rF+ and rC+, as well as rSteam (which is almost worthless), but it lost the skill improvements, except for evocations, which is a +2 instead of +1. 

And then for mottled: no resistances (or just the lame sticky flame resistance), but multiple skill boosts, fitting the "mottled" theme: +1 to fire, air, earth, ice. Maybe they could get -1 to poison, charms, hexes, to add some interesting balance. Then boost their sticky flame. To further distinguish from red, instead of going further, the sticky flame can have "cleaving" so it applies to all adjacent monsters (doesn't need to be targeted at all). Better yet, maybe the stick flame is added automatically to any melee or ranged attack, so it's no longer an "ability", but a permanent ego attached to all attacks. This would seem to change the playstyle quite a bit from the red.

**Comment by yrmvgh** [comment]
Steam clouds will save your bacon. Repeatedly. Free aptitudes are great. Pale is fine, IMO, but I can see how it reads worse than most of the others. I prefer the current aptitudes on it, but I wouldn't feel put out if you gave it those changes. A little aptitude for some resists is a fine trade.

Cleaving for mottled is good, but I'd keep it as an active ability despite my hatred of tedium, because part of the allure of draconid is the big impactful satisfying breath weapons. Leave the cute little enhancers to the demonspawn, IMO - better to make a breath weapons big enough to be worth a cooldown & turn, than to make it weak enough to be a freebie.

"Mottled" being a combo of the other colors certainly makes sense though!

**Comment by G0rg0** [comment]
How about instead of just rSticky, the mottled gimmick is they are globally resistant? Leave the attack weak in exchange for powerful defenses.

**Comment by jeremygurr** [comment]
what do you mean globally resistant? +rF, +rC, +rP, +rCorr, +rAcid, etc.? That would be really powerful. Definitely would make them more interesting though.

**Comment by G0rg0** [comment]
If rEverything is too much, maybe just the "basics", rPois, rC, rF? Add another random resist at lvl 12 for flavor?

**Comment by yrmvgh** [comment]
I feel that rEverything would dumb down the race to Gargoyle levels of ease and non-dependence on items. Which isn't inherently wrong, but seems against the spirit of what dracs currently are. More minor resistances could be a nice convenience though, and I like the universal elemental aptitudes that Gurr was thinking of.

**Comment by jeremygurr** [comment]
Ok I see your point. Pale is pretty powerful because of the steam clouds, so I will leave it as is, except to take inv from 1 -> 0, and evo from 1 -> 2, just to add a tiny bit of distinction there. 

Mottled I gave the +rF and +rC, plus the +1 apts for elemental and poison magic, then gave their sticky flame range 2 instead of 1. The aptitudes really don't make that much of a difference, they are more for flavor. But the resistances and extended sticky flame will significantly impact gameplay. 

Deployed.
