### ISSUE TITLE
Can you make Fedhas less tedious?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#166]
Fed is very powerful, but very tedious in that every ability is an active ability and nothing "just works" like most other gods.

Maybe the Jiyva code that causes jellies to "react" when spotted by the player, becoming friendly, can be used here. This would cause plants to occasionally evolve automatically when spotted by the player due to exploration or prayer-spawning.

Obviously oklob auto evolve should be pretty rare, but since it's a stationary turret and it's unlikely to happen in an ideal place and time it willl be quite a bit less impactful than player-spawned oklobs.

Less important: also maybe Gozag's 50% corpse-conversion code can be used to automatically mushroom half of the corpses, and praying can be removed. Though it's very easy to just macro prayer to your rest and explore buttons, which most of us already do.

**Comment by jeremygurr** [comment]
Hmm... I like the idea of making auto-sacrifice just happen whenever a player rests or auto-explores, so we don't even need the rc file settings (better for new players). And making just half of the corpses turn to mushrooms is good too. 

I don't find fedhas very tedious since most of his abilities are rarely used. But I like the idea of possibly converting an active effect into a passive one. He's got the plant movement / shoot through passive effect which is fairly useful, but nowhere near the free spellbooks / no miscast of sif, or the free health or magic of mak or veh or free armour and weapons of oka. I definitely see your point there. 

So maybe whenever a mushroom spawns from a corpse, there is a chance (if piety is greater than 2\* for example), that it will automatically become a wandering mushroom. Then, if piety is greater than 4*, anytime a player sustains more than 25% damage in one hit, or if a player goes below 30% health, there is a chance that a wandering mushroom in the area evolves into an oklob. Then we remove the evolve ability entirely. 

I don't know though, that just makes it more like yred's undead servants. I like the distinct gameplay mechanic here. Maybe one of the other abilities could be made passive. Maybe giant spores can automatically spawn from corpses if an enemy is nearby.
