### ISSUE TITLE
Humans

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#168]
> I never play humans in the mainstream crawl. It's just never interesting for me to do so, since they don't have any real benefit over any other species. So in this version, I amplified the differences between species, especially the "boring" ones I never play, to make each species more appealing in it's own way. 

I like this sentiment a lot, but I don't see any changes mentioned for humans!

If they're "the ultimate dabblers", some thoughts come to mind:

Humans get cross-training on Invo and/or Evo and/or spellcasting
Humans get half as much god wrath for switching to a new god
Humans get cross-training on fire/earth/air/ice

Though in some RPGs, the human shtick is to have all options open to them, but be good at focusing, maybe like a small bonus to skill training speed based on how many skills the player has at 1 or less. (not 0, that would screw Wn :)

What are your plans for humans? :)

**Comment by jeremygurr** [comment]
The current changes to humans was to take their exp, fighting, and spellcasting apts to +2. Now for the exp aptitude it's more significant than it seems, since I changed exp aptitudes to be more meaningful. Previously, if you have exp +2, it would only mean your character is 1 level ahead of where other characters would normally be, which isn't that impressive. Now it is closer to 2 levels ahead. Real example: at the same point that a Dj (exp apt 0) is at level 8.6, the human would be at level 11.5, which is almost 3 full levels higher, which is a pretty big difference. SImilarly, the Dg, with it's -3 apt, would be at level 5.8 at the same time the Dj is at 8.6 and the human at 11.5. Pretty huge difference. 

The cross training idea is interesting though. It probably wouldn't be hard to throw in cross training as well. It's a cool flavor. And the reduced wrath timer is cool too.

**Comment by yrmvgh** [comment]
Ah cool, didn't realize they'd already been changed

**Comment by jeremygurr** [comment]
Deployed.

**Comment by yrmvgh** [comment]
In hindsight, might make more sense for ice and fire not to crosstrain, and for air and earth not to crosstrain. It's whatever though. Thanks for the quick commit!
