### ISSUE TITLE
All melee weapons crosstrain?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#173]
If you find a sweet unrand, as of now it's a matter of luck whether it falls into a skill you've been training,  a valid cross-training option, or something that you have at 0.0.

Odds are, of course, it'll be something you're not trained in.

Would it be so bad if all melee weapons crosstrained to alleviate this issue? Or would that make characters feel too generic and replaceable?

In theory, were I making a fork of my own, I would make all melee weapons mutually crosstrain, because hitting someone with a stick uses many of the same skills as hitting them with a sword. Possibly I'd make unarmed and throwing crosstrain as well. What are some downsides to such a move?

**Comment by jeremygurr** [comment]
I think it limits the depth and interest a bit of the different weapons. Part of the fun of training is matching the training to the weapon you want to focus on. And part of the fun of finding weapons is happening to find one that you are skilled in. If all weapons were equally valuable in that way, it would make things more bland I think. It also reduces the difference in species since aptitudes are a big part of what defines a species.

**Comment by Sandman25DCSS** [comment]
I agree with Jeremy. I wouldn't object to removing cross-training completely instead. I remember I had a weird game where I used Demon Whip at min delay with 0 skill points invested in M&F.
