### ISSUE TITLE
Ash curse ability should curse an arbitrary number of equipped items, like uncursing does

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#184]
In most games, you get plenty of curse scrolls, but occasionally they are far too limiting and as a result you run around mostly unbound.

**Comment by G0rg0** [comment]
Cursing an item should just burn piety, and perhaps have a "first one is free" like Gozag's potions. 

It always struck me as wrong that you could find an ash altar on D2, but then if you're unlucky on finding scrolls you could go a number of levels deep before cursing a single item.

**Comment by jeremygurr** [comment]
Hmm, I see what you mean about going unbound for a little while, however, burning up remove curse scrolls to curse your items is important for the balance of remove curse scrolls. By forcing ash players to lose some of their remove curse scrolls, the significance of the curses themselves becomes bigger, because it is harder to remove the curses. 

However, we could also just make cursing free, and reduce the number of total remove curse scrolls in the game, to achieve the same balance. This reduces it for non-ash worshippers too, but that might actually be needed because of the fact that I made curses for normal players deteriorate automatically, even if you never read remove curse scrolls. I think this might be a better solution. Under this scenario, I don't think that cursing items needs a cost at all, since Ash is happy to curse things for you :) Adding a piety cost wouldn't have any real strategic impact on the player, since piety consuming skills are not frequently used. The complexity of a piety cost would be worth it if there was significant flavor involved, but I don't think that's the case here.

**Comment by yrmvgh** [comment]
Yet another way it could work:

Leave curse scrolls relatively common, as now. They can be used to uncurse an arbitrary number of worn items, as is. For non ash players you'll have plenty to wear-ID most items, as now.

Ash periodically curses a random worn item, so you never have to use an ability (or a curse scroll) to curse your stuff. Or, periodically offers you 3 curse choices, Ru-style. Whateva... point is, she takes care of spreading her curse to your items or slots.

But uncurse scrolls are of great value to any Ash player who wants to swap resist rings or upgrade their equipment, because eventually, all your stuff is going to be placed under Ash's curse... **AND,** in place of her existing, fiddly little curse management *\* ability she gains the ability to "release" a curse. (and maybe it swaps positions with Scry, since it feels more "epic")

This uncurses an item of your choice, at a high cost in Skill Drain, Piety, or both, and hits everything in LOS with corona, drain, and confusion. Or just a buncha nice straightforward damage, ru/qaz style.

As usual, not saying this is better than the existing proposals, just throwing more ideas into the brainstorm. :smiley:
