### ISSUE TITLE
Kobolds rapidly evolve in the short term

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#185]
While testing the new exp options. I've gone through quite a few sad, short-lived kobolds. Most of them, I don't get a chance to see them evolve.

Would it be okay if Ko had "rapidly evolve" for a very short time? Just until they get their first positive mut, and then it downgrades to normal evolution. Or if it would be easier, have them rapidly evolve until hitting say, XL3?

**Comment by jeremygurr** [comment]
That would be okay, but it's likely that a better solution would come from figuring out why your kobold doesn't live long enough to get to the fun part. I've played them many times and it's a blast to see what kinds of mutations you end up with and have to deal with. 

Many species have fun parts of their progression that they don't get right away. This is a good thing because it forces the player to really invest in the character a bit before they get the reward, and the reward is sweeter as a result. The player also works much harder to keep that character alive, which powers the energy and thrill of the game. 

Personally I think everyone should be playing on easy mode until they can beat the game consistently, preferably with all runes :). Then they should advance on to normal and hard. Once I get all my challenge features put in place (particularly rune curses, advanced identification and spellcasting, enhanced ghosts, double sided branches), even beating easy mode with all runes would be a significant challenge for all but the most elite of crawl players. 

With the new experience modes it's quite possible that a flaw in the experience mode could be contributing to the problem. They are still in the alpha phase of development, so there is a lot of room for balance improvements still. As it gets more properly balanced, it shouldn't be very hard to keep a kobold alive long enough to get several mutations. 

Is there a particular experience mode that interests you, that you could focus on testing and helping me to balance properly? Or do you want a recommendation on what might be easiest to keep a kobold alive in? If they were properly balanced, I would think that classic is easiest, followed by the two simples (you just have to resist the temptation to dive too deep), and if you can resist holding on to potions too long, balance and serenity aren't that hard either. Intensity, pacifist, and destroyer are meant to be a bit more exotic and challenging, although depending on how they are played they don't necessarily have to be. 

I wouldn't mind cranking evolution up to level 2 for kobolds, after maybe level 6. Evolution 2 moves 3 times faster than evolution 1. That could make the ride a bit more wild. I'll try that and play a few kobolds to see how it goes.

**Comment by G0rg0** [comment]
I've played a number of kobolds that died before getting any mutations as well. I've also had a few chars (in vanilla crawl, not this version) with evolve 2 and it honestly didn't seem like the mutations came very fast even there.

It's completely anecdotal though, could just be the RNG messing with me.

**Comment by yrmvgh** [comment]
> I've played them many times and it's a blast to see what kinds of mutations you end up with and have to deal with.

Yeah, in 1.2.2 I got a kobold into XL 12 to 20 or so, many cool muts.

> Is there a particular experience mode that interests you, that you could focus on testing and helping me to balance properly? 

I spent the most time trying to get going on Balanced and Serenity, I also gave both the Simple modes one shot each.

> I wouldn't mind cranking evolution up to level 2 for kobolds, after maybe level 6. Evolution 2 moves 3 times faster than evolution 1. That could make the ride a bit more wild. I'll try that and play a few kobolds to see how it goes.

This is backwards, IMO. The longer I've had my kobold, the more likely it is that I've selected gear that plays to the kobold's existing strengths and weaknesses. Maybe I left a sweet helmet behind on D3, and I've equipped resistances that work around the + or - muts I've got. To start rapidly evolving _later on_, and need to go back for the helmet, or more frequently rejigger the character, sounds annoying, though of course I'll be down to try it. It's not so much that I think kobold needs a buff, it's just I was hoping for his first mut to come faster so as to start customizing his playstyle/skills around his muts. (if antennae, get stealth, if claws, get unarmed, etc)

**Comment by jeremygurr** [comment]
Hmm... that makes sense, the problem is that you can't solidly build a playstyle around these mutations, since there is always a chance it could go away. They aren't permanent like Ds. Even if you mutated quickly at the beginning, then stabilized later, you could still lose that cool helmet because you grew horns. I guess we can try doing level 2 at the beginning, and then stabilizing to level 1 later on.

**Comment by G0rg0** [comment]
I do like the flavor of a "baby" kobold mutating rapidly and only slowing down as it grows older and more powerful.

**Comment by jeremygurr** [comment]
Yeah I like that too. Makes sense. And gameplay-wise, I don't think a player would like things changing too often after the character has gotten far along, so this will probably work out perfectly. I'm trying a kobold now with this style. It's quite fun. I've gotten several good mutations and a few bad. And of course I drink all mutation potions I come across, since evolve tends to clean out the bad ones over time. But I do have to deal with a few bad ones for now, which is a fun challenge.

**Comment by G0rg0** [comment]
That sounds perfect!

**Comment by yrmvgh** [comment]
> evolve 2 and it honestly didn't seem like the mutations came very fast even there.

Yeah, it's pretty random. I've played ten or more kobolds today and with rapid evolve, I've seen a range of "3 great muts before I even leave D1" all the way up to my current game of "XL4 on D3 and no muts at all".

Really fun stuff! I would say this one game is a fluke, usually I leave D:1 with at least one mut.

Can it be triggered to slow down to normal evolution after you get X amount of muts from it, or does the slowdown have to be XL/DL based?

**Comment by yrmvgh** [comment]
Curious... if their evolution slows down over time, would it make sense to turn off the racial evolution at 27, so you can have a stable character build? Or would it be more fun to keep mutating even into zigs and beyond? I've never gotten more than 4 runes yet so idk.

**Comment by yrmvgh** [comment]
Yeah, evolving is very random. And this is not a complaint! The randomness keeps it very different from Ds.

I've had a kobold with 4 or 5 muts by XL 10. And now I've got a kobold with only 1. My "wild genetic ride" slows down indeed. ;) It's a fantastic mut though - bone plates. I'm happy with the char and can't wait to see how it ends up.

http://crawl.homedns.org/morgue/itsakobolditsakobold.txt

**Comment by yrmvgh** [comment]
My best kobold yet! Pretty sweet array of muts:
[talons 1, large bone plates 1, see invisible, carnivore 3, evolution 1](http://crawl.homedns.org/morgue/itsakobold/morgue-itsakobold-20160414-070349.txt)

![itsakobold](http://i.imgur.com/LRge9ec.png)

The anti-stairdance code _miiiight_ need a special exception for poor lost souls attempting to escape the Abyss. :wink: 

I think I should have used my wands more, and relied less heavily on my sexy, but **low-tier**, artifact sling.

**Comment by jeremygurr** [comment]
Hmm, you are probably right. Abyss stairs ought to be a guaranteed exit.

**Comment by G0rg0** [comment]
If it hasn't been done already, genetic stability should not be a possible mut for Kobolds.

**Comment by jeremygurr** [comment]
agreed.

**Comment by jeremygurr** [comment]
done
