### ISSUE TITLE
Stuck games don't timeout

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#189]
Currently Sar's game is stuck, it does not stop. I had similar issues before.

**Comment by jeremygurr** [comment]
Likely what happened is he chose a different game version than his save game was started with. But now the server records whatever version you started a game with, so that this issue doesn't happen anymore. 

The problem is that games started before that change was made still need to know which version was started, and so it relies on the player to choose the correct one the first time. If that doesn't happen, it gets stuck on the wrong version. If he wants to save that character, I need to know what version (1.2.2 or 1.2.1) it started on, then I can fix it. If he doesn't care about the character, I can delete it and he should be fine from now on, because the server will track which version he started each game with.

**Comment by jeremygurr** [comment]
But if this issue still happens after new games are created, then tell me, because that means there is a different bug going on that I need to track down.

**Comment by jeremygurr** [comment]
I'm going to guess he was on version 1.2.1, since that is probably most likely, and kill the current process. He should be able to try again soon. If that doesn't work, we can try 1.2.2 or just delete his character so he can restart.

**Comment by Sandman25DCSS** [comment]
Thank you.

**Comment by eyestalker** [comment]
I'm not sure it was even a game, I think I quit on chargen screen? Anyway, it was 1.2.3. Nuke it please, nothing of value will be lost. Thanks!

**Comment by jeremygurr** [comment]
should be good now. Tell me if there are any further problems with it.
