### ISSUE TITLE
Djinni should not autopickup food, since they don't need it

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#2]

**Comment by jeremygurr** [comment]
Now they do. No reason to have Djinn foodless

**Comment by yrmvgh** [comment]
Since you can't read them anyways, it might be cool if flying past a scroll caused it to burn for a turn. It might be too easy to cover your retreats that way - kinda like using qaz clouds to (very slowly) kill things while you run away, instead of fighting in them. But it would also help visually (and dramatically) explain to a "tl;dr" style of player, why they can't read scrolls!
