### ISSUE TITLE
Pacifist mode requires chaning piety mechanic for most gods

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#215]
Most gods give piety for killing monsters

**Comment by jeremygurr** [comment]
Hmm... this would be a bug, because I intend for all experience gaining events to have the same side effects (removing drain, gaining piety, removing stat damage etc.). I'll have to look into this. The trick here is that gods have specific monsters they want dead and that they award piety for. We could make it to where when it's not a monster that is giving experience (such as when drinking a potion of experience or changing floors), that the piety is given unconditionally. It might need to be scaled back a little though for proper balance.

**Comment by jeremygurr** [comment]
We decided that it's okay for some gods to be bad for pacifists. We'll leave things here alone for now :)
