### ISSUE TITLE
Tree form nerf: lower uc boost and ac boost

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#217]
It's a little too powerful as is

**Comment by yrmvgh** [comment]
I would sadly agree with this, because using unarmed is almost a no-brainer with this kind of bonus. you miss out on brands, but that's ok cuz you have an occasional, if a bit unreliable, antimagic brand.

I'm having fun but too many enemies don't feel like threats with this kind of AC. And AC of this prodigous size usually costs you a bunch of armor skill, maybe some EV due to encumbrance, and doesn't stack with ozocubu's, while this does.

**Comment by yrmvgh** [comment]
In part, the OP feeling I get might have be due to this just being a good character. Even outside of tree form, it's pretty durable because the usual Vs racials have all come online, and decent defenses. 20/22/16 in humanoid form is fine for a lot of stuff, but having the ability to fall back on 51/2/16 at any moment (without ozocubu's) is pretty nuts.

**Comment by G0rg0** [comment]
Yep, it needs to be toned down a bit but I wouldn't weaken it _too_ much, things like this always seem to get over-nerfed.

**Comment by yrmvgh** [comment]
From IRC: 

> **((O))** tree-man hasn't much to worry about, gear-wise
> **((O))** what if tree man was split from lignification pot, and multiplied your armor, hp, and damage by an amount [instead of replacing it]
> **((O))** I'm not saying [that] would be better [for certain
> **((O))** just pondering. since we can wear the gear, maybe it would be good to be gear based. but, again, it's kinda cool using humanoid form as a "resist kit" and tree form for general fightin
> **((O))** did you have armour skill disabled and armor-wearing allowed at the same time, on purpose, to encourage this sort of dual-nature resist-robes playstyle? or was it actually a bug?
> **[[X]]** no, a bug
> **[[X]]** but it's an interesting idea to make lignify just boost ac and remove ev and movement, so you still have your armour and effects.
> **((O))** if you split it off from lignify[potion] and change its effects to _boost,_ instead of replace, equipment, it'll probably need a new name, and use a different tile (maybe a monster from Swamp. like bog beast or thorn hunter)
> **((O))** dodging could become less useless - reduced by a large percent instead of set to 2 in most cases
> **((O))** esp since Vs racially increase in str/dex as they level
> **((O))** zeroing out EV would make more sense if they were a str/int race - which is my next [suggestion] if you stick with actual-lignify lignify!
> **[[X]]** hmm... maybe they _should_ be a str/int race. There aren't many of those anyway.
> **((O))** they certainly have fine spellcasting apts
> **((O))** part of the reason they're str/dex, imo, is because aux attacks proc based on str+dex, so every int levelup is a levelup in which you forgo a little bit of bite %, and they have one of the best aux's in the game

They might make more sense as str/int, or str/dex, which pushes them towards casting or making the most of their aux attack, but right now their dexxy stats seem to clash a smidge with the no-EV aspect of Lignify.

**Comment by jeremygurr** [comment]
So at the moment I'm thinking of making lignify a separate form from tree form, that reduces ev (proportional to what the character has, so their ev still matters), and increases ac (but doesn't meld armour, so you still have that), and of course stops movement. 

So if you had a char with AC 10 and EV 15, after lignifying, you would get maybe AC 20 and EV 7. AC would not scale based on armour, armour would just add to it. AC would scale with XL like it does now.

**Comment by yrmvgh** [comment]
sounds worthy of a try! will it cost a big chunk of stamina? it seemed to have a high hunger cost currently

**Comment by jeremygurr** [comment]
done. Yes all previous hunger costs have been converted to stamina costs.
