### ISSUE TITLE
Pacifist mode feedback

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#218]
1) I tried SpEn in pacifist mode on easy (http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt), quaffed 11 potions of experience on D14 (entered D1-14 also) and I am only XL 8. Perhaps you may want to increase XP. Or is it intended to be under-leveled?
2) I accidentally killed a confused monster while moving. Perhaps it can be a good idea to prompt "Really attack foo?" like "!a" inscription does, at least for the first time.
3) Dungeon layout is not suited for pacifism runs, there are too many corridors. Any normal speed species without Confuse will need to kill something. Teleport scrolls are not reliable (I found only 2 scrolls and I explored more than 50% of every floor), also Formicid/Naga exists.
4) I cannot reach D15, all upstairs on D14 have dangerous wondering monsters nearby, even 15.3 Stealth with Spriggan makes it impossible/boring. Probably there are too many monsters in crawl to make pacifist runs possible (I assumed I cannot pacify monsters with Ely because it makes me lose XP and is effectively better than a kill).

**Comment by jeremygurr** [comment]
Cool, I'm glad you are trying out some of these alternative modes. This helps a lot to make them more fun. 

1) If you are playing on hard mode, level 8 after drinking all of your potions on 14... hmm maybe a bit underpowered. Probably would be level 10 or so on hard mode. I'll tweak pacifist from 30 to 50% per potion. That should give you a couple levels more by that point. 

2+3) Pacifist isn't expected to be played without any kills, since like you said dungeon layout and just bad luck is sometimes against you. You are just trying to minimize kills. Does it feel like monster kill penalty is too strong, or too weak? Right now you lose 100% of the experience that killing that monster would normally give. Should probably be more like 200% or more, but I'm not sure yet without actually doing a lot of testing.

4) You just have to kill sometimes :), even as a pacifist. Ely _should_ work harmoniously with pacifists, so that is a bug. Kills through "pacififying" should not have an xp penalty.

**Comment by Sandman25DCSS** [comment]
The game is in easy mode, that's why I think XL 8 is too low. If you expect that player cannot avoid killing some monsters, character should probably have more XP than in classic mode.
I mean classic mode characters who killed everyone and pacifist mode characters who killed a few monsters should be about the same XL.
I haven't tried pacifying so I am not sure if there is a bug. It's possible to win without killing monsters with Ely in normal crawl so I assumed that pacifist mode has an extra penalty to make game harder.

**Comment by jeremygurr** [comment]
I think this is much better now.
