### ISSUE TITLE
insight mutation doesn't allow items to stack properly, since it doesn't identify the whole class of item

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#23]

**Comment by jeremygurr** [comment]
Fixed

**Comment by yrmvgh** [comment]
I don't want to "open an issue" for this, because that is a silly use of github.

I just want to say that the "insight" mut is really cool. I've gotten it on two separate kobolds and sure, a resistance or regen might be "better", but insight is **cool**, and in the stage of the game where you don't have enough ident scrolls to go around, it's actually quite useful! Great idea, and thanks!

(I'm never sure whether you end up seeing my comments on closed issues or commits, so if you see thins one, if you could reply just this once it'll help me know in the future whether this is a good way to leave feedback on closed issues. Cheers!)

**Comment by jeremygurr** [comment]
Yeah I still get notified, which is cool. Glad you like insight. Djinni
have this natively and it advances to level 3 eventually. Each level is 4
times faster than the last, so level 3 is 16 times faster. Pretty fun.

This will be a bigger deal after I finish the identification expansion I
have planned. It will make identification meaningful and interesting even
late in the game, instead of the annoyance it is now.

**Comment by yrmvgh** [comment]
> make identification meaningful and interesting even late in the game, instead of the annoyance it is now

Lofty sentiment. :D I play a lot of other roguelikes so the Crawl ID game is pretty mild and forgiving by comparison. Circus does a lot of good things so I'm intrigued to see what happens to id!

I will have to try a djinn when this run ends. Djinn^ash sounds flavorful... if very redundant. Maybe Ru. We'll see what tempting altars crop up in D1-4! :D
