### ISSUE TITLE
Mut appeared to not take effect

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#230]
Quaff-ID'd a potion of mut on CeAm. In the message log, no device heal 1 & 2 popped up as well as clumsy or stupid. But when I checked "a", I only saw the -2 stat mut.

Unfortunately failed to get a screenshot, computer went wacky.

**Comment by jeremygurr** [comment]
Are you sure you didn't get the mutation, and then have it removed? It often happens when one mutation takes away another when drinking a mut potion. Maybe that shouldn't be allowed for a single mutation potion? It is a little confusing when it says: you feel more intelligent, then it says you feel more stupid, and you only end up with 1 out if the 3 muts.

**Comment by yrmvgh** [comment]
Ohhh, yeah. Mighta been +1 -1, not +1 +1. Wish I'd gotten the screeny! Damn my flaky computer. I'll keep an eye out.
