### ISSUE TITLE
Save-breaking updates

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#233]
Is it possible to somehow fix problem with game loading when there is save-breaking update? I cannot load my game and cannot start a new one, probably existing games should be deleted when upgrading.

**Comment by jeremygurr** [comment]
Sorry. I spent a lot of time separating version code this last round, so this issue _shouldn't_ happen in the future. It looks like your game is trying to load v1.2.3, but is that the wrong one? Did you actually start a 1.3? I can switch the version and you can see if it works, or I can just nuke that character if you prefer.

**Comment by jeremygurr** [comment]
So the current strategy keeps save breaking updates isolated, which will avoid this problem in the future, but you will still need to finish the old game before starting the new version. I plan on making a change before too long to writing save games into a YAML file instead of the current structure, which gives us the ability to avoid almost all save game breaking changes, meaning that you will almost always be able to play a new update, even if it does a save-game-breaking thing like adding mutations or branches. So this will steadily improve over time.

**Comment by Sandman25DCSS** [comment]
According to http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt it's v1.2.3.0. I am not sure which version it should be, I started it yesterday.

**Comment by Sandman25DCSS** [comment]
Just delete the game, it's easier. Thank you

**Comment by jeremygurr** [comment]
Done. Sorry, it probably got messed up when I was trying to get 1.3 deployed, but then had to roll back to 1.2.3. The new system should isolate the versions completely now so this shouldn't happen again... I hope.
