### ISSUE TITLE
vampire simplification

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#238]
just spend some amount of blood to change and stay in that form with no tedious maintenance. or, the maintenance is auto deducted if that's needed for "balance"

**Comment by jeremygurr** [comment]
I like just having an ability to change forms. It doesn't even need a cost. 

Forms:
bat
bloodless: rC++, rP*, rN+++, rTorm, rRot, no regen
thirsty: rC+, rN+, rP+, normal hp regen
alive: high regen, stamina is consumed

**Comment by yrmvgh** [comment]
I would change the forms' names now, because they no longer have anything to do with blood drinking.

Avatar of Death
Vampire (fall into this mode if petrified, out of stamina, etc)
Illusory Mortal
BAT!

**Comment by Sandman25DCSS** [comment]
Having free transformations will be a huge buff, it should take much time (maybe even 10-15 turns, interruptible) and incur Exh status IMHO. Otherwise player will switch between Alive/rPois in Lair, Alive/rTorm in extended, Alive/Bat Form for escape etc. Alive is really OP status, it's like Regen++ as far as I remember.

**Comment by jeremygurr** [comment]
Good point. 

Bat form is intended to be an escape form, so having a high turn penalty there makes it useless. What if a transformation burned through half of the player's mp (keeping it similar to other transformation spell costs and mechanics), but cost 1 turn like before. Then they couldn't rapidly change forms (they would have to wait for mp regen). And of course regen++ would cost major stamina (which is already the case since hunger costs have been translated to stamina costs). If stamina ran out for alive form, regen simply stops. They stay in alive form, with all the normal lack of buffs that the other forms have. All regen activity only occurs if the player has stamina to pay for it, making it stop when stamina is too low.

**Comment by Sandman25DCSS** [comment]
Why did you change Regen to deplete stamina? It makes Regen items (unless it's amulet which can be removed in fight) strictly bad as having attacks deal 50% more damage is more important IMHO.
I hate bat form, it's OP and results in degenerative gameplay (annoying time-consuming kiting and safe escape).

**Comment by jeremygurr** [comment]
I didn't change regen. It already had a hunger cost associated. Didn't it? And it should only kick in when the player is wounded and needing the regen. 

Yeah it makes sense that having 50% more damage trumps regen, if you had to choose, but you can have both if you can kill the bad guy fast enough, or if you have fruit to spare, or if you have items that boost your sp pool. Seems like a meaningful decision. Not only that, but it's not always optimal to engage dangerous enemies in power mode, since it reduces your escape chances. If this degenerated to exactly one optimal playstyle, then it would need to be changed. But I'm not sure I'm seeing that yet. 

I only ever used bat form to escape. It can be used for effective kiting? If so, then something needs to be changed there. I'm not sure that is the case with the stamina system, because bats still move at slower than monster speed when not in power mode. And if we can add the movement penalty back for power mode, kiting I think becomes quite impractical.

**Comment by Sandman25DCSS** [comment]
See for batform: https://crawl.develz.org/tavern/viewtopic.php?f=8&t=19660&p=265917#p265917
I got impression that you changed regen to drain stamina points even in normal mode so eventually regen is stopped and player cannot switch to power mode. This is why I believe regen items are strictly bad.

**Comment by jeremygurr** [comment]
Yeah regen drains stamina even in normal mode because it has a hunger cost, and I translated all hunger costs into stamina drain. This of course can easily be changed if we have a good reason to.

I think between the movement penalty and stamina limits, bat form will be okay. But if that proves otherwise, I will definitely change it.

Same for regen. If players discover one optimal path and lose choice, then I will change it. At the moment, I think I would still choose regen items in many cases, especially if I had a good number of fruit or royal jelly, or had a higher sp pool capacity from items or race. But maybe after playing for a bit we will discover otherwise.
