### ISSUE TITLE
More general solution to various scroll issues?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#240]
[Conservation](http://crawl.chaosforge.org/Conservation).

In a typical game, you get way more RC scrolls than you could possibly ever need. But if you're playing Ash, suddenly you need all those scrolls and even getting a few below average can be quite painful.

Instead of giving everyone an Ash amount of RC scrolls, give Ash worshippers a 60% chance to conserve an RC scroll whenever they they use it. Then you don't need to dump so many spares on non-Ash players.

Jiyva followers could have a 20% chance to conserve any mutation-related potion that they drink. Ds and Ko could have their own 20% chances, meaning ds/ko ^ jiv would overall have a 36% chance to conserve.

Lava orcs could have a 50% chance to conserve scrolls of immolation.

I think there's a lot of design space here for "spawn an amount of consumables that's reasonable for a normal game, but allow (foo) to have access to X%" more, without having to rely on the Gifting system which can get a little out of control. (leading to the recent huge nerfs to Pakellas on trunk)

**Comment by Sandman25DCSS** [comment]
I think standard crawl moves into opposite direction: scroll of enchant weapon always works reliably, ammunition mulching was tested. I don't see why the same item should work differently for different species. For the record I dislike changes to potion of heal wounds too.

**Comment by jeremygurr** [comment]
what do you mean ammunition mulching was tested? Isn't all ammunition occasionally mulched now? 

Yeah there is some value in an item working consistently across all characters. 

It isn't hard to change spawning rates based on the player. But I don't want to do it unless there is a strong enough case for it, since it is added complexity for the player. I don't think ash characters needs more RC scrolls than any other character. If that became a real problem, we could change ash to not use rc scrolls for cursing. There are several alternatives that I think would work. But I'm not really seeing that yet. The point of Ash is that you are giving up your ability to swap equipment as much as you normally would. It should be dramatically less than normal. That won't happen if you always have plenty of RC scrolls and can usually change whenever you want.

**Comment by yrmvgh** [comment]
I'm saying there should be fewer RC scrolls in the general case, and then ash can have a Conservation-style passive to ensure the player has enough to uncurse/curse when upgrading to new equipment.

Rather than now where there's too many RC scrolls in general, but it's needed because 1) you might pick ash and 2) DCSS is inconsistent, it doesn't appear do the brogue thing of "guarantee a certain range of the important items, then spawn the rest more randomly." They dump a giant basket of curse scrolls on our head, because they know it sometimes rolls low - my 0.17 OgHu^Ash definitely experienced the bottleneck of one of those rare low roll games.

**Comment by Sandman25DCSS** [comment]
See https://crawl.develz.org/tavern/viewtopic.php?f=8&t=15819&p=216484 for mulching

I agree, Ash does not need any changes, current balance is fine/fun.

**Comment by jeremygurr** [comment]
the mulching experiment is quite interesting. Definitely there's value in removing the tedium of picking up ammo. I'm tempted to remove ammo entirely. Ranged attack damage may need a nerf in that case, but does ammo really carry it's weight in gameplay value? I'll create a separate issue for this so it can be discussed.
