### ISSUE TITLE
Permanent transmutations can feel a little cheesy, but I think they're a step in the right direction

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#244]
Once you find the necessary equipment, there's nothing stopping you from equipping a bunch of spell enhancers, casting Blade Hands once with very low skill, and going to town. It's not the most busted thing in the world, but it's a little on the "freebie" side of things.

Not having to re-cast stuff is awesome, and I think it should work with more spells.

One of the reasons it works so well with Transmutations is that you can only have one running at a time. I'd be willing to, say, pick Ozocubu's OR condensation shield, and forgo the other, if it was perma up (fire could temporarily halve or suppress the effect, instead of ticking down duration).

A possibly usable balancing factor: Tome4 has a lot of always-on buffs, but each one "reserves" some mana from your mana pool, and the best ones reserve a very large chunk of mana, which means that you have to be choosy about which one(s) to run, and some of them are out of reach for Adventurer killdudes builds, because they don't have a big enough mana pool.

So it could wind up something like this, perhaps:
- Most self-buffs are always-on
- Always-on spells reserve mana from your pool equal to, say, spell level *2 + XL/2, with up to a +10 extra fee for the bestest, Zig-quality spells.
- You can't run two buffs that share a school, with special exceptions for Charms (which has contam and/or normal durations on many of its spells) and the buffs that are intended to "go together" such as stoneskin+statue form.

**Comment by jeremygurr** [comment]
I like the mana reserving idea. This may be a better way to do summons too.

**Comment by Sandman25DCSS** [comment]
Many transmuters don't care about MP. No, I don't have any idea how to fix the problem.

**Comment by eyestalker** [comment]
Make each hit with a transmutation spend a bit of MP/have a chance to, duh. Not proportional to the spell cost though, or you'll end with current Summoning situation (high-level spells being literally unusable).

**Comment by G0rg0** [comment]
Mana reserve seems like a good idea.

**Comment by SleepySteel** [comment]
I think they feel more than cheesy- infinite transmutations might be the easiest run I've ever had. Granted I only have one rune so far but I've not had to do anything other than hold tab the whole game. You just need to cast blade hands and then put on your non-caster gear- or if you're as hilariously lucky as I am, cast dragon form or hydra form and enjoy your free rampage.

**Comment by jeremygurr** [comment]
Ok I can understand how casting blade hands then getting non caster gear on is OP as it stands. But I don't quite understand the hydra form part. You can use any armor in hydra form right? In a typical hydra form battle in vanilla crawl, do you need to recast hydra form in the middle of battle? Unless you have to cast it repeatedly in a battle I'm not sure I see the difference from vanilla crawl.

**Comment by yrmvgh** [comment]
The main difference is that you can brute force cast it even with very low success odds, and once you get it to stick you're good thenceforth. Plus careful mode. In vanilla, you want to get good success rate so you can reliably have it.

**Comment by jeremygurr** [comment]
I do like the idea of a form slowly unraveling when it is hit. It's not necessarily needed but at least worth a brief consideration. 

So what if mp is lost each time damage is done to the player. Not related to form, only damage done. A player could still quaff a magic potion to keep up the form if needed, and their mp regen is still functioning normally. But if the mp runs out, so does the form, and it needs recasting. Which of course won't be trivial if they are out of mp in the middle of a battle. 

It's simple to understand, but still a meaningful limiter in cases where the player is overpowered or has too little mp. This would make mp more meaningful for transmuters, which may or may not be a good thing. But my instict is that it might be a healthy nerf to muters to make them depend on mp a little more.

**Comment by jeremygurr** [comment]
This might help with blade hands being too powerful with heavy armour. If the spell unravels in that case, the player must finish the battle without blade hands, and without the abilty to use magic normally because of heavy armour.

**Comment by Sandman25DCSS** [comment]
Jeremy, could you please describe your reasoning behind changing how Transmutation work? I am not sure what problem we are trying to solve. Did you feel boring to cast Tm before every fight? But it made success chance important, MP important, time important, which form to cast important...

**Comment by Sandman25DCSS** [comment]
Blade Hands is not a no-brainer by the way, being unable to use any wands and decreased success chance for all spells (hint: Haste after some nasty monster comes into view middle fight) can kill.

**Comment by yrmvgh** [comment]
Yeah, I've definitely found staying in-form to be hazardous. The form + trog thing is a silly build - having ways to handle stuff when you drop form is important, and at that point being able to switch to a more suitable form is a good thing, so having a "proper" amount of skill is still a good idea. But you can also drop form, use melee skills / throwing / evocables / other spells, and then post-fight cheese into a form that's way above your level once again.

Maybe as a band-aid fix, Careful Mode should be special cased not to work on forms?

**Comment by jeremygurr** [comment]
The transmutation change is mostly about avoiding that extra prep-before-battle cycle that many spellcasters already have to deal with. It's not unreasonable to have a powerful spellcaster that gets into a tough fight, turns on hero, maybe finesse or haste, maybe even quaffs a potion or two, casts ozo armour or an ice shield spell, then transforms in their preferred form, then dives into battle. If there's a change that can reduce this without taking away important strategy from the game, it is a good thing. Entire spells have been removed because of this cycle in vanilla crawl. 

I can see that it makes spell success chance not a big deal for Tm spells, It does retain it's importance if the transmutation unravels during a battle. And I think there should be more monsters that can dispel a form as well. Then a player will need a backup plan and ideally a way to get back in their form quickly should that happen.

Some of the others who are testing this fork strongly prefer the new transmutation mechanism, or I would be tempted to just scrap it. But I know enough that you may well recognize issues that those of us who are less experienced can't see yet. So, ideally, I'd like to find a solution that works for you and still accomplishes what is making it more fun for some of the rest of us too.

**Comment by Sandman25DCSS** [comment]
I would agree with your reasoning if players were casting the same spell in all battles and would never fight without forms. My experience shows that it is not the case, for instance here is my offline DrTm game (15 runes):

```
Action                   |  1- 3 |  4- 6 |  7- 9 | 10-12 | 13-15 | 16-18 | 19-21 | 22-24 | 25-27 || total
-------------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------++-------
 Cast: Beastly Appendage |    27 |    21 |    10 |     2 |     4 |       |       |       |       ||    64
      Spider Form       |       |    23 |    38 |    12 |     3 |       |       |       |       ||    76
       Ice Form          |       |       |       |    63 |    45 |     7 |       |       |       ||   115
       Blade Hands       |       |       |       |       |   178 |   171 |   149 |   133 |   120 ||   751
       Hydra Form        |       |       |       |       |       |    39 |    39 |     8 |    24 ||   110
      Statue Form       |       |       |       |       |       |       |     1 |    16 |    10 ||    27
       Dragon Form       |       |       |       |       |       |       |     1 |     2 |     9 ||    12
       Necromutation     |       |       |       |       |       |       |       |       |   317 ||   317

```

As you can see I used quite a lot of forms and I am sure I fought in my natural form also. Sometimes I even quaffed brilliance when I really needed to enter some form.
You like to give player more options/decisions but IMHO in this case you are removing them, triple costs makes player decide in advance which form to use and wizardry items make Tm too easy.

**Comment by Sandman25DCSS** [comment]
Also new Tm mechanic makes spell miscasts irrelevant which is bad IMHO. I remember I had 3 miscasts in a row with 1% failure chance for Necromutation, that resulted in fun situation.

**Comment by Sandman25DCSS** [comment]
Another thing is that I got miscast from Necromutation at 1% and started petrifying with monsters in LoS while being unable to quaff cancellation, it was fun too.

**Comment by jeremygurr** [comment]
So maybe with the form degradation mechanic, the cost of Tm can go back to normal. This should bring things closer to normal crawl tactics, minus a little bit of extra work when staying in one form works for multiple battles. There should be significant enough negatives with most forms that players won't want to always stay in that form. Between that and the form decaying from time to time because of damage, this will force occasional recasting, making spell failure more relevant.

**Comment by jeremygurr** [comment]
Now trying to reform when you are out of mp can be a problem. 

We could leave it as is, to provide a different kind of challenge. It would be a Tm nerf, but that could be counter balanced in different ways.

Or we could just not take mp from damage, but instead just cause damage to reduce a counter. Once that counter is gone, the form dissolves. Maybe the size of this counter could be proportional to spellpower, with a base minimum that still keeps the form usable for low spellpower cases, allowing SE to still be effective Tm.

**Comment by jeremygurr** [comment]
Just as an interesting thought: those times you got miscasts for a 1% failure rate, I bet your real failure rate was more like 5%, and the game was displaying it incorrectly. The chances of getting 1% failure 3 times in a row is exactly 1/1,000,000. You'd probably win the lottery more often :). But if it was 5%, it would be 1/8000, which is still rare, but a lot more likely than the other.

**Comment by jeremygurr** [comment]
I don't like the invisible aspect of tracking damage in a counter to determine form decay, so I came up with another possibility:

So I'm thinking of doing mp decay like before, but after the form unravels, you gain the amount of mp needed to cast that same form again. In this situation I think we can make keep the Tm at triple cost. 
The triple cost makes it a little harder to just pull off a powerful Tm spell early game with careful mode.

**Comment by jeremygurr** [comment]
Okay that won't work because then the form will just be dissolved immediately... hmm...

**Comment by jeremygurr** [comment]
Ok I got it. What if every time a transformed player is hit, their spell failure chance is hit again. If the spell fails, the transformation ends. If they have a high failure rate, they won't be able to maintain the form for long. If they don't, it won't be much different than vanilla crawl, since they usually don't have to recast a form during battle anyway.

**Comment by Sandman25DCSS** [comment]
I think you can try to do it like Repel/Deflect Missiles work. As far as I know the spells have a chance to end every time a missile is deflected/repelled and the chance depends on spell power. For Tm it would mean the check should happen after every attack of player (i.e. when player melees something).

**Comment by yrmvgh** [comment]
If it does re-check spell failure, it should be 5% or 10% easier to keep on than to cast - if a vanilla player gets spell failure down to 10%, then they're pretty much fine and that's a good place for us to be too.

**Comment by G0rg0** [comment]
@Sandman25DCSS 

I agree the check should be on attack rather than taking damage, if it were, any time a player was surrounded and taking a bunch of hits, they might as well not even bother with the form. Even if they were at a relatively low fail %.

**Comment by Sandman25DCSS** [comment]
Offtopic.  I cast Necro literally hundreds of times in extended in many games so it is possible that it was 1% miscast really, it happened just once ;)

**Comment by jeremygurr** [comment]
Ok, each time the player attacks (melee or ranged), the game will check spell failure when you are transformed. Maybe % of attacks will cause a fail check, and if the spell "fails" the transform is dissolved. 

Hmm... lets try this. Having a 20% failure rate you should be able to stay in a form for a little while and be able to do some damage before getting dissolved. So if there was a check 20% of the time, you could average 5 attacks per check, and with a 20% failure rate, you _should_ end up with 25 or so attacks on average, which is probably plenty. Maybe too much? It's easy enough to change though. Chances of having your form dissolve on the first attack: 4%. Chances of it dissolving within the first 10 attacks: 33%. That actually sounds ok. So 20% failure rate will make a fairly weak transmuter that will dissolve back in the first 10 turns 1/3 of the time. So on average they would get to about 17 attacks.

At 10% failure rate, they would get to 35 attacks on average before reverting. 
At 1% failure rate, they could attack hundreds times before reverting on average.

So to contrast, if the game checked failure rate 50% of the time instead of the above 20%:
At 30% failure rate: 4 attacks
at 20% failure rate: 7 attacks
at 10% failure rate: 14 attacks
at 5% failure rate: 28 attacks

Looks like about 25% check rate is probably a good place to start.

**Comment by jeremygurr** [comment]
Hmm, I suppose spell casting and wand / rod usage should also count as "attacks". Otherwise necromutation gets a free ride...

**Comment by jeremygurr** [comment]
ok it is deployed. When you get a chance to create a new 1.4 character, tell me how the new mechanic works for you.
