### ISSUE TITLE
Got Dj mutation as non-Dj

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#25]
My Deep Elf got this:
 28933 | D:14     | Gained mutation: You occasionally figure out what unidentified objects are. [potion of mutation]
Not sure if it is intended

**Comment by jeremygurr** [comment]
Yes this is intended behavior. Tell me if you think it doesn't work well for some reason. I think it's interesting for there to be a chance for others to get the Dj mutations, both good and bad. I may need to tweak the frequency of them though. It should be quite rare to come across the insight one, since it is so powerful. But the bad one that Dj has, glow, should be as common as other bad ones I think.

**Comment by Sandman25DCSS** [comment]
I love it of course, it is great to have items identified for free.
I hope it is not possible to get "unable to read", that would be too cruel IMHO

**Comment by jeremygurr** [comment]
Lol. No it's not possible to get unable to read. I did however enable a few obscure mutations that were already in the code, most of them very rare, like "missing an eye", and "slow learner". We'll have to see if those work or not as random bad mutations. 

-- Jeremy
