### ISSUE TITLE
recharge / wand changes may make it harder to appease a trove

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#250]

**Comment by jeremygurr** [comment]
hmm, what are you running into?

**Comment by yrmvgh** [comment]
if you recharge a wand, it has a lower max. if you then get to a trove that wants that wand, and it's a rare wand, you can't fulfill the trove

**Comment by Sandman25DCSS** [comment]
Also stacking wands is bad for trove reason, you are unlikely to want to give your only wand of heal wounds with 45 charges (instead of standard one with 9)

**Comment by Sandman25DCSS** [comment]
Maybe provide a command to unstack a wand? So you can get wands with 9 and 36 charges out of wand with 45 charges?

**Comment by jeremygurr** [comment]
The numeric drop command should allow the "stack" to be split. And it would be split based on max charges. So I have a wand of healing 5/20. I say to drop 5 charges (since the trove requires it). I get a wand 1/5, and a wand 4/15. But maybe the trove requires a 5/5 wand of healing. So you'd either have to give it the 5/20, or split and use a recharge scroll. This seems okay to me since troves aren't supposed to be super easy to get into anyway.

**Comment by jeremygurr** [comment]
We may also need to ease up the trove wand requirement, because of the max nerfing. Maybe it requires wands with half as many max charges on average.

**Comment by G0rg0** [comment]
I can't remember the last time I actually managed to get into a trove and the reward wasn't even that good.
It would be nice if the troves gave you more than one option to enter. Like sac all of your piety OR give a +5 ice dragon armour.

**Comment by Sandman25DCSS** [comment]
I think bad troves should stay, I wouldn't want to have the choice between two requirements.

**Comment by jeremygurr** [comment]
I've found some pretty sweet troves myself. But bad troves make the good ones all the more awesome when you are lucky enough to find one. However, I don't think it would hurt that much to spawn more troves. Maybe 1-3 in an average game, each with their own requirement.
