### ISSUE TITLE
remove food shops

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#253]

**Comment by yrmvgh** [comment]
Partially complete. "random shop" still has a small chance to make a food shop, but overall players will be seeing a lot less food shops. In theory the dreaded Orc4 ending with 2 food shops is gone. :grinning: 

@everyone - should random food shops stick around, in order to sandbag shops from being too good, and to occasionally give you a bunch of fruit for stamina spamming?

**Comment by jeremygurr** [comment]
I think random food shops should stay for now. Although they should be rare enough not to make stamina meaningless. We may need other fruit items eventually. Royal jelly should occasionally be sold there, which is pretty powerful.

**Comment by yrmvgh** [comment]
Probably close this?
