### ISSUE TITLE
Difficulty levels: do we really need/want them? 

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#255]
There was a comment in the rune curses issue about an easy 15 rune game being more difficult than vanilla crawl, with normal and difficult setting 15 rune runs being insanely hard.

I'd prefer there be one difficulty setting that inherently scaled by how far you get in the game itself, driven by adjusting the branch difficulties etc. I really like being able to have a 1-1 comparison between games.

So a 3 rune win would be roughly the same as vanilla, perhaps even slightly easier. A 5 rune win would be quite challenging, 10 a major feat and 15 would be that pinnacle of insanity that "difficult" covers now.

If we keep the different levels, let's please change the naming:
Easy>Standard
Normal>Difficult/Challenge
Difficult>Impossible/Insanity

**Comment by jeremygurr** [comment]
How about: standard/challenge/nightmare?

**Comment by Sandman25DCSS** [comment]
Presence of difficulty levels is main reason why I am here. Hard mode allows to play some fun species which are not that enjoyable normally due to being too easy.

**Comment by jeremygurr** [comment]
I definitely see the value in having one difficulty to compare with, but it would be quite a challenge to pull that off and still maintain what we have now. 

And thinking about it further, it really isn't any more difficult to compare a easy mode 3 rune win to a hard mode 3 rune win than it is to compare a felid 3 rune win to a cave troll 3 rune win. Or even to compare which runes each game obtained could show different "difficulty levels".

**Comment by G0rg0** [comment]
If people really like the difficulty levels, they should stay in, but what do you guys think about the renaming? I like the standard/challenge/nightmare idea.

**Comment by Sandman25DCSS** [comment]
I think we cannot call "standard" what is easier than vanilla crawl. Probably they should be renamed after rune curses are implemented.

**Comment by G0rg0** [comment]
I thought what is currently easy mode was supposed to be harder than vanilla to win a 15 rune game. Is that incorrect?

**Comment by jeremygurr** [comment]
Fair enough. Rune curses are coming soon anyway. 

Yeah easy mode will be much easier than vanilla for a 3 rune win, but much harder for a 15 rune win. Even at 5% hp increase, and even if you ignored other curses, you have monsters with twice the hp of normal when you have 15 runes (+108%). Then add the rune specific curses, and I think you still have a formidable challenge. At 3 runes monster hp is at +16%.  

For reference, in a normal mode game at 15 runes, monsters will have +318% hp. On hard they would have +714%. It should earn the name "nightmare". Or maybe insanity really is better :)

**Comment by Sandman25DCSS** [comment]
I see, it will make many combos and gods unplayable and some tools like distortion and speed even more important. Currently it is a bad idea to melee Antaeus, with 714% HP it will often be a bad idea to melee most monsters.
I have actually tried 200% HP (https://crawl.develz.org/tavern/viewtopic.php?f=12&t=16700&p=230068), it was fun but felt very time-consuming to hit something 20 times to finally trigger banishment/teleport. All characters will need to have huge defence of course.

**Comment by jeremygurr** [comment]
Yeah but what if the level 27 cap was gone? And all the other changes, most of which are significant buffs to late game characters? We need more "hard" to make room for more solutions and tools and strategies. If more solutions and tools are added without making the game harder, it just makes it too easy and boring.

**Comment by Sandman25DCSS** [comment]
If both player and monster have more HP, it changes nothing except:
1) forces player to press more keys and spend more time (both real and in-game)
2) makes fight more predictable

**Comment by jeremygurr** [comment]
even without rune curses, going from early game to late game already creates a situation where both player and monster have more HP. What's the difference? Why is late game still fun? Is fighting more predictable in late game because monsters and players have more hp than in early game? No, because they are very different, just like the rune specific curses and many new late game items / mutations / branches / monsters will make it different, requiring the player to come up with new strategies.

**Comment by Sandman25DCSS** [comment]
Late game damage scales with player HP so basically nothing changes during game, player still can die in 3-4 attacks as before. I assumed that you are going to increase player/monster HP WITHOUT changing monster damage. I don't think it will be fun to fight Quokka with 3 damage and 100 HP when you deal 3 damage and have 100 HP too. You can feel it by using a quickblade, for example.

**Comment by jeremygurr** [comment]
Hmm... late game monster damage is a threat to the player now, but wouldn't be if the player had a lot more hp, and tools to fight and escape with than now, even if the monster had more hp. Yeah we will definitely need to address more than just hp. Maybe hp increase could just be one of the curses?

**Comment by Sandman25DCSS** [comment]
Another solution is to keep both player and monster HP unchanged though I suspect you don't like it ;)

**Comment by Sandman25DCSS** [comment]
One of the reasons why I think it is good to keep HP unchanged is that it allows to easily use future monsters from standard crawl. If devs create something interesting (they do it in every release), it will be straightforward to borrow it into your fork without any changes.

**Comment by Sandman25DCSS** [comment]
You reminded me this:
https://crawl.develz.org/tavern/viewtopic.php?f=8&t=18988
It's a description of power creep problem which seems to be realized by most crawl devs at this point

**Comment by jeremygurr** [comment]
The power creep discussion is interesting. I'm not sure I came across a clear solution there though. Yes it is basically meaningless to increase monster difficulty and player power. But that's assuming no additional interest and strategy is added. 

So currently in vanilla crawl there is a level 27 cap, Power can somewhat advance beyond that with players training different skills or finding new items, but it's definitely a lot more beyond that point. Why not have a level 10 cap? Or a level 5 cap? Would cutting out the "power creep" of more powerful player and monsters from the level 5+ game improve the fun of the game? Once you have 5 levels of a game built, how do you know whether to stop there or to add 5 more levels, with more difficult monsters and more powerful items/potions/etc? 

What about cutting out healing and haste potions, and making monsters easier to compensate? Isn't that reverse power creep? And it power creep is fundamentally bad, then the opposite should be fundamentally good. 

Clearly that is not the case. On the one hand you have a power creep that only introduces new challenges to be perfectly balanced with stronger players without any added strategic space for the player to learn and grow in. On the other you have increased monster difficulty and player power through carefully selected enhancers that require additional skill and problem solving to learn to use well. 

For a game to be fun it must have a motivator that drives the player forward, rewarding them when they've made good choices, yet also delivers enough challenges to keep things interesting. Theoretically there is no limit to how long a game can do this. It's only limited to the imagination of it's designers. Look at how long ultima online has been developed and played and expanded upon. 

So you are suggesting keeping hp unchanged but still having the rune curses and other player buffs that will come later? Or are you thinking of a different way to balance things?

As far as the hp changes making it harder to merge in vanilla crawl changes, that doesn't really apply to the hp scaling from rune feature, because it doesn't directly touch those values at all. The code is in a separate place that operates on all monsters as a whole, so any new monsters vanilla crawl introduces would be seamlessly integrated into the rune curse mechanic without any changes needed. 

There's actually a huge nerf I really want to do, that would be an alternative way to address this issue. But it seems to be quite unpopular.

**Comment by Sandman25DCSS** [comment]
Yes, I think you should stop buffing player (at least in hard mode). I recalled power creep thread because you seem to always start with buffs and then trying to nerf either it or something else to make it not so OP.

Some monsters with changed HP will be quite different, for example, consider Ancient Lich who created a couple of fiends (and you can no longer expect to kill the lich before your HP becomes a single digit), Ironband Convoker who cannot be prevented from recalling monsters or that monster who unconditionally decreases your AC and slaying with corrosion, Boggarts who create several giants but can no longer be one-shot with most attacks etc.

**Comment by Sandman25DCSS** [comment]
Probably "should" is not a right word (sorry my English), I meant that it could be better to try different approach :)

**Comment by jeremygurr** [comment]
I'm willing to try each way and see which works best.

**Comment by jeremygurr** [comment]
Done
