### ISSUE TITLE
Geometric scaling for most attributes and skills

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#256]
I am not sure how you are going to balance it. It looks like all species will be extremely inflexible. I mean what's the point of learning magic on species with high Str when you can kill everything in 1-2 attacks with melee? Similarly why to train weapon on SpWz who starts with 4 Str?

If you want to see how it works, you can try "experimental (cyc)" branch on https://crawl.project357.org where Ogre with GSC reliably kills Orb of Fire with 3 attacks, most other monsters die in one attack.

**Comment by yrmvgh** [comment]
What **is** cyc? When I looked it up, all I found was a section of the Tavern.

**Comment by Sandman25DCSS** [comment]
It's cyc indeed, the branch has implemented some crazy ideas from tavern.
You can see commits at https://github.com/crawl/crawl/commits/cyc

**Comment by Sandman25DCSS** [comment]
The commit that allows to feel how broken increased damage is https://github.com/crawl/crawl/commit/8bf63ef44f3a40119b81835133df10376ee5f68e

**Comment by jeremygurr** [comment]
we aren't talking about increasing damage. We are talking about making every +1 str meaningful. Damage could go up or down based on how the rest of the game is scaled to fit. 

This would almost certainly involve making +str items more rare (and with smaller boosts), and gaining str as a species would be much more infrequent. Yes you should be able to really feel the difference between a spriggan at 5 str and an ogre at 15 str. Right now, the ogre would cause 3x damage compared with the spriggan. With a doubling scale every 5 levels, the ogre would cause 4x damage instead. Not a huge difference yet. But by 25 str, the ogre is at 16x damage compared to the spriggan, That would be equivalent to 80 str with a linear system. So if an ogre would normally end up with say 35 str in vanilla crawl (7x damage of 5 str), with the geometric scaling, they would instead end up with 19 str, and do the same amount of damage as the 35 str in vanilla. 

The whole point of this is that currently, getting an item that adds 3 str to an ogre that already has 35 strength is pretty much meaningless. It would increase their damage by 8%. But with the geometric scale, that 3 str buff would increase their damage by 51%, which is meaningful.  So even into late game the player still has important strategic decisions that would have otherwise been lost, making the game more boring than it needs to be.

**Comment by Sandman25DCSS** [comment]
So you are changing Str to lower values but making every point more meaningful? I am not sure it changes balance then, it's similar to how SH was halved in some crawl version to make it easier to compare to EV.

Have you used fsim to analyze how Str works in standard crawl? It is not a linear system and every Str is meaningful already, at least for weapon with high base damage.

**Comment by jeremygurr** [comment]
after looking at the actual damage calculating function, I discovered some interesting things: 

Interestingly, 9, 10, and 11 str deliver exactly the same damage! So if you are at 9 str you get exactly nothing from a +2 str item. Talk about spoilery...

Also there is a trivial amount of difference between str 1 and str 5 because a different scale is used if str is <9 than the one used for str >11

Here's the dirt:

str 1: 74% (of base damage)
str 5: 85%
str 10: 104%
str 15: 123% (+19%)
str 20: 142% (+19%)
str 25: 162% (+19%)
str 30: 181% (+19%)
str 35: 200% ...
str 40: 219%

So when I said before that 15 str does 200% more damage than 5 str (=3x), it's actually 44% more damage. So an ogre at 35 str that finds a +3 ring of str would do 6% more than his previous damage, which continues to diminish as the player gains more str. Yeah I wouldn't be wasting time on that ring. 

That is a linear scale, since each level goes up by the same amount of damage as the previous. 

What I'm proposing:

str 0: 25%
str 1: 29%
str 5: 50%
str 10: 100%
str 15: 200% (x2)
str 20: 400% (x2)
str 25: 800% (x2)

so a str 40 character with the old would be = str 16 with the new. Each +1 str gives 15% increase in damage, no matter what str the player has. So a spriggan at 5 str in the old would be 9 str in the new, and would do the same damage as before. The difference is that adding str to a spriggan now means much more than it did before. 

If needed, the doubling could be every 10 levels instead of every 5:

str 0: 50%
str 5: 71%
str 10: 100%
str 15: 141%
str 20: 200%
str 25: 283%
str 30: 400%

Then every level would give 7% increase in damage instead. That might be even better. Then a str 40 in old would become a str 21 in the new. And a 5 str spriggan would become a 8 str spriggan in the new.

**Comment by Sandman25DCSS** [comment]
Will starting Str be changed for species? Str 40 is not unheard of and while 219% damage is huge, it is not OP (without Transmutations). With your system Str 40 would cause 1600% or 800% damage, this is clearly OP even without Transmutations.

**Comment by jeremygurr** [comment]
with a doubling every 10 levels mechanic, str 40 would be achieved as often as str 191 is in vanilla crawl. Which is obviously never :)

Yeah starting species attributes would need to be adjusted, as well as how often/how much attribute increases would happen. It's a fairly big recalibration effort, and is a way further down the line compared to many other features I'm considering.

**Comment by Sandman25DCSS** [comment]
Then I don't see why you are doing it, it's really similar to SH reform. Just create Str+20 rings if you want ;)

**Comment by Sandman25DCSS** [comment]
Or rings with new {Damage*2} property

**Comment by jeremygurr** [comment]
you aren't understanding the problem. A geometric scale is fundamentally different than a linear one. A geometric one makes all +1 increases meaningful, regardless of the current level of the player. A linear one does not. Just making a +20 str ring under the existing linear scale would be vastly OP for early players and barely usable for late game players, exactly the opposite of what I'm going for. This is nothing like the SH reform change which just cut all numbers across the board by the same ratio.

**Comment by Sandman25DCSS** [comment]
Ok, let me understand the problem. In current crawl Str+20 corresponds to +77% damage  no matter what your Str (using info from your earlier post here: Str 10 to Str 30 increases damage from 104% to 181%, Str 20 to Str 40 increases damage from 142% to 219%). You want to replace it with Str+4 which gives +80% damage at Str 10, +160% at Str 15, +320% at Str 20, correct?
Then it is not SH reform indeed, I was wrong. But I still don't understand why you need Str+4 instead of Str+20 provided 77% is pretty close to 80%. I mean you can change the scale but you don't need to change starting Str.

**Comment by yrmvgh** [comment]
Without getting into the debate over what makes most sense in the normal 10-30ish range of Str, I think the reason 1-9 are special cased is so that heavy stat drain and malmutates don't end your game in an unrecoverable way.

**Comment by Sandman25DCSS** [comment]
I think it's because SpWz starts with 4 Str without any drain/malmutate and it still should be able to kill things with melee.

**Comment by jeremygurr** [comment]
in a linear scale, the **raw** amount of damage increase that every +1 str gives is the same. In a geometric scale the **%** of damage compared to what you were doing before is the same for every +1. +1 point of damage when you are already doing 100 points of damage is nothing. But +10% damage when you are doing 100 points of damage actually means something. 

so with the linear scale, str+20 would give 77% more raw damage than before, but not 77% more than the damage you were doing, which is what the str+4 ring would do. Observe:

old way:
str 5 char damage: 85%
str 5 char with str+20 ring: 162%
str 20 char: 142%
str 20 char with str+20 ring: 219%

new way:
str 8 char (equivalent to 5 of old) damage: 87% 
str 8 char with str+4 ring: 115%
str 15 char (equivalent to 20 of old): 141%
str 15 char with str+4 ring: 187%

lets say the base damage done is 10.

The weaker character without the ring does 8 damage in either system. Adding the ring: 16 points of damage old (100% more than without), 11 points of damage new (33% more than without). 

The stronger character without the ring does 14 damage. With the ring: 21 old (50% more), 18 damage new (33% more, just like before) 

see how the same ring adds 100% damage to the early character, but only 50% damage to the later character with the old system? With the new, it is 33% each time. The exact percentages don't matter and can be adjusted in either system. The fundamental difference is the property that the % increase over not wearing the ring is the same no matter what str the character has in the new system, but can vary considerably in the old, heavily favoring low attribute characters while having very little impact on high (for example, on a str 40 character, that +20 ring gives a 35% increase, instead of the 100% increase for the str 5 character). And that's for a +20 ring! For +20 str to only give a 35% increase means that adding that 1 point of str late game really means nothing.

**Comment by jeremygurr** [comment]
Yes the 1-9 are special cased because of heavy stat drain. However, it's just a bandaid over the deeper problems I'm trying to address here. For a stat drain to be "heavy" for a late game character, it needs to drain 5-10 points, which is not that huge when you have 40 str. But that same drain for an early character is devastating. With a geometric scale this problem goes away automatically, because -3 stat has the same significance whether you have 50 str or 5 str. Observe:

old way: 
a str 40 character would have to lose 30 str to cut their damage in half
a str 30 character would have to lose 22 str to cut their damage in half
a str 20 character would have to lose 20 str to cut their damage in half (because of the different rules for <9)
a str 10 character couldn't ever have their damage cut in half

so if you caused 5 stat drain, it would have little impact on the 40 str character (8% loss)
but a 20 str character would have a 14% loss
but then a 5 str character would have a 40% loss, even with the different formula they use there to temper it.

new way:
a str 40 character would have to lose 10 str to cut their damage in half
a str 30 character would have to lose 10 str to cut their damage in half
a str 20 character would have to lose 10 str to cut their damage in half 
a str 10 character would have to lose 10 str to cut their damage in half 
so a flat 5 point stat drain would have the same impact on any level character.

it's easier for a player to see a 5 point stat drain and recognize that it's significant, no matter what level they are on, instead of having to think, oh 5 is a really big deal because I'm low level, or 5 is no big deal at all because I'm high level.

**Comment by Sandman25DCSS** [comment]
So main reason for your changes is related to draining? And you really want to make player lose 50% damage when going from Str 40 to Str 35? Does it even make any difference since you will be one-shoting everything even with Str 35? And if not, how average characters with Str 15 are supposed to survive?
I don't like the idea, it sounds like you want all characters be extremely specialized so a fighter will have to put all bonus points into Str and wear items that give Str, casters put all points into Int and wear corresponding items and I suppose stabber into Dex. No hybridization, no adaptation to found loot, no hard choice between different items. Hack and slash style I suppose, your character is determined at turn 0 :(

**Comment by jeremygurr** [comment]
So on the one hand you have a linear scale, when penalizes players that want to be very focussed on strength for example, by giving a small reward for additional points in strength, and a bigger reward for additional points in dex or int. So it does add some motivation to spread out. 

The geometric scale does the opposite. It adds some motivation to keep going along a specialized path because the diminishing return for adding to str, for example, has been removed. 

Either choice takes weight from one playstyle and puts it on another, which is a negative in both cases. However, the geometric scale doesn't penalize a hybrid style like the linear scale penalizes a specialized style. With a linear scale, adding to stats you are low in gives a higher bonus, and adding to stats you are high in gives a lower bonus. With a geometrics scale, adding to _either_ gives the **same bonus**. If anything I think it allows for different playstyles better than a linear scale, because it doesn't penalize the specialist. Adding 5 points to int increases your effectiveness just as much as adding 5 points to str, independent of what either value is at. 

You are mixing up numbers here. Since the attribute numbers will be adjusted to be the same as vanilla crawl, (str 40 would translate to str 21 for example), you won't be one-shotting anything any more than in vanilla crawl. This is not a damage change. It is only a scale change. The difference will be that late game attribute buffs and nerfs will continue to hold the same value, and not get stale. Yes that comes at the price of removing the low level boosts that a stat would get with a linear scale. 

I definitely agree though that I don't want hybrid playstyles so nerfed that people can't pull them off or wouldn't want to. I'm not sure that would really happen here, but if it did, then I would scrap the idea. There would definitely cause a nerf for hybrids, but I think the case could be made that they are a little too strong now. Against a monster that a specialist is strong against, they would be able to wipe them out more easily than before. But the opposite is also true. For a specialist to go against a monster they are weak against, they will be even weaker than before. What good does it do to be able to annhilate a powerful monster with ridiculous fire power, only to die to a red imp that is fire immune, because the player was so weak in other areas? A hybrid will not have this problem, which will, and should, partially compensate for the inherent nerf here. So there will remain a strong motivation for players to hybridize, just like before. Those who are lured into the temptation to specialize too much, because of the higher rewards there, may not find the time to enjoy the reward, as they are annhilated by the creature that is immune to whatever their specialty is.

**Comment by Sandman25DCSS** [comment]
Ok, let's see how it works.
