### ISSUE TITLE
Summoner background is unplayable

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#26]
I started one of the easiest summoners - Tengu and still was almost unable to use mammals or imps because they disappeared before being able to attack.
Probably it can make sense to limit mana draining ability to some higher level summons only.

**Comment by Sandman25DCSS** [comment]
For example, I am unable to kill a single Ogre on D:5, that was impossible with 13 MP and Ice Beasts etc. in standard version.

**Comment by Sandman25DCSS** [comment]
MP decrease in some unusual way, I summoned a single Canine and then passed turns, my MP changed like this: 11-11-9-6-1. Is it progressive decrease by 1-3-5?

**Comment by jeremygurr** [comment]
Ok try it now. 

I gave summoners 2 extra points of magic at the beginning and a +1 dagger. I also tweaked the summoning cost a little to give early summoners a fighting chance. 

It's still difficult, but should be doable. I'd recommend focussing on maximizing spellpower at the beginning. Spellpower determines how quickly your mana is drained by a summoning spell. 

Keep in mind that tengu start with a basic flight ability which gives them a speed boost that can help them escape many of the earlier monsters when they get in over their head, which is frequent because they are so squishy at the beginning. Flying also gives a decent evasion boost, especially as they advance in levels. 

The way the magic cost of a summons works is very chaotic. You may be able to hold 3 canines for 10 turns one time, and only 1 turn another time. But the average can be extended by increasing spell power and magic capacity.

**Comment by Sandman25DCSS** [comment]
Thank you, I will resume playing the game.
This is what I meant as Tengu being one of the best summoners, it has +2 summoning aptitude and I still was able to escape many times due to speed boost from flight and even win some fights due to lucky finding of venom sword and training fighting/dodging really early (because I realized on D:1 that pure summoner build is impossible).

**Comment by Sandman25DCSS** [comment]
Also is it possible to have 0% failure for "release summoned creatures" initially?

**Comment by jeremygurr** [comment]
It should be that way already. Tell me if it isn't in that latest build. 

-- Jeremy

**Comment by jeremygurr** [comment]
Yeah summoners pretty much have to be hybrid fighters. But the extra help of even a single rat or bat early on, with an ok melee fighter helps quite a lot.

**Comment by Sandman25DCSS** [comment]
I was a bit surprised because you mentioned in the tavern thread that your intent was to provide more options to summoners (for example, they can use several hydrae or more than 3 Ice Beasts) but it looks like the result is quite the opposite, summoners are locked into being hybrids who use just a single summon most of the time. Traditionaly pure summoners like MuSu of Sif Muna summon the best they can get for a fight and then channel mana every turn to have MP to replace fallen/expired summons, I think it is no longer an option unless new summons are changed to stay as long as your MP is positive. And even then replacing fallen summons is problematic due to very low mana.

**Comment by jeremygurr** [comment]
Well I would think that you only have to fight along with the summons in the early game. It doesn't take too long before you can have a pack of canine familiar summons following you around. At higher power levels I can summon a pack of hydras to take out most mid game monsters with ease. That's the way I had to do it with the normal game even before these changes. I found I always had to pick up the first weapon I found and join the battle, because my summons couldn't take care of it all themselves for a long time. 

I'll start up another summoner and play it further into the game to see how that works in practice.

**Comment by Sandman25DCSS** [comment]
Picking up a weapon is optimal, yes. Yet it was possible to rely on summons in all fights, even early game. Though probably we have different meaning for "early game".
Here is my MuSu of Sif Muna who ignored Fighting/dodging/weapon skills for a long time. 
http://crawl.berotato.org/crawl/morgue//Sandman25/morgue-Sandman25-20150317-021625.txt
7828 | D:8      | You fall through a shaft for 3 floors!
  7828 | D:11     | Noticed a hill giant
  7840 | D:11     | Killed a hill giant
  7840 | D:11     | Reached skill level 8 in Summonings
  7985 | D:11     | Noticed a hill giant
  7993 | D:11     | Killed a hill giant
  7993 | D:11     | Reached XP level 9. HP: 57/57 MP: 2/17
  8005 | D:11     | Noticed a cyclops
  8023 | D:11     | Killed a cyclops
  8023 | D:11     | Reached skill level 5 in Ice Magic
...
 9301 | D:9      | Reached skill level 1 in Fighting
...
12107 | Lair:1   | Reached skill level 5 in Dodging
...
15734 | Lair:4   | Killed a death yak
 15756 | Lair:5   | Noticed a death yak
 15763 | Lair:5   | Killed a death yak
 15983 | Lair:4   | Killed a death yak
15983 | Lair:4   | Reached skill level 1 in Long Blades
...
 29081 | Swamp:1  | Reached skill level 5 in Long Blades

**Comment by jeremygurr** [comment]
Ok I adjusted the summoning mechanism a fair bit. It will be even harder to maintain high level summons, but easier for lower level summons. Try this out and tell me what you think. This is a save game breaking release, since my difficulty level feature went out with it, so you'll have to start fresh. But it should be noticably easier to be a summoner.

**Comment by Sandman25DCSS** [comment]
Thank you! I will start another TeSu when I have a chance.

**Comment by Sandman25DCSS** [comment]
Thanks for the difficulty setting also, I will test it as well since normal TeSu is probably too easy for me.

**Comment by jeremygurr** [comment]
The difficulty setting is just an initial stab at it of course. It will take a fair bit of tweaking to get it balanced right. Easy is meant for newcomers to have a chance of at least getting to some of the cooler aspects of the game before giving up on it. Hard is meant for those who can beat the game consistently on Normal, and need more of a challenge. I'd like to boil these down to a few key changes for each level. I don't just want a trivial change, like all monsters have 20% more health. I'd like more interesting differences, but not game destroying, like increased chances of out of depth monsters, or more bad mutations thrown into the mix, that would normally not be possible for a normal mode character, but would still be playable with a skilled enough player. I don't want to turn it into a pure luck game, so choosing exactly how to make it harder is tricky. I'm sure you'll be able to help a lot with that. I can understand the easy side much better than the hard side, and should be able to balance that easily enough. 

For example, I don't just want to reduce the spawn rate of healing potions. If I take away healing potions, I'd like to replace it with something that is maybe more difficult to use, but would make the game still possible to beat by a skilled player. 

Maybe a few new monsters could be added in each branch that only exist for hard mode. Or maybe we could chop a floor or two off of the top of each branch, reducing the number of easier monsters and levels, forcing the player to get to more difficult challenges without giving them the time to build up their character as much.

**Comment by Sandman25DCSS** [comment]
I am not sure if you checked my mod but it has 2 options to customize difficulty:
player XP multiplier and monster HP multiplier, and they are independent of each other.
You mentioned many things that are already possible, for example, I mutated myself as much as I could to make one game harder, spending more time on levels to trigger out of depth monsters is already possible too, no wands/potions/scrolls conduct is possible too. New monsters could be fun but I am not sure they worth the extra work since eventually it will result in one of standard "harder to kill so you need consumables" or "too dangerous so escape and never return" solutions.

**Comment by Sandman25DCSS** [comment]
Unless of course the new monsters change a lot, something like Vault Wardens or Silent Specters.

**Comment by jeremygurr** [comment]
Oops I left the summon cost calculation debugging in there. It will be removed for the next version.
