### ISSUE TITLE
FR: Trog should give stamina when prolonging berserk

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#269]
When Trog increases berserk duration after a kill, stamina is not increased so eventually my berserk is stopped by stamina. It makes Berserker not as fun as before since I can no longer berserk vs large groups. I suggest to increase current stamina points at the same time.

**Comment by jeremygurr** [comment]
fixed. when it gets deployed tell me if I got the balance right. Currently I'm giving 4 stamina points per turn of duration increase.

**Comment by jeremygurr** [comment]
Ok it's deployed

**Comment by yrmvgh** [comment]
Sandman, since you're a pretty high skilled player, can you try to break a character build that I've been messing with? I keep getting overconfident and dying.

It's a "octospider of trog / demonblade of trog" - or whatever

Whatcha do is, you get a decent amount of Transmutation and then in Careful mode you cast a form and you just... never turn it off. And then to be silly, you worship trog (which means you can't upgrade to better forms at higher skill, but you get the best god in the game...)

My best guess is that you want to be Oc or Fe and use a real form (for the extra jewelry slots) or pick something durable and cast Blade Hands. I like Ds because PBP/PBD are great, if you get em, plus you probably get an AC bonus, though also a lowish armor apt...

Things to watch out for are anything that can remove your form post-Trog. Potions of lig, enemies that polymorph, etc. Fortunately trog gives a meaty MR boost to deal with poly.

**Comment by Sandman25DCSS** [comment]
Sorry, I am not clear what I am supposed to do. I don't think using one form during the whole game will make game easier while switching to another form is too dangerous because of Trog's wrath.

**Comment by Sandman25DCSS** [comment]
Do you want me to point you that Statue Form is slow or what? :)

**Comment by Sandman25DCSS** [comment]
Blade Hands melds shield, Ice Form gives rF- and basically if you can cast Hydra/Dragon Form it means you are not in early game and probably don't need to switch to Trog.

**Comment by Sandman25DCSS** [comment]
I think 4 SP is too few, I still run out of SP very fast.

**Comment by yrmvgh** [comment]
Same here. It's also mildly annoying to be sitting on 70 stamina and told I'm too tired to zerk - though at least we have Mini-Zerk in the form of Power mode, in that situation.

**Comment by yrmvgh** [comment]
Sandman - the way I look at it is this. Blade Hands is better than an executioner's axe. So in theory, you just need a very small amout of casting skill to brute force casting Blade hands at like 50% fail rate, and thenceforth play just like a mace/sword player would play. But using UC instead, and having good armor options unlike a troll!

**Comment by Sandman25DCSS** [comment]
yrmvgh, IMHO current transmutations are broken, I treat them as bug and refuse to use. So do whatever you enjoy :)
