### ISSUE TITLE
Vampiric weapon is unusable with berserk

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#272]
Previously it was a very good combination, now berserk is over too fast and you are slowed with non-branded weapon.

**Comment by Sandman25DCSS** [comment]
Also I found http://crawl.chaosforge.org/Leech in my DsBe game 

> Vampiric brand effect, activated on every hit

Stamina mechanic makes it not very different from other vampiric weapons which activate on 50% hits.

**Comment by jeremygurr** [comment]
See if the extended berserk time is enough to solve this.

**Comment by Sandman25DCSS** [comment]
I see that switching to vampiric weapon sets stamina to zero now. This makes vampiric weapon really bad IMHO, previously I could use electro weapon while at high HP and then would switch to vampiric for healing, now I just use electro all the time.

**Comment by jeremygurr** [comment]
Hmm... that's not right. I believe vampiric should just consume hunger like before when health is below max, translating to sp costs over time, which may eventually wear out a player, but they should get a fair amount out of it first. Oh I see what's happening. Vanilla crawl immediately takes a chunk of hunger away on equip. I need to take that out since it doesn't make sense here.

**Comment by jeremygurr** [comment]
fixed.
