### ISSUE TITLE
5 by 5 (the Future.md feedback thread)

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#276]
check out [Future.md](https://github.com/jeremygurr/dcssca/blob/master/FUTURE.md) and leave some feedback! I'll start.
### 5 things from Future.md that I'm unequivocably a fan of
- Inversion scrolls, and most of the other new scrolls
- UI/fixes like autpickup, macroing, doors, one-button interact, etc
- Altar destruction - we can really be zealots for our chosen god!
- Improved acquirement - yeah screw this scroll imo. :laughing: 
- Elemental distinction - and maybe we can bundle "shrink Conj school" with this? Like, if something does just plain ol' damage, it can be conj or conj/earth, but if it does something very Earthy, like removing walls, maybe it can be just Earth so the non-Conj schools are less tiny?
### 5 quibbles, nitpicks, or tweaks
- scroll of karma sounds cheesy, because monsters never hold back. kinda like how some monsters stupidly keep trying to flame a djinn player. maybe if it was a 1 turn effect it wouldn't make monsters look too foolish.
- "inversion" effects should always have some way in which you can use them to your benefit. invert + heal = dead isn't interesting, because 1 it'll almost never happen, who inverts an unknown item, 2 don't make a player feel bad for using 2 consumables. invert + heal should be dangerous (like maybe AOE flayed ghost effect, torment, etc, hitting self & enemies), but not suicidal.
- scroll of time is REALLY good with a lightning spire or oklob. no invert needed.
- As stated on IRC, I'm against bad consumable effects in general, because they don't happen very much to careful, boring players who run from danger and Lure every fight. And it's a double whammy - if you quaff-ID in hopes of something defensive/healing, and you get Might, that already might spell your doom. Consumables that are extra-extra bad in a blind quaff situation aren't needed.
### 2 things that I just Do Not Want
- Spellcasting speed based on a particular skill that some spellcasters have a good apt in, others don't. Base it on spellpower, or total mana pool size, or Int... not spellcasting!
- Removing jobs. A clear start role is a good guidance system for newbies, and the start gear is semi synergistic - more synergistic than finding a short blade manual, a greatsword, and a robe on D1 when you're playing a minotaur. Adapting to drops is an important DCSS skill even when you're playing a clear role - let players develop that skill on their own, don't try to force it by throwing them in the dungeon naked and afraid.

**Comment by jeremygurr** [comment]
excellent. It's this kind of discussion I'm hoping to stimulate. Many of my future ideas aren't even half baked yet, but they are presented anyway so that we can see clearly how good or bad they are. 

I'm not even sure that the concept of spell speed will improve the game yet, but if it is, then it would probably be best to base it on intelligence instead of spellpower.

Yeah that is the intention that no items are "pure" bad, there is always some kind of use. I love that the random uselessness scroll actually has some use. And it was so fun when I finally learned that immolation could actually be a powerful tool in a skilled player's hands instead of just a spectacular suicide. And lignification has become one of my favorite life saving tools, when originally it meant my death. All are brilliant examples of good gamecrafting IMO. Many of the items I'm considering adding are an attempt to make more of that. 

And I also don't want any one-shot unavoidable deaths from consuming unidentified items. However, incidental death may occur as for example a poorly timed lignification potion could cause. I don't feel a need for a potion of poison, and I'm not even sure about the potion of degeneration. But there is plenty of room for others that with skill could be turned to the player's advantage. Like the inverted form of the potion of poison vulnerability giving temporary poison resistance, or even immunity with an amp scroll. 

Yeah inversion scrolls are going to be a ton of fun. But the amp scrolls I think have a lot of potential too, although they are a lot more difficult to get right I think. The point of the amp scroll is to add room for another layer of crawl expertise, allowing even more cunning solutions to difficult battles. I think a great deal of the fun in crawl comes from getting in over your head in a battle and then pausing. You are pretty sure you are going to die, but you've worked so hard on this character.... what to do.... you look through every item in your inventory, no obvious solutions. But with your vast experience with crawl a crazy idea comes to mind. You apply a couple of items in a way you never thought of before, and amazingly it works. You overcome the situation and your character is still alive. 

Because of this, it isn't even obvious how it can be useful in many situations, but it needs to be flexible enough to open up many new doors to allow for that dungeon crawler creativity to save a player from certain doom from time to time. Let me give an example. 

So you are carrying around this amp scroll. There are so many things you could do with it that would benefit your game, but you are about to face a particularly difficult challenge, and want to keep your options open, so you save it a little longer. You get into an epic battle where your favorite weapon gets a heavy curse on it, nullifying it's enchantments. Your character is okay at the moment but you don't want to burn your last remaining blink scroll to get out of here, and teleport puts you at too much risk in this situation. But you really need that weapon to dispatch the current enemies safely. So you decide it's worth using your amp scroll for. You read the amp scroll, then a remove curse scroll, and it's just enough to take the heavy curse down to a light one. You still can't swap out your weapon, but you don't need to anyway. But at least the enchantments are back and you can go to town on the enemy, after burning only 2 turns. Actually, might even be better to make the amp scroll take no turns, as part of it's power. So just the one turn to read the remove curse scroll and you're back in action. 

One more example. You again have been saving an amp scroll, hoping to use it to amplify a branding scroll on an executioner's axe you found to create a sweet artifact weapon. But before you have a chance to do that a particularly challenging unique shows up. Unfortunately for you it is after you've already picked up 14 of the runes, and so a heavy load of rune curses are being applied here, making this unique that normally wouldn't be too big of a deal, an epic challenge. You might just be able to take care of this monster if they didn't also happen to have the abillity to create 3 copies of themselves, equally as deadly as the first. So you get a crazy idea. You aren't even sure it will work but you figure it's worth a shot. You read an amp scroll followed by an inversion scroll. Then you read the replication scroll. Normally the replication scroll would create a copy of something, and an amplified version would create many copies. But an amplified _inverted_ form would take multiple copies of something and collapse it into one. So you read that and target your enemy. Now there is one, which you have enough resources to dispatch soundly. 

As far as the job removal, you are probably right. I think it is a fun idea but maybe it is better implemented as a specific wanderer enhancement or alternative game mode. Probably not best for newbies.

**Comment by eyestalker** [comment]
I don't like the idea of making Xom more predictable. I'd like an idea of making him even less predictable, though.
