### ISSUE TITLE
wand charging mechanic, op for many different wands, under powered for single wand use

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#284]
The main issue I'm trying to solve here is that we don't want a stack of recharge scrolls and a healing wand to basically provide unlimited healing. And we want to do it in a way that isn't too complex or spoilery. 

Without the wand stacking I think the existing mechanic worked reasonably well, but with the wand stacking a single recharge scroll can add 50 charges to a stack of wands.

If we just cap the amount of recharging a single scroll could do, we couldn't cut the max charges down each time, because that would penalize the player because of the wand stacking mechanic. Wand stacking should not ever be bad thing for the player, because it is forced and would lead to tedious behaviors otherwise when it came to picking up new wands. 

Possible solutions:

1> revert wand stacking. I don't like this because it causes a lot of inventory clutter. There's got to be a better solution.

2> fixed recharge amount per scroll. This would have to be different for different wand types, since adding 3 charges to a healing wand may be worth it, but adding 3 charges to a confusion wand would never happen, since it's value isn't good enough to offset the value of using it on a healing wand. So it results in reducing player choice. And if it is different for each wand, that adds extra complexity. Not a huge deal, but still something I like to avoid when possible. Another negative of this approach is that it would have to not reduce the charge cap on each recharge, which increases the chances of wand abuse.

3>  keep it like it is and tweak wand generation to keep things from getting too extreme. 

4> spawn more wands, but they are never rechargeable. They don't have a cap at all, just use up their charges like a deck of cards. Recharge scrolls would be removed. This decreases the chance that you won't find any at all, but greatly limits abuse scenarios. A few special cases would need to be solved: pakellas wand charging, DD charging ability. This changes the nature of wands and makes them basically like potions that can be used more than once (a bad thing). For pak, the recharge ability could go away, and instead the rate of wand gifts increased. For DD, they lose their recharge ability too, but they have a passive ability that makes any wand usage have a % chance that it doesn't lose a charge. So if they find a wand with 3 charges, say they have a 66% chance the charge isn't lost on use, then they would on average get 9 charges out of it. The biggest negative I see here is loss of the distinction of wands that set them apart from potions, which is that they are rechargeable, and potions aren't. So finding 4 charges in a wand of healing is like finding 4 healing potions. I guess there is one more difference. Wand power is based on evocations, whereas potions are independent of player attributes. 

5> vanilla crawl style wands caps and recharging. Wand stacking becomes a problem here and I think there is too much room for abuse, thus leading vanilla crawl devs to nerf it in various ways, which also make it lame/weaker for those who aren't abusing it. 

So far I'm leaning towards 4. Problems? Better ideas?

**Comment by Sandman25DCSS** [comment]
6> Scroll of recharging in vanilla crawl already gives different number of charges for different wands. http://crawl.chaosforge.org/Scroll_of_recharging. We can combine it with wand stacking and max zap reduction. Something like this: charges added are taken from vanilla crawl, wand stacking is taken from CA fork, stacked wand has its max charges reduced by "max normal charges divided by three".
Examples:
a) recharging 0/9 wand of healing gives 2-7 charges and reduced wand maximum to 6.
b) recharging 0/6 wand of healing gives 2-6 charges and reduced wand maximum to 3.
c) recharging 0/3 wand of healing gives 2-3 charges and reduced wand maximum to 0.
d) recharging 0/18 wand of healing gives 2-7 charges and reduced wand maximum to 15
e) recharging 0/15 wand of healing gives 2-7 charges and reduced wand maximum to 12
f) recharging 0/12 wand of healing gives 2-7 charges and reduced wand maximum to 9
then see  a-c  since we have 9 max zaps again)
For another wand type:
a) recharging 0/15 wand of ligthning gives 2-13 charges and reduced wand maximum to 10.
b) recharging 0/10 wand of ligthning gives 2-10 charges and reduced wand maximum to 5.
c) recharging 0/5 wand of ligthning gives 2-5 charges and reduced wand maximum to 0.
d) recharging 0/30 wand of ligthning gives 2-13 charges and reduced wand maximum to 25.
e) recharging 0/25 wand of ligthning gives 2-13 charges and reduced wand maximum to 20.
f) recharging 0/20 wand of ligthning gives 2-13 charges and reduced wand maximum to 15.

**Comment by Sandman25DCSS** [comment]
Also my suggestion allows to keep using vanilla crawl chance to find recharging scroll

**Comment by yrmvgh** [comment]
If heal amount was even lower at 0 skill but strongly tied to evo skill, recharging for "infinite healing" wouldn't be as big of a deal. Few races are good at it, and it's usually an "extra skill" after a character's main combat or casting skill.

That might make things tricky for low level DD but they could have a racial +2d4 to wand heals or something.

**Comment by yrmvgh** [comment]
Or just make a special item for DDs with its own rules, and break off healing wands for general use and balance them without having to worry about DD

**Comment by Sandman25DCSS** [comment]
Yes, DD is a problem. We are basically trying to fix "a single wand should not be recharged indefinitely" but that does not work with DD. Maybe recharging wand of heal wounds should not decrease max charges for DD.

**Comment by jeremygurr** [comment]
It's easy enough to make DD recharging not reduce charges, but part of the point of reducing charges is to keep DD from becoming too easy. Am I mistaken in the severity of the issue for deep dwarves and heal wands / racial recharging / pakellas recharging potential?

I already require DD to pay 3 php instead of 1 for top tier wands, which helps a little by itself.

**Comment by yrmvgh** [comment]
DD's **need** their heal wands. Due to the repeated halving of wand charges, if I hadn't lucked into finding a vampiric randart I would be spendind all of my trog piety just on keeping my HP going. I don't think restricting DDs to only picking gods that heal is a good way to balance them.

**Comment by yrmvgh** [comment]
I mean everyone else just rests to heal. Meanwhile DDs give up MP permanently just to get back hp that everyone else takes for granted. The race is pretty powerful, but I'd look for other ways to nerf it than making healing even more difficult than it is.

**Comment by Sandman25DCSS** [comment]
I am not sure DD is really relevant here. It is still broken with Makhleb no matter what we do with wand of healing. Here is my old game, I was very inexperienced player at that time. http://dobrazupa.org/morgue/Sandman25/morgue-Sandman25-20131016-224836.txt
As you can see I used Device Recharging 4 times in 15 rune game (first time at XL 16), and just 92 uses of wand (not sure how many of them were heal wounds of course), 45 uses of wand before XL 25 which is basically 3 rune game.

**Comment by G0rg0** [comment]
What about instead of stacking, the wands "merge" charges into a single wand. You have a dig wand with 10 charges, you pick one up that has 5 charges and those are added to the one you had so now you have 15 charges. The original charge capacity in regard to recharge scrolls stays the same even if the wand becomes "overcharged". 

In this example say you've found 5 dig wands (unlikely) and you now have 40/35 charges on your wand. If you use a recharge scroll on this wand right now, you get nothing, but if you use up 10 charges first, you could get back up to the max of 35 from the scroll.

**Comment by jeremygurr** [comment]
Ok I think I have a good compromise. 

On recharge, wands gain their half of their normal full capacity in new charges. So a healing wand gets half of 9 charges, which is 5 in this case (less if there isn't enough capacity of course), no matter how big the stack is. Then the wand loses 1/3 of that from it's charge cap. Recharge scrolls spawn like in vanilla. 

So example rechargings of a heal wounds wand:
4/18
9/16
14/14
use it a bunch... 0/14
5/12
10/10
use... 0/10
5/8
use... 0/8
5/6
use... 0/6
5/4
use... 0/4
4/2
use... 0/2
2/2
etc.

so basically gaining 41 charges out of 2 healing wands and 9 recharge scrolls. Seems like a bit much to me, and it feels like I should make it lose 1/2 of the charges it gains from the cap each time. Which would be:
0/18
5/15
10/12
use... 0/12
5/9
use... 0/9
5/6
use... 0/6
5/3
use... 0/3
3/2
use... 0/2
2/2

which would give 30 charges instead of 41. That feels better to me. I think I will do this instead.

I applied it back to pakellas too, because I think pakellas is a bit too strong because of how things work here. I think if this makes pakellas too weak, we can balance by increasing wand gifts to original vanilla craft gifting rate. Which I think I will go ahead and do...

**Comment by G0rg0** [comment]
Maybe I am an outlier, but I don't think I have ever seen more than 5-6 recharge scrolls in any one game (even extended) _ever_. Are people really finding 10+ recharge scrolls? 

I'll be honest, these changes are pretty complicated, I don't know that a newbie would be able to make heads or tails of what was happening with their charges. Hell, _I_ don't know that I 100% follow it, and I've been here the whole time :P

**Comment by Sandman25DCSS** [comment]
Number of those scrolls varies a lot indeed but I don't remember any games where I found more than 6 either.

**Comment by G0rg0** [comment]
I agree, it does vary a lot. There are plenty of games where I never find a recharge at all or just 1-2 after getting all the way through vault.

In fact, I am going to argue for my earlier proposal again:

Merging/stacking charges is a very simple mechanic to understand and even better, it means that the total number of charges any player would get on any wand would be identical to vanilla, minus the inventory hassle. 

There wouldn't be this problem of one scroll recharging x number of wands, there would only be one wand, with a max number of charges. Even though you can potentially get over that max by getting lucky and finding 10 heal wands, as far as the scrolls are concerned, that max is as much as you can get.

No chance for it to be overpowered or underpowered, it would be up the the RNG and the base rate of wand and scroll spawning.

**Comment by yrmvgh** [comment]
> Number of those scrolls varies a lot

I kinda miss being able to read the biggest scrollstack and have it usually be Ident. I no longer have any idea what it is, though it seems to trend towards being tele? maybe that's intended, because that's a spoilery sort of knowledge, but I educated guesses are a nice handhold for when you're deciding whether to use-ID

**Comment by jeremygurr** [comment]
yeah I do the same thing. Yeah it's a bit spoilery, but at the same time kind of cool when a new player realizes that they can push the odds in their favor a little bit. I don't know of any better way to do it than what vanilla crawl already does, which is to occasionally generate 3 of even very rare things. 

Actually... if we really wanted to make it less spoilery there, we could just put _all_ unidentified scrolls together in one inventory slot, and then them break out into their own slot scrolls as they are identified. But I'm not sure it's worth the effort.

**Comment by jeremygurr** [comment]
I wasn't trying to say people would commonly come across 9 scrolls in a game, just trying to illustrate the mechanic I was proposing.

**Comment by jeremygurr** [comment]
problems resolved.
