### ISSUE TITLE
Scroll of identify identified wrong slot

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#29]
I read a scroll of identify, picked an unknwon potion in 'w' slot but it identified an unknown wand in 'w' slot instead.

**Comment by jeremygurr** [comment]
That is because it was in a different letter in the identify list, because w was already used by the wand. The way I had it before, when you read an identify scroll, it would ask whether you wanted to identify an inventory item or consumable, and then it asked what you wanted to identify. With that method, the letters always matched what it says in the inventory. 

But I found repeated usages of scroll of identification caused me to be annoyed with that extra step of having to specify consumable or not each time, which was sometimes confusing because I wouldn't always know. I just wanted to see all the unidentified items at once, and then decide what I wanted to id. 

So I implemented it with a unified list of unidentified items. The problem of course is that sometimes an item in the main inventory (the wand in this example) uses the same slot letter as an unidentified item in the consumables list (your potion), in which case this dialog reassigns it to an unused letter. So in your consumable inventory, you see the potion in slot "w", but when identifying, because w was already used, it had to use a different letter for your potion. It still works, you just have to find the item in the id list and make sure you are getting the right letter, and not assume it will always be the same as the inventory list. 

This odd behavior only exists for identification. All other inventory behaviors have sufficient distinction that you can always use the real inventory letter, so it doesn't come up.

But clearly this can be occasionally awkward, especially for experienced players used to it behaving differently. 

So it's a little awkward, but I still find this approach much better than my previous where I had to specify c or i each time.

**Comment by Sandman25DCSS** [comment]
Thank you for the explanation! I will keep attention next time.
