### ISSUE TITLE
Summoning is OP and annoying

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#296]
I tried DESu at nightmare. Multiple Imps were fine which was kind of expected because vanilla crawl has 3 as their cap. But 4 Wolves on D4 is completely broken, all those Ogres, orc packs without Orc Priest, Pikel with slaves, Blork the Orc die too easy. Only Orc Priest was a threat and that's because I have 28 HP. D2 was easy too, Su starts with more MP in CA fork so I was able to kill Worker Ant without allowing it to get adjacent to me. But the worst thing was that if I summoned 4 Wolves and had 0 MP, they would disappear at about the same time leaving me still at 0 MP so optimal strategy becomes: go upstairs, unsummon everything, wait for MP to regen, go downstairs and continue exploring. Power mode makes it even worse: if I am out of MP and suspect that summons will expire soon in a fight, I just activate power mode and retreat upstairs to reset the fight.

**Comment by Sandman25DCSS** [comment]
4 Wolves killed extremely dangerous player ghost (Moon Troll EE) on D5, that's just too much IMHO.

**Comment by jeremygurr** [comment]
Ok what if you got magic back after your summons were killed, so that you can resummon them immediately instead of resetting the fight. It would still cost some turns of course, potentially allowing monsters to pound on you a few times. 

That would help with the annoyance issue. For the balance issue, we can make wolves cost more or weaker. I'd prefer cost more. 

How about ice beasts? Since in vanilla you could summon 3 at a time also, would they need significant rebalancing?

**Comment by Sandman25DCSS** [comment]
Yes, some magic back can help indeed, it would be closer to natural MP regeneration which we have in vanilla crawl.
I am on D6 so I don't have an opinion about Ice Beasts yet, 3 of them were enough to kill an Ice Beast on D5 of course.

**Comment by jeremygurr** [comment]
I still feel like it would help if successive summons cost more. What if each summon cost it's base amount + the number of summons you already have. 

Summon mammal would cost: 1, 1+1, 1+2, 1+3. So to make 4 would cost a total of 10. 

2 mammals and a canine (doesn't matter which order they are summoned): 1, 1+1, 3+2 = 8 total.

4 canines: 3, 3+1, 3+2, 3+3 = 18 instead of 12. Not dramatically more, but still makes it a bit harder to manage a large horde, which is both consistent with the flavor and I think a necessary limiter.

**Comment by Sandman25DCSS** [comment]
I am not sure about it, it encourages using highest summons, you get less penalty for 2 strong summons than for 3 weaker ones.

**Comment by Sandman25DCSS** [comment]
I thought you were going to deploy a version with +30% cost for summons of the same kind? Or did you abandon the idea?

**Comment by jeremygurr** [comment]
Ok I guess I can do per summon type. Just a bit more complicated coding wise. But if it makes a significant difference then it's worth it.

**Comment by jeremygurr** [comment]
I took Canine familiar to a level 5 spell and made every summon of the same kind cost 50% more than the last. So this naturally makes optimal play require the player to summon a few different kinds of monsters. 

It feels like it might be better to make the 50% compounding cost to be based on the total number of summons to make it not too easy to spam monsters to death. Then the player is free to select whatever horde composition he wants. If a member of the horde is much more powerful than other members, it should naturally cost more. 

And summons across the board should probably cost 2-3x as much. But we'll try it like it is for now to see if it's fine.

**Comment by Sandman25DCSS** [comment]
Early dungeon is the hardest part of the game and now we have:
1) Canine Familiar is level 5 instead of 3
2) 3 Ice Beasts cost 13 MP (3+4+6, right?) instead of 9
3) Lightning Spire is level 5 instead of 4
4) Guardian Golem is almost useless (it decreases max MP too, right?)
and that's just to have 3 Hydra in Shoals or something :(

**Comment by jeremygurr** [comment]
But summoners get an mp boost over standard crawl, which makes early game easier. If that isn't enough we can do more. I'm a fairly weak player and at least on easy mode, I don't find summoners very hard at this point. If anything, they are still a bit OP. 

Try out a summoners game and see if it really is too hard. On hard mode it should feel harder of course than vanilla, but at least on normal mode it shouldn't be significantly harder. 

I'll try a normal mode summoner also soon. It's easy enough to tweak levels and MP costs. The more significant part here is what capless summons do to the game itself, which so far, IMO it gives summoners a lot more freedom. No longer is the optimal path exactly one thing (1 canine, 3 ice beasts, 1 guardian, 1 lightning) to be executed every time before a tough battle. 

I think I will take off the auto-releasing of summons when resting, so that players don't have to resummon their horde before each battle.

**Comment by Sandman25DCSS** [comment]
I meant that it's very hard to get Canine Familiar/Lightning castable and we can't spam Ice Beasts (not exactly easy to get online either). Am I supposed to spam Imps and Mammals all the way before getting dual school level 4 spell online? That's about D1-D7 with level 2 spell I guess, no other background does it. If it's possible, then those spells are broken. If it's impossible, then we need some level 3 spell.

If you are testing something, do it with Human IMHO (here I assume it still has 0 summoning aptitude and -1 spellcasting). I'll try HuSu at middle level today.

**Comment by jeremygurr** [comment]
I'm doing a gargoyle summoner now with -1 summoning and -1 spellcasting. I'm training polearms and summoning. I was able to bring 2 ice forms online at the end of XL 4 in challenge difficulty mode. So far I haven't come across a serious challenge yet. I have 2 ice forms and 3 small mammals, and am easily chewing through anything the game throws at me, and this isn't anything to do with removing the vanilla summoning caps, since both are within those caps. Yeah I guess gargoyles are pretty tough in general, but I'm just looking at how long it takes to get these spells online, and it's really not that bad. 

Now that I'm at XL 6 I can sustain 3 ice beasts and 4 small mammals, and it's even more powerful. I suspect things will get a lot more challenging when I get to lair, but so far I'm a little worried it's OP. However, that would be just as OP in vanilla crawl since I'm mostly within the summon caps. Not only that, but in vanilla I would also have a canine familiar in my pack at this point in the game.

**Comment by jeremygurr** [comment]
Summoning is a bit buggy still. I will get these bugs ironed out and a fix deployed in the next couple of days.

**Comment by jeremygurr** [comment]
fixed. Summoning is quite nice now.
