### ISSUE TITLE
Inv2 insight based on stack size

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#307]
The existing system prioritizes whatever happens to fall into your lowest letter slots, OR (if you're a spoilered player), whatever you move to your lowest letter slots.

A more general-use scenario would be for Insight to prefer to ID whatever you possess the smallest quantity of. This is uuuusualy how people identify their [scrolls](http://crawl.chaosforge.org/Identification#Scrolls) and [potions](http://crawl.chaosforge.org/Identification#Potions) already, because you can afford to waste 1 consumable from a large stack by use-IDing it, but you don't want to accidentally fire off your one Brand Weapon scroll before you're ready for it.

Look at all potions scrolls, find the smallest stack size(s), then if necessary randomly break ties. Or break ties based on inventory letter, since you've already got code for letter-based prioritization.

Sometimes I manually encourage Insight to do this by moving things around, but usually I don't bother. I think this change would eliminate tedium for the knowledgable and make the system more friendly to the unspoiled.

**Comment by jeremygurr** [comment]
I originally had it choose randomly what is identified, but found it much nicer to be able to choose what it focusses on first. Most of the time I only care about identifying one or two items above the rest. This change would take away that option. Thematically it makes sense that a player could choose what items they spend more time "studying" and thus can identify sooner. 

It is true that I often want low freq potions identified first, but not always. Sometimes I deliberately want my highest stack or two of potions identified first, because I need cure early on in the game, and it's usually one of those. Because it's not always a no-brainer to identify the smaller stacks first, I think it's best to leave the player some amount of control over what they "study" first. 

This theoretically would be well documented, and so would not be spoilery, if I ever actually updated the main game docs. Any volunteers? I'd rather focus on getting these changes ironed out and leave documentation changes to those who don't want to or can't do the coding changes. But I will eventually get to it if no one else does.

**Comment by yrmvgh** [comment]
moving letters around is just a little bit too much of a homework thing, especially when you're trying a new character build and you're likely to die a few times before you figure out its playstyle. I just don't bother rearranging inv2 any more, it's too much of a waste of time. I just try to keep an eye out for anything stacking higher than 5 in my message log, and quickly use-ID it before the insight system wastes an insight on it.

**Comment by jeremygurr** [comment]
I bet you could make a lua macro to do that if you wanted. Unfortunately I don't know that very well or I'd help.
