### ISSUE TITLE
transmutation changes 

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#312]
Ok I'm changing the transmutation slightly from my plan. I recognize that a player can cast blade hands at a good success rate (especially after turning careful mode on), and then put on heavy armour and slice their way through a lot of the game. Since the miscast checks are based on the original failure rate, this is viable. I don't want it to be. 

So instead the failure check will be based on your **current** spell failure rate. So just casting blade hands, your failure rate immediately jumps, because blade hands has a spell penalty as part of the form. So if you could just barely cast blade hands normally, you won't be able to maintain it for long at all because the failure rate jumps so much. You'll need a lot of transmutation skill to be able to maintain it for long. Then if you try to put on heavy armour, the form will dissolve much more rapidly, because of the increased failure rate that creates. Now if you happen to be insanely powerful enough to be able to have a 5% failure rate under blade hands **and** heavy armour, then you will be able to maintain the form for quite a while, and be devastatingly powerful. But that's quite hard to do of course. 

So this is effectively a nerf for those forms which reduce spell success rates. I'm not sure that's a bad thing in this case. So let's try it and see if it's not too bad. Blade hands is probably due for a bit of a nerf anyway :)

**Comment by Sandman25DCSS** [comment]
Yes, I like idea of nerfing Blade Hands. Tm starts with its "weapon" for Zot 5.

Another way to solve "keep your form while autoexploring" is to freeze duration when there are no monsters in view, that would allow to use vanilla crawl mechanic for Tm spell expiration.

**Comment by SleepySteel** [comment]
As much as I feel like form spells did need a nerf, I think this is too much a step in the wrong direction. Transmuters are of the warrior-mage metaclass, meaning they're expected to at least perform a bit of actual melee fighting- but it's gonna be pretty ridiculous to be able to do that when you need to invest enough in spellcasting that you can get blade hands castable after the blade hands penalty. It also nerfs spider form while leaving ice form alone, which brings in a strange balance of making one garbage and one still pretty good. I think it would be better to simply make blade hands not as powerful rather than make it ridiculous to upkeep, considering it feels really lame to cast blade hands and swing 4 times before they turn back. At that point, just make it duration based honestly.

**Comment by jeremygurr** [comment]
Try it out and see. Although it takes a little longer, I was able to get blade hands and spider form online without too much difficulty, and they are still as powerful as ever, ripping through early game enemies without much challenge. And that's with training unarmed combat and dodging at the same time.

**Comment by SleepySteel** [comment]
I also just remembered that Sludge Elf has the easier casting mutation. Trying right now, will report back with thoughts.

**Comment by G0rg0** [comment]
I haven't played with these changes, but I'd rather have the vanilla "cast before fight/duration based" than a situation where you can revert right in the middle of a fight. Even if it's down to a 1% chance, it'll happen and it'll kill you.

**Comment by jeremygurr** [comment]
It gives you plenty of warning before the form ends. It gives you a starting to unravel warning when you are about half way, then a "you can't keep this up much longer" warning when one more failure will pop your form. At that point you can either escape or recast the spell before you lose your form. That is no worse than vanilla where the duration is within a random range anyway, and you could still lose your form in the middle of battle.

**Comment by SleepySteel** [comment]
Just having tried it, it feels a bit more cumbersome than vanilla honestly. It's a little bit more convenient if you're using your forms for utility, like spider for running or ice for floating over water, but it's nowhere near as consistent in battle- I'd rather have a range that is reliable within a margin of error than the duration be anywhere from 5 hits to infinity. Also, casting the form while you're in the form is not allowed by the game, it tells you that you're already in that form.

**Comment by jeremygurr** [comment]
In vanilla crawl, spider form has a duration of 10 - 60 **turns**. In CA, it has 5 - around 500 **attacks**. 

So considering approaching the enemy and occasional repositioning, given low spellpower, in vanilla crawl you may pull off 7 attacks before the form fails. That's not much different than the 5 attack minimum in CA. 

As far as the maximum, would it improve your experience with transmuters if I added a 60 turn max like vanilla has? I don't see how it would. It just requires you to reform before every battle, which I don't think adds to the game more than the tediousness cost takes away.

**Comment by Sandman25DCSS** [comment]
I actually like the idea of having 70 attacks max. The limit might be reset after resting/autoexploring during 10 turns to prevent abuse with turning around a corner while chased by monsters. So it wouldn't make sense to recast the spell before every fight because it had already been "casted" automatically.

**Comment by jeremygurr** [comment]
hmm... good catch. I need to make autoexplore resetting ensure that some time has actually passed before giving the player a free reset. 

I'm not sure a player will really feel any difference between a 70 attack cap and the way it is now. And it's a little bit of added complexity, since the player must not only know that there is a % chance it will fail based on spell failure, but also that it will fail no matter what after 70 attacks. Not only that, but the game warns you when your close to unforming, so the player would just recast the spell to avoid that anyway. The only effect on their game would be the extra trouble in a long battle of recasting it once or twice. But since this is likely to happen anyway because of spell failure, it really means that over a 200 attack battle (does that ever really happen?), instead of recasting 3 times, they recast 4 times. Doesn't seem to justify the complexity cost. Unless there's something I'm missing here?

**Comment by Sandman25DCSS** [comment]
Yes, I agree, the max is not really needed as long as chance to expire is not incredibly low. And even then I guess having Spider Form 0% and literally unlimited is not OP because you have Dragon Form or Blade Hands easily castable at that point.

**Comment by yrmvgh** [comment]
Idle speculation: checking "current fail chance" instead of "raw fail" might be interesting, and less frustrating for some players. You could fight carefully to avoid breaking your form. Costs you SP, so you can't do it forever. But maybe that's enough to "cheese" small encounters, or "cheese" all the time - if you invest your item slots in a +SP or SP regen item - which is still a cost. And foregoing power mode is a cost; 50% extra damage is no joke against monsters that aren't very high EV.

I'll note I'm faaiiirrly happy with Trmt in its current form, I just need to set some RC file stuff to flash the screen or use -MORE- to stop me from autofighting when my form's about to break.

**Comment by jeremygurr** [comment]
That is how it is now. Current fail chance is used. So that is a good reason to fight in careful mode for a transmuter that may be struggling to keep their form. But also a good reason to train that skill so that the failure chance is very low, so that they can fight in power mode instead.

**Comment by jeremygurr** [comment]
Done.
