### ISSUE TITLE
bring back itemdest

### ISSUE THREAD

**Issue by eyestalker** [jeremygurr/dcssca#323]
Now that the inventory for consumables is effectively limitless, just prohibit dropping scrolls and potions and bring back itemdest (not for easy mode, though). Should probably be scaled with the amount of damage taken, so sticky flame with good AC and rF doesn't burn half of your scrolls. Conservation was a bad ego though and should not return.

**Comment by Sandman25DCSS** [comment]
Are you trying to decrease the gap between powerful combos and weak combos by encouraging to use consumables? Or is it a buff for stealthy characters and characters with ranged attack and a nerf for melee in heavy armour? Because there should be some hidden reason for the change, I don't think item destruction can be fun for anyone. Or am I wrong and you just want item destruction for item destruction? :)

**Comment by jeremygurr** [comment]
I'm not sure I see a good enough case for this though. Ultimately any given change should make the game more fun, which is quite subjective I know, and I'm sure not all of my changes have achieved this, but that's the goal anyway.

**Comment by eyestalker** [comment]
But itemdest is fun, it gives more character and personality to certain attacks and enemies. Oh well, it was worth a try.

**Comment by G0rg0** [comment]
Oh man, please do not bring back item destruction. Sorry eyestalker, that's like the opposite of fun for me.
