### ISSUE TITLE
Decrease Power/Care bonuses

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#329]
IMHO 150% damage for melee/ranged in Power mode is too much, it's pretty identical to Haste bonus which is 6 level. Also as far as I understand it stacks with Berserk, maybe it should not.
200% stealth in Care mode is too much, it's like having Dith's bonus for free, I went from very stealthy to uncannily stealthy.

**Comment by Sandman25DCSS** [comment]
Maybe change all bonuses to 20%? That would be closer to running bonus (1.1 to 0.9).

**Comment by yrmvgh** [comment]
The multipliers work on spells too.

Power Mode Magic Dart is one of the best spells in the game, IMO. Though at higher spell success rates, other conjurations in Power Mode can give it a run for its money, especially against multiple targets.

Whether it's a problem or not, and how much of a problem if so, is the question

**Comment by yrmvgh** [comment]
A common spell sequence I use goes like this - 
- Care mode on
  - Haste self
  - Cast battlesphere
- Power mode on
  - Prism, prism
- Power mode off
  - Searing ray
- Power mode on
  - wait, wait, wait
  - Dart dart dart dart dart dart dart dart dart dart dart dart dart dart dart dart dart 

Try something like that (moving your spells' usage from Care to Power or vice versa based on success rate) and see what you think.

**Comment by Sandman25DCSS** [comment]
Oh, I didn't mention spells because of 2 reasons:
1) I haven't tried them yet :)
2) 50% increase in spell power doesn't increase damage by 50% for most spells.

Magic dart is great but its main benefit (no miss) becomes less important as other spells get higher accuracy from spell power. Shock (Air/Conjuration) was really great even in Depths.

**Comment by Sandman25DCSS** [comment]
Maybe switching mode should cost 1 turn, that would solve some issues.

**Comment by yrmvgh** [comment]
Not a whole turn, but maybe an aut or two. I'd sooner see them weaker than see them costing auts though... they already occupy plenty of brainspace just because you are sorta deciding whether to use them on every single attack, spell, or move, wondering whether to burn some time would make more people go the Gorgo route and just not bother.

**Comment by jeremygurr** [comment]
Hmm.... I kind of like the idea of it taking a turn. I don't like a player feeling like they have to switch modes every other action. I think what should happen is a player should assess the threat, and determine whether careful or power mode, or neither is the best approach, then mostly stick with that in the battle. 

So what if going from normal -> power or normal -> careful cost 0 turns. But then going from either of the other two modes to any other mode costs 1 turn. So if you take the safe route of fighting in normal exertion mode, and need to escape quickly, you still can without a 1 turn penalty. But if you feel confident enough to not need the escape option, you can switch right to power mode and hack away.

Both power and careful mode should have powerful enough buffs to tempt the player to take the less safe path of burning through their SP. So although I'm okay with nerfing them a little, they should still have noticeable impacts on the game when they are on, and they should have a punishing consequence if they are used too much or in too dangerous of a situation. If the optimal play in almost every situation is to always use power mode, for example, then it isn't balanced correctly yet. It should be hard to tell in a lot of cases what the optimal strategy is, because the tradeoffs are so closely balanced. 

I have a debuff for haste on my list, the spell not the potion, where it will last until your SP runs out. Which means it will not allow you to escape a sticky situation if you've already used your SP, and although you can stack it with power mode, it means you will burn through SP twice as quickly, so the total damage done might actually be less, but it will be done more quickly, and so may be worth it in some cases, but not in others. 

With the 1 turn penalty for switching from power/care mode, it means you are really having to choose between saving SP, stealth and accuracy boost, or damage and spell power boost. Although you can switch it, frequent switching will not be optimal, so most players will probably settle into one of these choices in a battle. The benefits of increased stealth and accuracy should be close to as big of a deal as the benefits of increased damage and spellpower, overall. For any given battle, one will often be a much better choice than the other. But it shouldn't be the same choice for all battles.

So maybe 30% damage increase and 50% stealth increase. Still quite significant. But the path of conserving SP I think will still be a better choice than the 30% damage increase in some cases at least.

**Comment by yrmvgh** [comment]
5 or 10 aut for switching - but entering is free! - sounds not bad at all. (why consider 5? well because that's the cost of switching weapons, hey hey!)

**Comment by Sandman25DCSS** [comment]
If I am in power mode and I see that I need to escape, I don't need to switch to normal mode, I can use remaining stamina to run away and when I am automatically switched to normal mode no penalty happens. So there won't be any penalty for power mode in this case.

**Comment by jeremygurr** [comment]
Done.

**Comment by Sandman25DCSS** [comment]
I am permanently in Power mode now, losing 1 stamina to cast level 6 spells is not a big deal, I am not going to run out of 80 stamina. Please reduce bonuses, it's too easy :(
