### ISSUE TITLE
Do ghosts bring anything good to the game?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#335]
- Ghost as free xp for no reason
  - the deceased can have a spell arsenal that requires player skill to use properly. Infamous "butterfly ghosts".
  - the deceased can be reliant on items that ghosts aren't allowed to use
  - the deceased was reliant on divine abilities
- Ghost as ridiculous unstoppable thing
  - griefers
  - player encounters ghost while playing a low level naga venom mage or is otherwise perfectly capable to handle the floor they are working on, but is "bad at ghosts"
  - weird ghost behavior that causes some buffs on the deceased player to persist forever

On IRC it was proposed that they drop loot instead of just being xp pots, but that doesn't actually help the above issues.

**Comment by Sandman25DCSS** [comment]
Personally I hate player ghosts so count me among those who would like to put `generate_ghosts=false` or whatever to their RC file if we cannot remove ghosts by default.
When playing locally I always remove player ghosts.

**Comment by jeremygurr** [comment]
I have a ghost reworking idea in the future file that is a start. Tombstones would appear in the game instead of ghosts, which are harmless by themselves. They should appear in specific vaults (cemetaries, etc.), or branches (crypt and tomb). If a player chooses to destroy the tombstone, they summon the ghost. This ghost will be harder than before but drop some of the items they were originally carrying when they died (will probably need various limitations), making them an attractive challenge.

**Comment by jeremygurr** [comment]
tombstones will also be readable, which tells who died there, basic stats, and how they died (maybe a link to the morgue file?)

**Comment by yrmvgh** [comment]
Tombstones should be a bit of a mystery imo. I guess my hatred of detailed tombstones depends on what you mean by "basic stats" !

**Comment by G0rg0** [comment]
Maybe just something like their race and profession? 
`---Here lies yrmvgh the adequate!---`
        `---Troll Hunter of Okawaru---`

**Comment by yrmvgh** [comment]
Part of the problem with ghosts is the slew of "undead" freebies they get which makes them a lot harder for some characters to deal with than others. Fortunately the realism stops at also making them ephemeral - that would make just as much sense as their other benefits.

**Comment by jeremygurr** [comment]
Yeah I think race and profession is fine. But they will be even more difficult than vanilla ghosts, because you have the option to easily avoid them, and because the loot is greater.

They probably will have ephemeral 1 + undead perks + most of their characters qualities when they died. But I think their attributes should be reduced, maybe 2/3 of their original str, int, and dex (seems more thematically appropriate to me).

**Comment by Sandman25DCSS** [comment]
I believe at least disabling Moon Troll ghosts is a good idea for every player. D3 ghost with 100+ HP is unkillable by almost (?) all characers and unlike vanilla crawl, we cannot indefinitely retreat to stairs because of 1.1 movement.

**Comment by Sandman25DCSS** [comment]
Not to mention that ghost can stop you ascending if it's lucky to hit you.

**Comment by jeremygurr** [comment]
fair enough
