### ISSUE TITLE
Stair dancing and pillar dancing have been targeted. Are killholes next?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#337]
Should they be?

**Comment by jeremygurr** [comment]
I like killholes. They are already more limited though than in vanilla crawl, because all characters move more slowly than most monsters, unless you are in power mode, in which case you can only run so far before you run out of SP. And even in power mode, you face the dreaded movement penalty, further limiting your fancy footwork. 

Maybe I'm not an advanced enough player yet, but I don't see these as a significant source of tedium at the moment.
