### ISSUE TITLE
Boots of running

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#353]
Boots of running still give speed 0.9 turn per move like they do in vanilla crawl so difference is 0.2 (0.9 instead of 1.1). It's like Power mode movement for free. Maybe they should give speed 1.0 instead, what do you think?

**Comment by Sandman25DCSS** [comment]
I have not tried them in Power mode but probably they should give speed 0.8 turn per move in Power mode if this is not already the case.

**Comment by jeremygurr** [comment]
All movement should be 1.1 or slower unless in power mode. 

Hmm, I already fixed this one. Are you in the latest version (1.4.2)?

Ah I had an idea for a nice nerf. From now on, all speed up effects (including hasting and swiftness) only take effect while the player is in power mode. Casting haste or swiftness automatically switches the player to power mode. If stamina runs out early, the effects are gone until the player can get more stamina. Which at the moment there's way too much fruit around so that shouldn't be a problem, but we'll get to that...

**Comment by Sandman25DCSS** [comment]
Do you mean boots of running will be useless? I am on 1.4.
I don't think Haste needs another nerf, it is already bad enough because it spends stamina. I ran out of stamina very often in extended with my previous character. Power mode can be somewhat better than Haste for fighting (despite 30% damage is less than 50% damage increase) because it does not require time to activate and can be deactivated on demand so you can activate Power mode to kill something like panlord and then enter normal mode and be ready for next fights no matter what while after hasting myself I actually had to escape to restore stamina because 0 stamina means no Power mode and no Haste which means I can die to something dangerous. Also Power mode is good for running away (0.9 turn for Power mode vs 1.1*0.66=0.72 for Haste), still faster than most monsters.

**Comment by Sandman25DCSS** [comment]
By the way I ate just 1 fruit with my 15 runer, fruit description does not mention it restores stamina.
So probably we don't need ways to restore stamina, at least as common as fruit.

**Comment by jeremygurr** [comment]
Yeah description needs to be updated. Boots of running will help during power mode, but not otherwise, just like any other speed boost. It still makes escapes easier and helps the player to avoid a little more damage when running away, because you get away faster. 

No I don't think haste should have an extra stamina penalty above power mode. It should just have the normal penalty of being in power mode. I'll fix that.

**Comment by Sandman25DCSS** [comment]
I hope you know that running ego cannot be on artifacts and it means that boots of running will be worse than boots of stealth or most of artifact boots. How about changing it and making running be available on artifact boots?

**Comment by jeremygurr** [comment]
Yeah we can allow it to be on artifact boots.

**Comment by jeremygurr** [comment]
Done.
