### ISSUE TITLE
LRD should create stones and occasionally large rocks.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#359]
I can't be the only one that runs out of stones as an EE. Sandblast is decent with stones and for most people there are plenty of them laying about the dungeon but whenever I play EE, I run out. 

Flavor-wise, it would make sense for LRD to create stones - you _are_ blowing up rock walls with it. At high enough power it could even make the occasional large rock.

**Comment by Sandman25DCSS** [comment]
Sorry, I don't like this idea:
1) It makes Conjuration school and especially Stone Arrow optional, you can just keep training Earth Magic and get unlimited Sandblast before Lair. As of now there is interesting choice "Do I really need to use stones for this monster or should I save them for more dangerous monsters?"
2) Spamming LRD to get large rocks for throwing is boring/OP. For example, Tr has relatively good aptitude in Earth Magic.

No, I don't run out of ammo as EE.

**Comment by jeremygurr** [comment]
Stone arrow has a range and damage advantage, so it's still a superior spell, I think. Although I don't like spells that only differ in damage. Each spell should ideally have it's place, even in late game. Maybe the big benefit of using sandblast later in the game is high hit chance. But you'd want to use stone arrow otherwise. 

Yeah I don't like the idea of having to spam a spell for large rocks. So I guess that part wouldn't work.

**Comment by Sandman25DCSS** [comment]
Only range is an advantage. Sandblast deals more damage than Stone Arrow to targets with low AC  and when you start running into monsters with high AC you can already have LRD.
Stone Arrow uses 3/8 spellpower (3d11 at spell power 50), Sandblast with stones uses 2/3 spellpower (2d(20.67) at spell power 50), also Sandblast is a single school spell and will have much higher spell power when rushing to LRD. I tried ignoring Stone Arrow in vanilla crawl when I was lucky with stones, it's doable there too. That's why I believe the suggested change would decrease significance of Conjurations which is bad IMHO.

**Comment by jeremygurr** [comment]
Options I see are to:
1. remove stone arrow, if it really doesn't have a clear place.
2. make sandblast require conjurations too.
3. leave it like it is, with stones restricting use
4. allow LRD to create stones

I'm leaning towards 4 now, since I don't think it hurts too much at that point in the game.
