### ISSUE TITLE
Speed increase changes game balance

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#36]
Latest change to increase speed for walking into the same direction actually reduces number of attacks by ranged attackers. I use crossbow and I noticed that I attack less times than usually before monsters come adjacent. This encourages weird behavior by attacking from an unusual angle so the monster must change direction middle way to reach you.

**Comment by jeremygurr** [comment]
Hmm... I see two problems here. First the average time it takes for a monster to get to a ranged attacker is less, independent of the turning cost mechanism, since I only increased speed of part of the motion, and didn't reduce the speed elsewhere. That can be fairly easily fixed. Maybe it would be better to do the reverse, where the same direction is normal speed, and changing direction adds a slight penalty. This of course means that ranged monsters would get buffed a bit, since it would take longer for melee characters to get there. Hmm... maybe a compromise is needed here.

But this still leaves the other problem. Like you said, it still pressures the player to use strange tactics. But I have an idea. Unless the player is moving, the monster is going to move towards the player in as straight of a line as a grid based game can allow, which means zigging a bit if the angle isn't a multiple of 45 degrees. This can be fixed by allowing direction changes of 45 degrees, but no more. So up, up-right, up-right, right would incur no penalty after the first move, but up-right-down would incur two extra speed penalties. This still eliminates the zig-zag being as fast as a straight flight problem, yet doesn't force the player to worry about an optimal attack angle, since there is none. 

Pillar dancing would have an additional tactical element to it, since avoiding 90 degree turns would provide optimal speed around a pillar, but at the same time, that also increases the distance travelled, and so probably wouldn't be worth it. I'm okay with this added complexity, since in most cases there will not be a significant advantage in taking one path over the other (I think), and the concept involved is intuitive (you move faster by not making radical changes in direction) vs. the esoteric: you must approach a monster from a 30 degree angle for maximum safety.

**Comment by jeremygurr** [comment]
Ok I made the change. Tell me if this is better, or if it has other problems.

**Comment by Sandman25DCSS** [comment]
Sorry, I still don't like it. It takes 1.5 turn to walk south after walking north while it takes 1.2 turn to walk south after walking north-east so it is optimal to walk in zigzag instead of normal movement during exploring. How hard is it to make movement changes optional? I like standard movement the most, sorry.

**Comment by jeremygurr** [comment]
Done. New option is described in the readme. 

It seems to me like optimal exploration movement would be exactly like before, because even moving one extra space outside of the path you would normally take would cost 10 extra auts, only to save 2 or 4. That would never be worth it. Autoexploring overall would take maybe 3% more time, but it would likely be taking the optimal movement strategy in most cases, since the optimal movement strategy is to move in as straight of a line as possible towards the target. Taking a slower turn to round a corner, for example, to save the 2 aut penalty of a 90 degree turn, would add one extra space that the player must travel to get to the destination, adding 10 aut more to the time to round the corner, meaning the slower turning curve is less optimal than the standard direct strategy. 

But now you can turn it on or off :). I'm okay with that because I don't think it significantly affects game balance either way. It adds slightly to the time it takes for a melee character to approach a ranged attacker. For example, if the ranged attacker was 5 spaces away, the first move would be 12, and the other 4 would be 10, for a total of 52 auts, vs. the original 50 auts. The extra 4% of time isn't going to be game changing I don't think.

**Comment by Sandman25DCSS** [comment]
Great, now I can turn it off and play like normal. Thank you!
