### ISSUE TITLE
Feedback for the latest effort mode implementations

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#383]
- Power mode feels like it's just right. At least for melee characters and spellcasters. (need to play more ranged folk) It does what it's supposed to do, and feels significant without feeling overpowered.
- Care mode still feels cheesy on some spellcasters. Transmutations are fixed, but nothing stops you from Care-moding some summons. Then again, with sufficient time you can probably cheese out some high level summons regardless of care mode. I shall test that out.
- As far as +Stealth and +Acc are concerned, Care mode **does the most** for the characters that **need it the least**... dig it? I can explain further. Maybe flat instead of % ?
- Care mode still lacks clear and satisfying feedback. Maybe when you enter Care mode with non-zero stealth, you can get a "you meld into the shadows" message? Or become semi transparent? Maybe when you're in Care mode and "barely" land a hit, there can be a "you almost miss, but manage to hit" description change in the combat log?
- It's become second-nature for fork veterans, but new players still find mode toggling tedious, sorta in the way chopping was tedious. This probably can't be satisfyingly fixed without The Big Keybind Overhaul that has been alluded to, however.
- I want to reiterate that I think Power mode is in a perfect place right now, well done! You could remove Care mode from the game and suddenly the SP / mode system would appear to have no problems whatsoever. :wink:  (though vets might miss Care a bit - I personally enjoy it and just wish it had a smaller effect on spell fail, smaller effect on stealth, and more "player signaling" to make the +acc boost more obvious)

**Comment by Sandman25DCSS** [comment]
I know I am in minority here but I would be happier if Care mode didn't exist and Power mode was just a way to limit Berserk/Haste/invisibility without making your character any stronger. Also it's a cheap way to run away, I would change it to 1.0 instead of 0.9 so you cannot escape easily while luring is still really limited due to fast depletion of stamina.

**Comment by Sandman25DCSS** [comment]
Yes, I find toggling power mode annoying, it's optimal to activate it before every fight  on D1, for example.

**Comment by jeremygurr** [comment]
We had discussed a change earlier that will significantly reduce tedium, I just haven't implemented it yet. So let me express it clearly here, we can finalize the design, and then I'll put it on the top of my priority list and get it out, and I think things will run smoother for all. 

Power mode will only boost damage and spellpower, not increase movement speed, nor reduce stealth. It only burns stamina when actually attacking / spellcasting, so it may be left for many encounters in a row without negative consequences. Stamina doesn't regenerate when there are monsters around, but a player may rest and regenerate stamina normally while still in power mode.

Careful mode will boost stealth and accuracy like before. Like power mode, it only will consume stamina when attacking, so the sneaking boost is basically free. But wouldn't a player want to explore the dungeon in careful mode for the stealth boost, and then switch to power mode when they see a monster? To discourage this, there will be a 2 turn penalty for changing from any non-normal mode to any other mode. Changing from normal mode to any other mode will still be 0 turns. 

A new mode, called escape mode, will be added. It boosts movement speed (to slightly faster than the base movement speed of the race), decreases stealth dramatically, has a movement penalty of 1.1 for direction changes, and increases evasion a little (maybe 30%). It burns stamina on every movement, and at a faster rate than the other two modes. Escape mode will automatically be turned off when auto-exploring, unlike the other two modes, to save the player the extra keystroke. 

I believe it is necessary to have the escape mode slightly faster than the 1.0 standard speed, to somewhat balance against the movement penalty, and because of the fact that you are burning a valuable and limited resource, which you must have made sacrifices for to even have available for escape.  

So what key should be used for escape mode? Maybe 's' for "speed" mode, and 'S' for spell list. 
Does anyone ever use 'S' instead of c-s to save?

**Comment by yrmvgh** [comment]
I currently use S. I also use *q to quit, because c-q gets intercepted by my OS/browser. Looks like c-s is not, however - I can use it, and other people probably can too!

**Comment by G0rg0** [comment]
I think the proposed changes are great, it will make mode-usage a lot better.

**Comment by jeremygurr** [comment]
Oh I didn't really address the care mode issue. What exactly is the problem there? Not significant enough? Too powerful? Is it bad to be able to pull off harder spells sometimes at the expense of some stamina? Is the price not high enough?

I find careful mode very valuable for a transmutation that I'm struggling to cast. I will keep care mode on while I'm fighting in that form to significantly reduce the chances of deforming. 

As far as stealth and accuracy boosts, I'm not sure that a player who hasn't invested in stealth / accuracy at all deserves to have a dramatic boost while those who have invested heavily in it get almost no boost from careful mode. It would seem to encourage actually developing the skill or using boosters.  I find the mode quite useful in a number of situations.

**Comment by Sandman25DCSS** [comment]
Care mode is OP for casting spells outside of battle and spells that don't care much about spell power: Animate Dead, (Controlled) Blink, Repel/Deflect Missiles, Conjure Flame, Freezing/Poisonous Cloud, Shadow Creatures, most Transmutation spells etc.
I haven't tried stabbers yet but it looks like they will often use Care mode when trying to kill something.

**Comment by jeremygurr** [comment]
Right now care mode reduces spell failure by 30% or cuts it in half, whichever is worse. I need more details on how it is overpowered. For me overpowered means it ultimately takes away choices / interest from the game by overshadowing other options that would otherwise be viable. 

Current care mode allows a player to cast a level 5 spell when they are only at level 4 skills, but it is at a significant cost in stamina, since you have the normal careful mode cost, plus the hunger cost of casting a spell that is out of your league. That price seems to be a sufficient limiter at least in that scenario from making it overpowered. 

Stabbers would definitely have a significant advantage in being in careful mode (which is the intention), but it shouldn't always be to be in care mode even for them, because of how it lowers their chances of escape in exchange for significant boosts in stealth (50% higher currently). Stabbers should have about as much of an advantage in careful mode as melee fighters do in power mode, because they have the same cost.

The proper balance here is that it should not always be optimal to be in power or careful mode. There should be some situations where the risk is too great, and the optimal path is for the player to conserve stamina. But for basic popcorn battles, it makes sense to burn stamina in whatever the highest damaging mode is for the character.

**Comment by Sandman25DCSS** [comment]
Let me give you an example. My LOFE used Conjure Flame in relatively heavy armour, it just activated Care mode, blocked the corridor with flame, then took its time to switch to normal/power mode and used a polearm. So Care mode allowed me to use tactics which would be unavailable otherwise (miscasts can be quite bad).

I tried a stabber but didn't live long enough to get decent stealth and Dith's shadow. Yet I was able to stab an orc priest, orc wizard and a plain orc as a single group in early dungeon with stealth 4 or so, care mode really helps. But yes, I agree, using care mode makes escaping more difficult (as long as power mode gives speed boost which you are going to remove as far as I know)

**Comment by jeremygurr** [comment]
I think care mode _should_ enable you to use tactics you couldn't before. However, keep in mind here that switching from care mode to power mode cost an extra turn, and with the new mechanics being discussed here would have cost 2 extra turns. There are times when that would be worth it, but frequent use of care -> power -> care type tactics is naturally discouraged by the 2 turn penalty. So in that case it may be more optimal to switch to care mode (which is free when switching from normal mode), cast conjure flame (which you can do with less skill like you said), but stay in care mode and polearm the enemy across the flame, so you avoid the 2 turn penalty. If I remember right, polearming across flame like that causes it to go out faster than normal, but still gives you some good hits, and under care mode you will have a better chance of landing each hit and so increase your overall damage. And care mode doesn't have any damage penalties any more so it's just like normal mode, except with increased accuracy with the added stamina cost. 

I think switching from any mode to escape mode should also be free. But switching from escape mode to anything else and you pay the 2 turn penalty again. 2 turns may be more than is necessary here, 1 might be sufficient to discourage frequent mode switching. We'll experiment and find out. I guess it'd be best to start with a 1 turn penalty, and if tedius tactics are still the optimal path, increase it to 2. 

I don't like how complicated what I just explained was. Maybe I should just simplify to all mode switches cost 1 turn. Since you can stay in power or care mode now, there's not as big of a need to have a free transition from normal to power, since that will be happening much less often. One exception I want still: switching from anything to escape mode is free. It _is_ escape mode, and it wouldn't be a very good escape if you have to take a pounding before you can take off. You are already penalized by the movement penalty on your first move, no need for another 1 turn punishment.

**Comment by Sandman25DCSS** [comment]
I didn't know the conjured flame expires faster if there is a polearm, that's another spoiler then.
2 turns penalty is not a big deal since I am safe now and can take my time to do whatever I want. Switching to power mode makes some sense to increase damage but if care mode does not have damage penalty, then I can stay in care mode indeed.
By the way, I don't like to calculate while playing, right now it is not obvious which mode to use - power or care vs high EV targets. Vanilla crawl is easy, there is no way to significantly increase accuracy there, even Sure Blade spell was removed (and it is good IMHO).

I do like that you are trying to increase tactical depth of battles, I don't like that it can create OP situations/characters. In my current game I have Death Channel at red (30%), in care mode it becomes gray (15%), another example of care mode providing OP tactics.

**Comment by jeremygurr** [comment]
I don't think it's OP to consume a resource to boost skills. This already happens with hero and ash's boosting of magic when you have cursed rings on. You can achieve the same effect with death channel with cursed jewelry under Ash, except it's even more powerful because Ash's ability costs you nothing other than losing being able to quickly change rings, and it can be easily kept on indefinitely. In this case, the stamina cost and/or turns lost to mode switching penalty are much bigger costs than what ash or oka require for their skill boosting. 

Care mode should usually be better at high EV targets, and power mode should usually be better at low EV targets or high AC targets, making it easy to know which to do in most cases without any complicated calculating. Ideally you should be able to "feel" it. If you are often missing, switching to care mode should make you hit noticably more often. If that isn't the case then I need to increase the hit chance boost. Yes if it's a close call, then you will not know exactly which is better, however in those cases the difference will be small anyway, so a player isn't strongly compelled to do complex calculations.

**Comment by Sandman25DCSS** [comment]
I don't even need to cast Death Channel in fight, I can cast it before opening a door, entering a new level or just when I can spend 2 turn because Death Channel is more important. 
I have found Deflect Missiles and started using it in red area too (my spell power is crazy due to 40+ Int so it is unlikely to expire in fight despite relatively high spell failure).
And the funniest thing is that care mode makes Fire Storm go from red 24% to gray 12% without changing spell power, that's on nightmare before entering depths ;)

**Comment by Sandman25DCSS** [comment]
Thank you for explaining accuracy!

**Comment by Sandman25DCSS** [comment]
I am permanently in Power mode now, losing 1 stamina to cast level 6 spells is not a big deal, I am not going to run out of 80 stamina. Please reduce bonuses, it's too easy :(

**Comment by Sandman25DCSS** [comment]
> Jorgrun Earthshaker comes into view. He is wielding a quarterstaff of crushing.
>  You feel a surge of power!
>  The poison arrow hits Jorgrun. (119)
>  Jorgrun is poisoned.
>  You kill Jorgrun!

And I have just a single enhancer :(

> 111244 | Depths:4 | Noticed Jorgrun
> 111244 | Depths:4 | Killed Jorgrun

**Comment by jeremygurr** [comment]
So higher spell stamina cost then? This is exactly the kind of testing we need. What is your hunger at for that spell? If it's no hunger, then we need to increase per spell cost, otherwise we can increase hunger cost.

**Comment by jeremygurr** [comment]
Your hunger is 0 for all of those spells! No wonder you can cast them so frequently. Maybe it's your staff that's doing that. I'll figure it out.

**Comment by Sandman25DCSS** [comment]
No, I wasn't using staff of energy. It's just DE with 40+ Int and high Spellcasting. Maybe spell hunger should not influence stamina cost, otherwise staff of energy will be OP item. I still think spell power bonus should be much smaller, something like 20-25%.

**Comment by jeremygurr** [comment]
Ok the problem here is that you have 42 int and 19 spellcasting, which crawl multiplies and subtracts from your hunger cost, which means it's subtracting 798 from your hunger cost, making all of your spells hungerless. That's without any enhancers at all. If you equipped that staff of energy, the vanilla code would make it hungerless even if you had 1 int and 0 spellcasting. I changed that so a staff of energy only cuts hunger in half (which is still quite valuable here, since stamina is a much more meaningful resource than hunger was). 

So I basically put the hunger calculation on a simple squaring formula (which was actually already in the code but not used for some reason). This means low level spells will be a little cheaper hunger wise, but higher level spells more expensive. By level 9, they will cost twice as much hunger as before. This is without having power mode on. **With** power mode on, that cost is doubled and 2 is added, so even if the player reduces their hunger to 0 for a spell, in power mode it will still cost a minimum of 2 stamina per cast.

**Comment by Sandman25DCSS** [comment]
Sounds good

**Comment by Sandman25DCSS** [comment]
I've just spectated a game and it looks like stamina is used even in normal mode. I think it is a bad idea, casters are barely playable.

**Comment by Sandman25DCSS** [comment]
19 stamina for fireball on challenge difficulty in normal mode in Lair 6, that's just 5 fireballs. The character has 44 MP, what is it supposed to do with them?

**Comment by Sandman25DCSS** [comment]
41 stamina in power mode

**Comment by jeremygurr** [comment]
Fixed. Feel free to open new issues for stamina related topics, but I'm putting this one to bed :)
