### ISSUE TITLE
Make max stamina points scale with XL

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#385]
Having 80 stamina points makes early dungeon too easy even on nightmare, it allows to use Power mode non-stop in every fight, you are more likely to run out of MP or HP than out of stamina.

**Comment by jeremygurr** [comment]
You never need to run away from a fight in early dungeon on nightmare mode? That is definitely a problem, but seems to have more to do with the difficulty of early dungeon than the stamina pool. Unless you are saying that you can stay in power mode, attack a lot, _and_ still have plenty of stamina to escape with should things take a dangerous turn? If that's the case then maybe we need to increase stamina consumption for power mode. I assume you are playing a melee character? Because of spell hunger costs, spellcasters currently get hit much harder than melee, because they have to pay stamina costs twice.

**Comment by Sandman25DCSS** [comment]
Usually I run away, yes, but often 80 stamina is not enough to run away because stairs are too far. So it makes more sense to use those stamina points for better melee/spells.
I created the issue after playing DEFE, it is extremely easy due to Power mode, 8 MP is enough to kill everything then. And later 2-3 Powered fireballs kill Hill Giants. 

Another problem is lack of spell power caps, in vanilla crawl I couldn't kill a pack of 7 killer bees with about 15 powered magic darts (14 damage that never misses can be insane).

You know how spell power is calculated, right? http://crawl.chaosforge.org/Spell_power
 I have staff of fire and have just cleared Lair 2, my spell power for Fireball is 87 but in power mode it becomes 130.
Raw spell power for 87 power is 124, raw spell power for 130 power is 270. That's almost like having extra 2 enhancers (in addition to staff of fire) as every enhancer multiplies raw spell power by 1.5. So one extra enhancer gives changes raw spell power from 124 to 124x1.5=195 and another extra enhancer makes it 195x1.5= 292.5
So we have power mode real spell power 130 vs 2 extra enhancers real spell power 135.6 (that's real spell power for raw spell power 292.5)

**Comment by jeremygurr** [comment]
Hmm... stamina should be calibrated so that you _can_ escape in most cases even with 80 stamina, as long as it's fully charged, otherwise a vital choice is lost. Occasionally that choice will be lost because of deliberate choices made, but it shouldn't always be lost. Maybe escape mode can help with this. It allows us to calibrate stamina usage for escaping independently of stamina usage for attacking. For nightmare mode I want stamina to be _just enough_ to escape to the stairs in most cases. 

As a side note, I wonder if escape mode should have a damage or accuracy penalty. It's not really for attacking. I guess the movement penalty for repositioning plus the stamina costs may be enough. We'll start without any additional negatives, and add more if we find the need.

**Comment by Sandman25DCSS** [comment]
Well, then I have another issue - why stamina cost is higher for higher level spells? Shouldn't high level casters have a way to escape? Do melee fighters lose more stamina for attacking with triple sword instead of scimitar?

**Comment by Sandman25DCSS** [comment]
Sometimes I find a new monster while escaping and the monster blocks my retreat, losing a turn to exit escape mode could be too cruel here

**Comment by jeremygurr** [comment]
Stamina cost is based on hunger cost of a spell, so training spellcasting more also lowers the stamina cost for the spell. A spellcaster needs to be careful about casting a lot of high level spells limiting their escape distance. The stamina pool should be large enough that a spellcasting with reasonable spellcasting skills (not 0) will be able to cast a few high level spells and still have just enough stamina to escape. But if they push their luck and cast too many high level spells before escaping, they will run into trouble. I think this is a good thing. However, the hunger costs need to be balanced in such a way that reasonable spellcasting skills can still escape after casting a few level 9s or a lot of level 6s. If that isn't the case, I will lower the hunger cost. I need people to play some high level spellcasters to help get this balanced right. I'll start one too soon.

**Comment by jeremygurr** [comment]
If you encounter a monster while escaping, you don't have to change to power mode. Escape mode has no penalties except for movement penalty, which, if it's just a monster that's directly in your path, shouldn't be a problem. In fact, escape mode has an evasion bonus which would help over normal mode anyway, so you don't have to lose the turn. 

But if you do need to switch modes to deal with a new threat, then I think it is appropriate that it would take an extra turn. It's no different than switching weapons because you came across a hydra for example, or something that resists the weapon's brand. Well, switching weapons _is_ faster, but it still has some penalty. And I think power mode is a bigger boost than just switching weapons, and should be considered a little more carefully.

**Comment by Sandman25DCSS** [comment]
OH, that explains why I couldn't cast level 6 spell despite having 7 MP and 7 SP. I guess, I can close the issue.
