### ISSUE TITLE
Too high HP in challenge mode

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#400]
I tried challenge mode and was surprised with too high HP.
CA: FoTm, XL 12, Fighting 8.3, HP 117 (139 in Ice Form).
Vanilla: FoTm, XL 12, Fighting 8.3, HP 93 (111 in Ice Form).

**Comment by jeremygurr** [comment]
Fo have 2 higher hp apt in circus. It doesn't need it though, I can take it back to original vanilla apt. When I was first making many of these changes I didn't have as good of a feel of what was needed or not. Now with the additional mutations and game layout tweaks things have changed a lot since then.
