### ISSUE TITLE
Reduce the size of the Conj school, and possibly increase the size of other schools

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#435]

**Comment by yrmvgh** [comment]
https://github.com/jeremygurr/dcssca/pull/436

**Comment by jeremygurr** [comment]
some of these changes seem interesting, but I don't yet see the need to reduce the number of conjuring spells. Most are combined with other schools, which make it a challenge to develop many of them to high levels in a game. 

Also removing conjuring from many spells makes them much more powerful, since they can be more easily trained. Do we need them more powerful?

**Comment by yrmvgh** [comment]
In its current state, Conjuration is pretty much Spellcasting - a non-optional skill you need in order to be successful as a mage. Turning a Fire/Conj spell into just Fire makes it "more easily trained", yes ... for someone who is giving up access to 30+ conj spells to instead focus on the 12 fire spells. I see it as increasing the number of available options by chipping away at the no-brainer / required "option" that overshadows the rest of em.

**Comment by Sandman25DCSS** [comment]
There are many "conjuration-like" spells which don't use conjurations (Tornado, Airstrike, Shatter, LRD, Ignite Poison etc.) and players can ignore Conjurations if they want.
If players choose to use Conjurations, they have more variety for greater cost, I don't see a problem here.

**Comment by jeremygurr** [comment]
I agree. If conjuration forced all other schools to train it, that would be a problem. But as long as other schools have a viable option to avoid training conjuration, it seems like there is enough distinction there that the choice is meaningful.

However, this does spark a thought. Does the game benefit all that much from the conjuration school? Conceptually, all damaging spells are some form of conjuration, the fact that firestorm doesn't have conjuration connected with it is purely to keep it from being too difficult to train, and has nothing to do with whether it actually makes sense thematically. 

Almost every conjuration spell nicely fits within another discipline. What if the conjuration school was removed. Would the game lose that much? It would definitely be a buff for many low and mid level spells, since conjuration arbitrarily applies to them and not high level spells, but that can be balanced out by reducing damage per spell power point accordingly. 

As far as I can tell, there is _nothing_ to distinguish conjuration/elemental attack spell blends from pure elemental attack spells, other than how hard it is to train it. We can get exactly the same effect in a single school attack spell by reducing the damage/spellpower ratio to effectively require the same amount of training as before to achieve a given amount of damage.

I'm just not sure that the conjuration school brings more to the table than the complexity cost it incurs. Originally I suspect it made a lot more sense. It probably applied to all attack spells, and wizards that wanted to specialize in attack magic would use that. But now with how things have evolved, that no longer seems to be the case, since many attack spell for no apparent reason don't use the conjuration school.

**Comment by Sandman25DCSS** [comment]
Are you talking about plans? Currently Fire Storm/Glaciate use Conjurations.

**Comment by Sandman25DCSS** [comment]
Fire Storm/Glaciate have a physical component so unlike Bolt of Fire/Cold they can damage even monsters immune to Fire/Cold. I guess that can count as Conjuration component.
Vanilla crawl has some nice flavor for elemental attack: fire does not do damage to fire-immune monsters and the damage is reduced by rF+, cold the same for cold-immune and rC+, air does not do damage to rElec and earth deals pure physical damage similar to pure conjurations.

**Comment by yrmvgh** [comment]
We will end up duplicating some of this discussion if I don't link it: https://crawl.develz.org/tavern/viewtopic.php?f=8&t=19072

**Comment by jeremygurr** [comment]
Oops Firestorm does use Conj. Bad example. Substitute Tornado or Shatter instead :)

**Comment by jeremygurr** [comment]
the physical component concept makes some sense. But then the entire earth school consist of physical components. 

I doubt it is worth the effort to remove conjurations, but maybe worth thinking about a bit to determine if it really has a place, or if it just steps on other spell schools toes.

**Comment by Sandman25DCSS** [comment]
Yes, Earth is about physical damage but it's still very different from pure conjuration spells. Earth has the shortest range from all elements to compensate for lack of resists.

**Comment by jeremygurr** [comment]
But pure conjuration spells lack resistances too right? Magic missile is just as irresistable, yet has the longest range. Not to mention shatter, which I believe affects all LOS?

**Comment by Sandman25DCSS** [comment]
I was saying that Earth spells have shortest range, not Conjuration ones. Shatter is the only exception and I think you agree that it is still different from other spells with max possible range.
Lack of resistances is not important enough to make Earth spells look similar to Conjuration spells, they are still unique.

**Comment by Sandman25DCSS** [comment]
Magic Dart becomes useless middle game unless you pair it with Battlesphere. Not in CA of course ;)

**Comment by yrmvgh** [comment]
Perhaps instead of shrinking conj, other schools could be made into "basic schools". Every spell either buffs, debuffs, deals damage, or teleports you. So every spell could be hex, conj, charm, or tloc in addition to one or more other schools, and then "mad hexes with a splash of others" would be as effective as "mad conj".

**Comment by jeremygurr** [comment]
that's an interesting idea.

**Comment by jeremygurr** [comment]
Problems solved
