### ISSUE TITLE
Remove power/care/escape mode nightmare difficulty

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#455]
Power mode makes fighting easier than in vanilla, care mode makes casting/stabbing easier than in vanilla, escape mode makes escaping easier than in vanilla. I suggest to disable all modes at least on nightmare, the only exceptions can be done for Felid, Spriggan and Centaur: they can keep escape mode.

**Comment by jeremygurr** [comment]
Removing the modes makes the stamina system meaningless and removes many significant choices. 

Removing escape mode also makes the running away constraints that exist here and not in vanilla go away, bringing back a whole host a problems that we have solved here. 

If the problem is that the average damage done is higher than vanilla, then the solution that doesn't remove important choices is to lower the average damage. So both normal and power mode do less damage than before. Normal does a little less than vanilla. Power mode does a little more than vanilla (at the risk of reducing a players escape chances). Same with stabbing. 

Also keep in mind that when I release 1.5 (probably in a couple of weeks), all attack actions will use stamina, thus making it even more difficult for melee characters to escape.

**Comment by Sandman25DCSS** [comment]
Stamina will still be used for berserk, vampiric weapon, haste, regeneration. By the way I neglected to report it but currently it is possible to berserk while still being slow from previous berserk, at least as Spriggan with amulet of rage.

There are no significant choices for characters who cannot run like Naga or anything of Chei. Nightmare is expected to be nightmare but instead it becomes easier than vanilla crawl except for player HP. 
Making normal mode weaker than vanilla can work indeed, interesting idea, yet with Naga/Chei you will still use power mode all the time without thinking a second. Stamina is restored extremely slowly but it is not a problem with Chei whose piety doesn't decay.

I suspect being unable to melee with 0 stamina will encourage luring even more than it does in vanilla but we will see of course.

**Comment by yrmvgh** [comment]
> currently it is possible to berserk while still being slow from previous berserk, at least as Spriggan with amulet of rage

Yes, this was added many patches ago, intentionally, as a reward for large stam pools and/or good stamina management.

Exhaustion and 0 SP are extremely similar in both gameplay effect and thematic "flavor" so it doesn't make a ton of sense to have both, also.

**Comment by Sandman25DCSS** [comment]
Really? So now I can eat fruits/jelly and berserk non-stop in Zot 5?

**Comment by jeremygurr** [comment]
Ok I nerfed all damage/evasion/stealth/accuracy/spellpower. 

In standard mode, it's as it is now.

In challenge mode, normal mode levels are less than vanilla crawl, and power mode, for example just brings damage levels **to** vanilla crawl levels

In nightmare mode, even power mode doesn't quite bring it up to vanilla crawl levels (normal mode damage = 50%, power mode damage = 66%)

For movement speed, normal mode for all difficulty levels is still 1.1. Escape mode speed is now 1.0. Of course this is more significant for species that move faster than 1.0, and for players with boots of running, swiftness, haste, etc. And escape mode still has a 33% evasion bonus, regardless of difficulty mode, so it still has an important strategic value. 

So, for all difficulty levels, factors are increased by +33% over normal mode for all factors in the appropriate modes. The difference is that normal mode factors start lower for challenge mode, and much lower for nightmare. 

This is a dramatic nerf for challenge and nightmare modes, and should make both significantly more difficult than vanilla crawl. 

Play with that and see what you think. Should immediately affect all games.

**Comment by yrmvgh** [comment]
>  Really? So now I can eat fruits/jelly and berserk non-stop in Zot 5?

Hm. Hmmmmm. You always raise such interesting points, I'm glad I didn't delete you.

**Comment by yrmvgh** [comment]
Seems the simple f- oh, hi jeremygurr, you ninja'd me... anyway, seems the simple fix is "no eating while berserk/hasted"?

**Comment by jeremygurr** [comment]
Yes it is intended for you to be able to berserk multiple times if you have the stamina to pay for it. But things should be calibrated in such a way that normal stamina pools couldn't support two in a row. You'd need pool enhancers or easier modes or fruit to pull that off. And there shouldn't be so much fruit in the game that you can just berserk through large sections of the game. Although that probably throws off the fedhas balance. Hmm... might need to split that.

**Comment by Sandman25DCSS** [comment]
Awesome changes, thank you! Now even challenging can be challenging...

**Comment by Sandman25DCSS** [comment]
> I'm glad I didn't delete you.

Wow, I didn't know you own github ;)

**Comment by yrmvgh** [comment]
One annoying god that no one really likes all that much, is probably not worth fucking up whatever balance SP is supposed to have. We could disable fedhas, or let fedhas abilities also consume degen pots and uselessness scrolls as a stopgap.

I don't think a single person has played that god on our server yet.

**Comment by jeremygurr** [comment]
I have! I like fedhas. But if he's annoying or boring, we can certainly get to fixing that :)

Simple solution is just to make fruit not restore stamina. Only royal jelly, which is much more rare (I think). Or we could just make stamina potions. We should probably just move away from all "food" for simplicity.

**Comment by Sandman25DCSS** [comment]
I haven't tried Mummies with stamina system, do they work like other species? They are unable to eat/drink which would make them the worst species stamina-wise while in vanilla crawl they were the best hunger-wise...

**Comment by jeremygurr** [comment]
I had made mummies so that they don't have spell hunger costs, approximating the effect in vanilla. But with the new stamina change I'm making, that will need more tweaking. 

What we need to figure out is how we want mummies to function in the stamina system. 

With the new stamina system, spells will only cost MP, never SP. But the MP cost will be higher than normal, and can be reduced by improving spellcasting, just like hunger was reduced in vanilla, allowing more spells to be cast. 

So what I'm thinking is that we can give mummies will have a special mutation called "energy efficient", which reduces their SP _and_ MP attack costs. It would not save any other mp or sp costs, just those used in casting spells / attacking. Running will still use as much sp as before. Power and careful modes will use as much sp as before.

**Comment by jeremygurr** [comment]
Ideally, the stamina system would be so unobtrusive that a player that knows nothing about it could still play, and win, without ever switching modes. It may be a little harder than it otherwise would be, but it should still be doable. 

I like the different modes, as long as they don't become too tedious, because they move me closer to my objective of expanding the strategic depth of the game, which for me makes it more fun.

**Comment by yrmvgh** [comment]
Might be good for a player starting their quest for the orb to automatically start in Care then, among other tweaks towards that goal.

**Comment by Sandman25DCSS** [comment]
> Ideally, the stamina system would be so unobtrusive that a player that knows nothing about it could still play, and win, without ever switching modes

It is almost like how I am playing my HoGl of Beogh. Initially I used Power mode all the time for damage, later switched to Focus mode for getting less damage while autoexploring and now I am always in Power mode because my allies kill everything too fast and I want to attack something too. I used escape mode just once as far as I remember.

**Comment by jeremygurr** [comment]
That seems about right. Keep in mind, now that speed mode is separate from exertion mode, you can stay in power mode, and hit "g" for quick mode to quickly approach your enemies before your followers get to them. Well I guess that doesn't work too well because the movement penalty gums up the works while you are trying to move around monsters, and if you want to switch out of it, it costs a turn. I'd like exertion mode to be more of a strategic decision, where it may be kept in one mode for multiple battles, whereas speed mode may be used more often. 

I think I'll remove the movement penalty from quick mode and just make the SP cost the only limiting factor. And I'll remove the turn cost for speed mode switching, which simplifies things (speed modes changes cost 0 turns, exertion modes changes cost 1 turn) and allows a player to better use speed mode in a battle.

**Comment by jeremygurr** [comment]
Actually, I think I'll leave the 1 turn cost of switching from quick to slow mode. Don't want players to get too-micro managey here. 

So you can still rapidly approach a monster, but just leave quick mode on to take them out. But the price is addition SP cost with every movement until you have a turn to deactivate quick mode.

**Comment by jeremygurr** [comment]
This would allow quick mode to be used for short bursts of kiting. Do we want that? I suppose they are getting that in exchange for escapability, so they are taking a big risk in doing so. We can try it and see.
