### ISSUE TITLE
VS Lignify while already lignified -> lose stamina

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#457]

**Comment by yrmvgh** [comment]
Also, on the same character, level_27_cap = true resulted in a massive improvement to all skills that had been trained

**Comment by jeremygurr** [comment]
that's because the vanilla crawl experience scale is jagged, and the ca experience scale is smooth, and better supports higher levels. But they are calibrated to match at level 27. So the amount of experience to get to level 27 in vanilla is the same as the experience needed to get to 27 in ca. But earlier levels are more or less, because vanilla crawl has many arbitrary experience accelerators/reducers in the code. For example, you get through the first 10 levels much faster in vanilla crawl, but then things slow dramatically down for the next 10 levels, then things speed up again after that. CA just holds the same speed throughout.

**Comment by jeremygurr** [comment]
but on the other topic, are you saying that you can lignify when already lignified?

**Comment by yrmvgh** [comment]
Not 100% sure, as usual I find myself spectating more than playing. But the VS I was watching said "if I wanted to play a mummy, I would have picked mummy" while gesticulating obscenely at his meager skills, also yes it seemed like lignify was castable during lignify

**Comment by jeremygurr** [comment]
Fixed. I don't understand what the player you were spectating was complaining about though concerning VS skills. I don't think I've changed them much compared with vanilla, skill-wise. What was the concern?

**Comment by yrmvgh** [comment]
No, it wasn't VS-specific, it was the 27 cap thing
