### ISSUE TITLE
Nightmare mode reduces mp (+ hp just a lil bit) too much

### ISSUE THREAD

**Issue by Bloaxor** [jeremygurr/dcssca#464]
This penalizes casters far too much and doesn't affect the top of the melee foodchain at all, so there's really no reason to do it.
Casters already suffer from glass cannon syndrome, so it's not like the hp penalty won't fuck them up enough.

So really, just keep mp at 100%, and if you feel like an ass you can always special-case VS to still get a -20% penalty.

Hp is also a bit low (something is wrong if you say that XL27+ is recommended for extended), so something around -20% or -25% should do.

DUNNO IF THIS COUNTS FOR AFTER THE BIZARRO MP/STAMINA CHANGE

**Comment by jeremygurr** [comment]
I'm okay with tempering the differences here a little, since I just nerfed nightmare pretty hard with the most recent change.

What about changing it from 66% of challenge mode to 75%? Same with HP.

I'll do the opposite for standard mode. Instead of standard mode having 150% HP of challenge mode, it will have 133%.

**Comment by Sandman25DCSS** [comment]
I like nightmare as is, it is exactly nightmare. Please don't listen to Bloax, he just wants more MP for Slouch :)

**Comment by Sandman25DCSS** [comment]
I tried different combos on nightmare playing recklessly and I think the balance is quite good, only a few combos can reach Temple. The only thing I'd like to change is to speed up stamina regeneration, it takes 500+ turns to regenerate stamina to 80. Poor berserkers barely earn any piety because their stamina is set to 0 after berserk ends.

**Comment by Sandman25DCSS** [comment]
Also I have impression that damage from brands is not modified so something like whip of electro is vastly superior to even halberd on Mf.

**Comment by yrmvgh** [comment]
Thank you for testing such a variety!

**Comment by jeremygurr** [comment]
Ok stamina regen will be increased. Yeah brand damage needs to be handled as well.

**Comment by jeremygurr** [comment]
Fixed. Tell me how this feels now.

**Comment by Sandman25DCSS** [comment]
`382 | D:1      | Noticed an ogre`

Is it expected?

**Comment by jeremygurr** [comment]
Not normally. But the out of depth rules for nightmare are relaxed a little, so it is possible. This was changed when I first made this fork, and hasn't be touched since, so either it's just a rare occurrence, or something unintentional broke with this last release.

**Comment by jeremygurr** [comment]
fixed
