### ISSUE TITLE
Healing almost does not exist

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#47]
I found a single potion of heal wounds and no wands of heal wounds in 15 rune game, including some floors from 2 ziggurats. I spent 3 acquirements when the only unknown wand was one of heal wounds, still didn't get any. It made my game much harder than normal, since potion of curing is almost useless for healing. Not sure how it can be fixed, I guess making new healing mechanic optional will not work because of vault changes.

**Comment by jeremygurr** [comment]
I can take vault changes to 1/2 instead of 1/3 original, and boost the normal production a little. It's a little surprising that no wands appeared at all, which seems a little weird. Maybe it was just pure chance. Maybe I'll make wand of heal wounds original frequency, since they work quite differently than the potions anyway.

**Comment by Sandman25DCSS** [comment]
Yes, I agree, if the wand cannot be used with monsters in LoS (I haven't tried), it is almost useless during fight.

**Comment by jeremygurr** [comment]
fixed.
