### ISSUE TITLE
Normal mode feedback

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#470]
I have just reread README 

> damage, spellpower, accuracy, stealth, evasion modifications from vanilla crawl: 
> standard difficulty: 100% of vanilla crawl (means will do the same damage in normal mode as in vanilla)
> challenge difficulty: 75% of vanilla crawl
> nightmare difficulty: 50% of vanilla crawl

I am not sure we need to change accuracy, stealth and evasion. On nightmare stealth penalty makes some strategies impossible, evasion penalty greatly encourages using heavy armour instead of light armour, accuracy penalty makes effective damage 33% in power/focus modes (50% damage x 66% accuracy or 66% damage x 50% accuracy), 25% in normal mode, increases luck factor and greatly favors attacks which cannot miss (Freeze, Fireball, tier 1 stabbing).

**Comment by jeremygurr** [comment]
The big issue I see here is the unbalance between evasion being heavily punished while armoured characters are not. That's a tricky one. 

The other issue is much easier. We can temper the differences a bit. Instead of nightmare being at 50% in normal mode, it can be at 75%, and challenge can be at 87.5%. 

It's easy enough to reduce ac. The hard part here is that it doesn't make any sense. Why would power mode, for example, increase armour effectiveness? Or focus mode, would it have any impact on ac? That's part of the nice thing about armour, it works even when your character doesn't :)

So that means we need another mode to fix this painful imbalance (probably not what you wanted to hear)... What if there was a defense mode, where, for whatever reason, the character is acting in a way to maximize their armour, and minimize damage. This is different than escape mode, where your purpose is to get away and take the least amount of damage possible by moving quickly and being evasive. Defense mode will be a mode for the player that isn't going anywhere until these monsters are taken care of. Movement speed is reduced in exchange for a 33% ac boost. Of course, stamina is being consumed at a higher rate like the other modes. 

Or we could just take the evasion boost off of escape mode. I'm fine with either way.

**Comment by Sandman25DCSS** [comment]
My point is that we don't need several types of penalties because of multiplication effect.
It is ok to have reduced HP/MP AND reduced damage at the same time because it is possible to make one of them irrelevant: for example, you can kill things at range, or you can retreat after every fight to restore MP or you can escape without fighting.
But HP penalty does not combine well with AC/EV penalty because it means you have even worse effective HP. For similar reason we cannot combine accuracy and damage penalty.

**Comment by jeremygurr** [comment]
right that just means you need to reduce the penalty. By spreading out the penalties is reduces the situation where one particular build or strategy is mostly immune to the nerfing, while another is heavily nerfed. I'd rather them be somewhat nerfed to the same degree. 

So if nerfing ev and hp by 10% is equivalent to nerfing hp by 20%, I'd rather nerf the two by 10%, since it affects more combos and roles.

**Comment by Sandman25DCSS** [comment]
I think it is quite the opposite. There are builds that don't care about accuracy, about stealth, about AC, about EV, even late game (Firestorm, Glaciate, Tornado etc.). Having multiple penalties encourages to build very narrow and specialized characters who ignore many of those, for example decent AC/EV is worse than high AC/zero EV or zero AC/high EV unlike vanilla. It will make game easier because you won't need to train both Armour and Dodging.
 We need only one penalty - damage. I played enchanter with 300% HP monsters, I had to train Stealth/Short blades to really high values and even then I couldn't one-shot many sleeping monsters. Also 300% HP monsters were almost impossible to kill with pure conjurations, MP is a more serious limit than accuracy or spell power.

Of course we also need HP/MP penalty because it is relevant for everyone, I cannot just build good defense and take my time killing Orb of Fire with spear like I did in vanilla because in CA I have lower HP and damage and OoF has higher HP and damage.

**Comment by jeremygurr** [comment]
Okay with the new 1.5.1 release I took the movement speed back to 0.9 for all difficulty modes for now, until it is tested in this new context a little better. I felt like I needed to because I nerfed so many other things, it seems like all players will need that choice to escape. It also makes the whole stamina management a lot more interesting, since escape mode is a much bigger consideration when it actually has the ability to help you escape. This feels like an important dimension to exertion mode tactics, and it's at the heart of the stamina system. 

That being said, if after all of these new nerfs in 1.5.1, you still want escape mode (quick mode now) to be speed 1.0, we can change it back easily enough. But try out several characters. There is one of the most radical changes we've ever tried in this new version, and it will take a little bit of work to balance it, and see if it really adds to the fun of the game by deepending strategic options, or not.

**Comment by Sandman25DCSS** [comment]
I am not sure it is playable. I have 75 stamina as OgBe and it means I can attack just 12 times (6 SP per attack) in normal mode so I basically just berserk in every fight and then retreat to restore stamina.

**Comment by Sandman25DCSS** [comment]
[Storm dragon on D4](http://crawl.homedns.org/morgue/Sandman25/morgue-Sandman25-20160510-213455.txt) is probably a bit too much :)

**Comment by yrmvgh** [comment]
Before reading through this big thread

> The big issue I see here is the unbalance between evasion being heavily punished while armoured characters are not. That's a tricky one. 

This could be another situation where a percentage or geometric thing sounds nice because it "scales", but with AC, -4 AC equals roughly the same increase to incoming damage whether you're at 20 or 10. EV is less intuitive, but I expect similar math applies.

**Comment by Sandman25DCSS** [comment]
XL 1 NaFi spends 18 stamina to attack with flail in normal mode.

**Comment by Sandman25DCSS** [comment]
Currently it is unplayable, I got "lucky" to get Robust 2 from potions of mutations and even then there was no a chance. It does not matter which mode I am in because it takes 6 attacks to run out of stamina. Also my MP were 75, was it changed?
http://crawl.homedns.org/morgue/Sandman25/morgue-Sandman25-20160510-224135.txt

**Comment by jeremygurr** [comment]
Yes it is expected to get off just a few hits at first before stamina is gone in early game when the player has little fighting skill. But you can still keep attacking just fine at 75% damage without any stamina. That is expected. Just like spellcasters have to deal with. Early game for spellcasters is usually just a few shots and then they have to recover or use a melee attack. But even then they don't get to keep casting spells at reduced damage like melee fighters do .

It's different, but I'm not seeing a fatal flaw yet. I did update the attack speeds, so they are less extreme. I expect that to take a bit of experimenting to get it just right.

**Comment by Sandman25DCSS** [comment]
Yes, it is playable.
