### ISSUE TITLE
Stopped monster regeneration is Beogh's nerf

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#490]
It looks like monsters don't generate in Orc after clearing it. It significantly nerfs Beogh, previously it was a good idea to visit it again sometimes to get more followers

**Comment by jeremygurr** [comment]
They should generate just like normal. I don't think I've done anything to monster regen. I don't even know where that is yet. Tell me if this seems to keep happening.

**Comment by jeremygurr** [comment]
Ok I just did something to regen :)  Now monsters don't spawn. I added 20% more monsters to initial floor creation to somewhat make up for it. I also double orc depth for now, to see how it goes. If we like it we can double more floors. So basically orc 4 is still in the same place, but if you wish to go deeper, you can go up to 8. You don't get experience for any monsters past 4, but you continue to lose drain, gain piety, and can gather bodies. You can also farm for items. If item farming turns out to be a problem, I can disable item gen below the 4th floor.

**Comment by Sandman25DCSS** [comment]
I see, now I can use Orc 5-8 to get more orcs and also Beogh has a chance to give you followers if you have none currently. so I think we are good and I can close the issue.
