### ISSUE TITLE
monster spawning

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#492]
I'm thinking of turning off monster spawnng. My reasoning is that monster spawning in most situations creates more annoying situations than it does interesting ones. For example, I'm autotravelling from the bottom of lair through dungeon to orc, and am often interrupted by a trivial monster several times. Secondary to that is the potential for tedious farming activities, which I like to remove when possible. 

A point has been brought up for the need to restore orc followers from orcish mines for example. If there aren't enough orcs naturally spawning, I would propose that we double the length of each branch, but not move the "bottom" floor. So spider will still have it's rune on floor 4, but if you chose you could go 4 floors deeper, just to get more experience or items or whatever. But you could also just do the 4 floors and leave without any significant consequence. Naturally the creatures do get a bit tougher as you go deeper, but there is no treasure floor waiting for you at the bottom. All branch targets will be at the halfway point. And there should be a staircase on the bottom to exit the branch, to save more tedium.

**Comment by yrmvgh** [comment]
We've already turned off the food clock, so it seems sensible to turn off the respawn clock. What were those clocks attempting to curtail? They never seemed to do much.

Instead of putting higher-HD monsters in the "bonus grind" floors, and potentially way too much exp, I would make each floor progressively smaller and more dense - in other words, more zig-like - with a similar total exp value as the 2nd-to-last floor.

**Comment by jeremygurr** [comment]
I could make the sub-floor monsters 0 exp if that was a concern. They could just be around for bodies and drain removal or piety gain?

**Comment by jeremygurr** [comment]
Done.
