### ISSUE TITLE
Djinni and conjure flame.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#50]
I don't know if this counts as an issue, but it seems like Djinni should be able to cast conjure flame directly on themselves. Right now it gives "That would be overly suicidal".

**Comment by jeremygurr** [comment]
You aren't even allowed to cast conjure flame on enemies. Maybe you are talking about flame tongue or a different one? It should have better wording there, it is true, but I don't see an easy way to do that at the moment. But it should be prevented either way, because it would just be free healing for the Djinni! It's already quite easy to put a conjure flame cloud the ground and then stand in it.
