### ISSUE TITLE
Issues with new mana pool size

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#501]
Rods don't have enough mana to evoke their own effects

**Comment by yrmvgh** [comment]
How does guardian spirit interact?

**Comment by Sandman25DCSS** [comment]
Yes, new mana pool is really confusing. Previously it was obvious how it worked and you could always train spellcasting to get more MP.

**Comment by yrmvgh** [comment]
What is the scoop with the mana costs for Infusion and Searing Ray

**Comment by yrmvgh** [comment]
Eyes of draining, godabils, crystal balls, ghost moth

**Comment by jeremygurr** [comment]
rods work now. You can still train spellcasting to get more mp. It just reduces the cost of your spells instead of increasing the pool size. Same end result though. 

Yes mana shield is much stronger now that the mana pool is larger. We'll have to see how that plays out to determine if that is really a big problem or not.

**Comment by jeremygurr** [comment]
ok for miscellaneous mp gaining (crystal ball, etc) I multiplied all of those by 3, so that it is about as meaninful as it was before.
