### ISSUE TITLE
give jiyva at ecumenical altar

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#506]
I found `don't give jiyva at ecumenical altar if player xl is < 15, unless they are on nightmare difficulty` commit comment and I believe it should be reverted. Getting Jiyva is one of reasons for player to use ecumenical altar. It is not a bad god, it makes early game easier for the cost of harder late game. If the commit was inspired by my complaints in my GhMo game, then you should not forget that Gh cannot mutate normally so I lost one of the best things Jiyva gives you and was too emotional probably :)

**Comment by jeremygurr** [comment]
Currently jiyva altars often appear in the same vault as the ecumenical, so it's not making it harder for a player who wants jiyva to get jiyva. I'm not sure jiyva _should_ be that easy to get eary game, but the fact is that it is much easier to deliberately get jiyva eary game than it is in vanilla crawl, because there are new vaults that are guaranteed to happen in early game that usually contain jiyva. 

So taking jiyva away from ecumenical choice has little to no impact on jiyva availability to early game characters. 

Now for players who would like to have a random, but _playable_ god chosen for them early game, the ecumenical altars are fun. Making the ecumenical altars give you jiyva early game or trog if you're a spellcaster just causes players to ragequit and start over. Or in my case I would just avoid ecumenical alters, thus reducing potential fun in the game.

**Comment by jeremygurr** [comment]
Really I should make this apply to nightmare too. Nightmare mode is about increased challenge, but not drastic reduction of fun. Sometimes things that add challenge significantly reduce fun, and that's not what I'm going for. All difficulty modes should be fun.

**Comment by Sandman25DCSS** [comment]
I don't see why Jiyva should be impossible provided Xom is possible. Ecu altar is a gamble and it gives free piety as reward, without "bad" gods it is too good to ignore.

By the way joining Trog for book backgrounds is typical for Nemelex combo at DCSS tournaments, Trog is just awesome when you found any non-club weapon.

**Comment by jeremygurr** [comment]
I think getting Jiyva early is much worse than getting Xom. Xom shouldn't be a "bad" god. Just an unpredictable one. Trog for a spellcaster is a "bad" god. Jiyva also I think is a "bad" god in many circumstances. Xom _should_ be an overall good god, but you pay for his benefits with some unpredictability. If not, then it should be changed. I think Xom should be about as good of an option as any other god. Like drinking mutation potions. More often than not, they work to your advantage, but you need to be versatile enough to deal with the times when they don't.

Also, since Trog altars are easily found early game, and you can even start with Trog from the very beginning, a player isn't losing any choice by not getting Trog from an ecumenical altar. 

I don't understand why Nemelex players would start with Trog. What do you mean joining for book backgrounds? Spellcasters deliberately choose Trog early game with the intention of getting Nem later?

For me there is a fun aspect to having the game pick a god for you, but just like in the beginning, when you choose the job for a race, you can select "random viable", it's nice to have a "random viable" god too. If they had a job at the beginning that picked a random viable god for you, I would do that. But that would only promote start scumming of course, and ultimately reduce game interest by taking away the obstacle of a player not always getting the god they want right away in a game.

**Comment by Sandman25DCSS** [comment]
Jiyva is a very powerful god, it is among the best gods for many backgrounds (rangers is obvious exception). It makes early game (the hardest part of crawl game) extremely easy and then you get loot from Slime 6. Slimify is really good, it's basically the most reliable kill ability in the game. Jiyva's mutations and stat changes are awesome too, you can find a GDA with DEWz and use it later, even Chei is not that helpful with its +15 Str. And unlimited cure mutation makes the god good even in extended.

Sorry, I assumed you know what Nemelex character means. http://dobrazupa.org/tournament/0.18/#nemelex_choice (also see top of http://dobrazupa.org/tournament/0.18/overview.html)
Typical example is TrWz, you just join Trog to maximize your chance to win the combo.

Well, I think you can play with "join first found altar unless it is unplayable" conduct or just create new "Viable ecumenical altar".

**Comment by jeremygurr** [comment]
Well if people really like the truly random ecumenical altar, maybe the best solution is to create another. So we'll have a high risk altar and a low risk one. Of course the high risk altar could award more piety (maybe one more *)?

Now we need a good name for it.

**Comment by G0rg0** [comment]
Fanatical Altar? Since it would give additional piety?

**Comment by yrmvgh** [comment]
I dunno how much spectating y'all do, but I've noticed Lektor and SleepySteel use Ecu Altars a **lot**. So keep in mind that even though ecu altar is a bad idea, and most of us intend to pick and playtest specific gods, there are cool, fun, take-it-less-seriously players out there who love to roll with the random.

I used to be one but, y'know, playtesting. :crying_cat_face:
