### ISSUE TITLE
Magic pool problem

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#508]
From player's point of view there are several unsolvable issues IMHO:
1) guardian spirit. In vanilla crawl it naturally scales with XL and spellcasting/invocation/evocation. Int is not relevant at all, berserkers can train evocation etc.
2) +MP items. In vanilla they give plain +9 and it is enough to cast level 9 spell once or level 1 spell 9 times.
3) Int affecting mana cost. In CA we get double penalty for low Int casters, their spell power is already low and they can cast the spells less times on top of that.
4) channeling. Due to non-linear costs (my DECj spends 1 MP for level 1 spell and 10 MP for level 4 spell) effectiveness of all channeling really depends on spells used.
5) Easy caster species like DE become even easier. My DECj trained Conjurations only until level 8 and got amazing spell power (especially in power mode), focused mode allowed to cast high level spells even earlier on top of that, spellcasting is not needed at all.
My DECj joined Chei and killed [a pack of Yaks on D5 ](http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt) by IMB spam in power mode, this is crazy.

Suggestion: revert the change. Vanilla casters are more powerful than melee characters due to having ranged attack and thus should be actually limited by MP, not just potentially limited.

**Comment by Sandman25DCSS** [comment]
Also please make minimal range of Flame Tongue 2, currently Fire Elementalist is unplayable on D1. Even Earth Elementalist starts with range 2 spell and has stones to increase spell power vs dangerous monsters.

**Comment by jeremygurr** [comment]
Agreed.

**Comment by jeremygurr** [comment]
I meant agreed about flame tongue having a minimum of 2. The rest are things I have to think about.

**Comment by jeremygurr** [comment]
For guardian spirit, I think a better way for it to work is just take 1/3 of the damage from mp instead of hp. That is much simpler to understand, and no training at all is needed to use it to it's full potential, as all jewelry effects should be. Is there a good reason to do otherwise?

As far as +MP items, I agree. The % boost is no longer relevant with a fixed pool size. And giving enough for 1 extra level 9 spell seems about right. In this version, a typical level 9 spell costs around 30 mp. 

As far as channeling, I'm not sure what you're saying. It seems like channelling should just work like a potion of magic, just restoring a fixed amount of mp (randomized, but fixed relative to player stats).

If DE is too easy we can balance that by reducing their mp apt or spellcasting apts. But the increased differentiation between naturally good spellcasters and naturally bad ones is in line with my game goals. Hybrids are harder now, but more rewarding too, as I think they should be. It's _supposed_ to be very hard for a cave troll to use magic. All though in the current situation, rebalancing is definitely needed. I will temper most stats between these species to make it a little more difficult for a cave troll to use magic than vanilla, but not as hard as it is now. They are already heavily punished by low intelligence, so I think other factors can be reduced.

**Comment by Sandman25DCSS** [comment]
I don't see how vanilla guardian spirit is complicated. If you are a Felid with 60 current HP and 40 current MP and you get 50 damage, then 50x60/(60+40) goes into HP and 50x40/(60+40) goes into MP so you lose 30 HP and 20 MP. I don't understand why you are suggesting to use 1/3. If I am a Troll with 300 HP and 40 MP I still can use guardian spirit and stay caster in vanilla, in CA I will lose all those MP when taking damage extremely fast.

30 MP is 15-30 level 1 spells, right? So the benefit of the item will greatly depend on spell costs which vary with characters and even with skills of the same character. I don't see how it is less complicated than vanilla (again speaking as player here, not as dev).

I am saying that channeling is impossible to balance. If I am a Troll of Vehumet (and thus have low spellcasting, low Int, low magic skills, low MP but good failure rate and mana on kills), I can be quite powerful in vanilla because channeling depends on evocations only, it does not care about anything else. In vanilla I can channel the same amount of mana with such Troll and DEWz. Let's assume I was getting 9 MP per turn on average. What are you going to do in CA? Calculate level 9 cost for every character and give corresponding amount? But if I am going to use level 3 spell thrice? Or level 6 spell? Level 1?

And by the way spells are balanced by their costs and spell power caps. 
In vanilla at max spell power (25) Magic Dart can deal 1d8 damage for 1 MP, IMB can deal 2d23 at max spell power 100 and costs 4 MP, that's about 600% damage for 400% cost, of course player is encouraged to learn high level spells. 
In CA it's just broken, my DECj with spell power 50 spends 1 MP to deal 1d13 damage with Magic Dart and then spends 10 MP to deal 2d14 damage with IMB. That's about 200% damage for 1000% cost, it's just a mistake to spend so many MP. Obviously, you made low level spells more powerful than in vanilla but for some reason you are trying to make high level spells cost more mana than in vanilla. Why? It's already a very bad idea to go for level 9 spell in vanilla with most characters, do you really want to make level 6 spells bad idea too?

It is not about species, every species can cast Firestorm in 3 rune game in vanilla. If you are trying to balance magic system by making changes to species, something is wrong with the magic system.

**Comment by Sandman25DCSS** [comment]
> But the increased differentiation between naturally good spellcasters and naturally bad ones is in line with my game goals. 

I missed it. It's already boring to play Merfolk with polearm or Ogre with giant (spiked) club in every game and now you seem to do similar things to casters :(

**Comment by jeremygurr** [comment]
It can be 1/3 damage, or 1/2, or whatever. The specific ratio isn't all that important. But it's certainly simpler to say "1/2 damage comes from mp", than to say: "If you are a Felid with 60 current HP and 40 current MP and you get 50 damage, then 50x60/(60+40) goes into HP and 50x40/(60+40) goes into MP so you lose 30 HP and 20 MP"

But you have a point about this being a nerf to high hp casters. But having high hp as a caster is already a major buff, and certainly spirit shield isn't nearly as important for an ogre with 300 hp as it is for a Spriggan with 50 hp. 

No, with the 5 point spell minimum cost that I am planning on, 30 MP is 6 level 1 spells at best. It's also 6 level 9 spells if you manage to get about 100 intelligence and spellcasting :) but realistically it will be 1 level 9 spell, maybe 2 for a very specialized character.

re: channeling: No I'm just planning on fixed amounts for channeling. For a weaker character, it means they won't be able to even cast 1 level 9 spell. But then again, a Troll isn't going to be casting level 9 spells anyway. I see your point about the change causing intelligence to affect how meaningful channeling is with regard to mp cost, but don't yet see that it goes against my game philosophy here. Some balancing will be happening to make Trolls not _quite_ so bad, but really, I'm quite okay with the species that are really bad spellcasters not being able to ever pull off a level 8 or 9 spell, or that they can't cast quite as many level 3s after channelling as a species that is more suited to spellcasting. They make up for it by having stronger fighting apts, hp, etc. As far as low level spells, it's still quite practical for a troll to get level 1 and 2 spells down to their minimum cost, which will be exactly the same cost as if they were a DE. Yes they may have to invest a point or two in intelligence to pull it off, and train a few points of spellcasting, but that's all it takes to get low level spells at their minimum casting cost. 

Yes you are completely right about spending 1 MP to cast very powerful spells, and it's something I'm attempting to address with my 5 MP minimum for all spells. Eventually your Magic Dart and IMB will cost the same, but yet IMB will cause far more damage.

I think it's not a good thing that all species can pull off the most powerful spells in the game. That reduces choice meaning, and differentiation between species. I mean, if you took a troll and put ALL of your points and training into getting a level 9 castable, that would work. But you would do it at the expense of what trolls are really good at, and you will end up with a much weaker character than if you went for a hybrid or a pure fighter. Which I think is an important part of the character of a troll.

**Comment by Sandman25DCSS** [comment]
Felid can have 30 HP and 50 MP, Troll can have 300 HP and 25 MP and you are trying to make a number that works for both. It's not 1/2, 1/3 or anything else, there is no such number.
I tried to explain to you as to dev how guardian spirit works because from your comment I got impression that you didn't know it. Wiki explains its mechanic really good: 
`Wearing an amulet of guardian spirit links your HP and MP, causing all damage you take to be split proportionally between your HP and MP pools` 
That's all, no formulae are required.
It's a nerf to both Felid and Troll by the way.

> I think it's not a good thing that all species can pull off the most powerful spells in the game. That reduces choice meaning, and differentiation between species. I mean, if you took a troll and put ALL of your points and training into getting a level 9 castable, that would work. But you would do it at the expense of what trolls are really good at, and you will end up with a much weaker character than if you went for a hybrid or a pure fighter. Which I think is an important part of the character of a troll. 

It is exactly how it already works in vanilla crawl and now you are taking that option off. CA troll won't be able to cast level 9 spell even if it starts as magic background, puts everything into Int and joins Vehumet like I did in vanilla :(

**Comment by jeremygurr** [comment]
I understand that having a fixed ratio can't work for both situations, and I'm not trying to make it do that. Probably simplest is to just be a 1/2 split. 

However, I'm not that set on a fixed guardian spirit. I'm actually fine with doing it the vanilla crawl way, but you probably wouldn't like it because it is a significant buff to all but late game high hp characters.  So I start the game with my 30 HP felid, but of course I have my 100 MP mana pool, so doing it the proportional way, if I receive 10 damage, 3 comes from hp and 7 come from mp, basically like giving the felid heavy armour. Once the felid gets to 100 HP, that won't be so significant, of course. For a Troll, early game it will still be a buff, but late game it will become much less significant, which is the way it is in vanilla crawl anyway, only not quite so much since there is more MP. 

So I guess I'm okay with fixed or proportional guardian spirit. Whichever you prefer is fine. I mostly pushed for the fixed guardian spirit because I thought people would worry too much about the high MP pool giving too much protection.

**Comment by Sandman25DCSS** [comment]
I am not sure what to do here provided magic pool is going to stay in CA.
But please remove corresponding Demonspawn mutation, it can make the game too easy or completely unplayable depending on character play style and the way you implement guardian spirit. With other species at least I can choose to not use the item with that ego.

**Comment by jeremygurr** [comment]
So you want guardian spirit demonspawn mutation gone because it would give them too much protection with such a large magic pool? You wouldn't rather just tone it down by taking only 1/3 or 1/4 of the damage from mp instead? Guardian spirit is really just intended to be armour for a magic user.

**Comment by Sandman25DCSS** [comment]
I asked for removal because I don't think it can be balanced provided magic pool is the same for XL1 and XL 27 character.
Guardian spirit is intended to be extra HP pool for characters who want to have it :), there is no need to be a magic user like I mentioned with berserkers+evocation example earlier.

**Comment by G0rg0** [comment]
> No, with the 5 point spell minimum cost that I am planning on, 30 MP is 6 level 1 spells at best. It's also 6 level 9 spells if you manage to get about 100 intelligence and spellcasting :) but realistically it will be 1 level 9 spell, maybe 2 for a very specialized character.

This actually has me quite concerned. If it turns out that a high level ultra-focused spellcaster can only get _2_ lvl 9 spells out of a full mana pool, I don't know that anyone would want to play a caster. At least I won't. My entire focus as a caster is getting my skills / int / equipment in such a place  that I can effectively _spam_ lvl 9 spells in any given fight.

**Comment by jeremygurr** [comment]
You didn't understand the context of that statement. I was speaking about the number of additional level 9 spells that could be cast by putting on a ring of magic, not the total number of spells that could be cast. In other words, a specialized spellcaster should be able to cast an _additional_ level 9 spell beyond what they normally would be able to with a magic ring.

**Comment by G0rg0** [comment]
OK, that's a relief.

**Comment by yrmvgh** [comment]
> Guardian spirit is really just intended to be armour for a magic user. 

Whaaaaaaaaaat? Source? I use it on VS and Ds (and now, all races, sometimes) with high invo or evo characters most of all. Or on hybrids that want to train spellcasting, but don't need to spam spells.
