### ISSUE TITLE
Inconsistent attack speed

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#540]
I use finesse and a bow of speed. For some reason some attacks take 0.2 turn and other attacks take 0.4 turn. I started the fight in power mode and I am down to 0 stamina.

**Comment by jeremygurr** [comment]
fixed

**Comment by Sandman25DCSS** [comment]
There is something wrong with hand crossbow speed, it takes 1.3 (power) -1.5 (normal) turns with 9+ levels in crossbows. 
Can we just keep speed unchanged?

**Comment by jeremygurr** [comment]
That is functioning as intended. There is a small nerf to all basic properties based on difficulty level to better balance the buffs that exist in this fork. Plus it's another way to make nightmare more of a nightmare :)  ...

**Comment by Sandman25DCSS** [comment]
So you keep adding several penalties with multiplication effect instead of keeping a single penalty which is easier to control, right? So now I have accuracy penalty, damage penalty, speed penalty, HP penalty, EV penalty, XP penalty, monster HP penalty, monster damage penalty, monster HD penalty... This is crazy, not nightmare :(

**Comment by Sandman25DCSS** [comment]
Also it means I have to retreat and rest for stamina to restore completely after killing a single goblin, not fun at all :(

**Comment by jeremygurr** [comment]
I had already taken out the EV penalty. Most nerfs are quite small. 

I started a nightmare CeHu with a hand crossbow to see what you were talking about. I got to D:5 without any significant challenge, in power and quick mode most of the time. I died to menkaure after 3 hits, but I'm sure if I was a better player I could have avoided that. I should have run the moment I saw him, then I would have survived. 

But I almost never needed to pause mid battle to rest. Certainly not after killing a single goblin. So I'm not sure what you are referring to. I have auto-explore set to rest before moving up to 80% of everything, so I actually only need to hit the rest command a couple of times. Even then I probably didn't need to, just did it out of habit.

**Comment by Sandman25DCSS** [comment]
If most nerfs are quite small, what's their purpose? Even for veterans of CA fork it is easy to get lost in all those details. I imagine many players can be scared of CA complexity.

I am not sure what you mean as "I have auto-explore set to rest before moving up to 80% of everything", do you mean it waited for 80% stamina too? If yes, then this is exactly my point, I was at full HP/MP after most fights with goblins but I still needed to press 5 (or use your new 80% option) to restore stamina. And of course it is optimal to retreat for that, when I tried to rest without retreating I had to kill a new wondering goblin every N turns.

**Comment by jeremygurr** [comment]
The base stats in CA are a little lower than vanilla. There's no complexity to that at all. Do all players know every base stat in vanilla? It's the same number of variables in vanilla or CA, they are just set to slightly different values. At least CA is pretty open about what those values are. In vanilla most of those values are hidden. 

The auto-explore option I'm talking about has been in crawl for a long time. It's just these:
rest_wait_both = true
rest_wait_percent = 85

But I see you point about it being optimal to retreat before resting after each monster attack. I'm not sure what that has to do with the stats nerf though. You ought to be able to play in power mode for several encounters in a row without requiring tedious behavior. This problem existed before the nerf, because being in power mode is going to cost stamina, and you will need to rest if you want to restore it between battles. It's exactly the same for a spellcaster in vanilla. Each time they attack even the smallest monsters, they burn mp. That's never been an inconvenience for me because I just autoexplore, which rests first, between each monster encounter. 

So I do see that this is a problem. But I don't see how it's a new problem, since it has existed forever with magic users. Did you not rest to restore mp between battles when playing a spellcaster in vanilla? 

I _could_ remove this tedious optimal behavior of needing to retreat before resting each time, if you want. It's probably a good idea.

**Comment by yrmvgh** [comment]
Magic users can just use an axe, or very low mana spell, to knock off popcorn so as not to be forced into a constant cycle of resting and being stumbled over. DCSSCA players, even the tabbiest of autotab players, are forced to choose between a constant cycle of resting, or a constant cycle of toggling their effort modes (which were recently changed to be somewhat leave-on-able!)

**Comment by Sandman25DCSS** [comment]
Yes, I play with lots of retreats as vanilla caster. But when I don't want to play this way, I might pick a melee background and even go Makhleb for double fun, it allowed to basically press tab and o non-stop. Now even melee fighters need to retreat and rest :(

**Comment by jeremygurr** [comment]
Yeah I don't think that's a good thing to force magic users to switch to an axe just to avoid having to rest between encounters. That's a sign of a design flaw IMO. 

I _do_ expect players to want to rest between each encounter, but it shouldn't be tedious. For me, with auto-resting happening each time I autoexplore, this issue is non-existant, and there is 0 tediousness. But I can see how auto-exploring itself is not necessarily optimal, and retreat before rest is also optimal, which encourages a tedious behavior that I wasn't really aware of before. 

The solution is to remove the motivation for the behavior. I don't think there's anything wrong with consuming resources in a battle that need to be regenerated between battles. That's an essential part of the tactics of the game. The problem is in requiring a player to back up each time. This is solved by giving no advantage to backing up before resting.

How do we do that? 

One way is to take away manual resting entirely. As soon as the player reaches a peaceful state, they automatically restore mp, hp, sp, instantly. The requirements for a "peaceful state" would be something like they have either killed all monsters in their previous encounter, or they haven't seen them for say 10 turns or so. So you would still have a "wait" command, but it would just cause time to pass until you met the 10 turn requirement for restoring your resources. You would still have normal regeneration, so you could slowly build up mp while running away for example. But once "peace" has been reached, the resources just jump to their maximum.

So the typical encounter would be: come across a pack of jackals and wipe them out. After the last one is killed, you immediately gain your sp back, and can autoexplore or manual explore (if you're being paranoid :) ). If you end up having to escape, then the process is a lot like it is now. You go up a floor, hit the rest button, which passes time until the 10 turn requirement is met, and then you instantly gain the missing resources.

**Comment by Sandman25DCSS** [comment]
Well, I like the idea, it will improve quality of life. But I am afraid it will make crawl too easy, it is always exciting when you are low on HP in Hell and some fiend or hell sentinel is dropped at you by hell effect or when you are still low on MP after a teleport and some dangerous monster comes into view.
I am not sure if it's possible to implement but ideal solution would be to automate retreat-for-heal, something like Shift+x, <, Enter, <. I mean character autotravels to the nearest upstairs and goes on previous level to rest, then automatically goes down the stair back to current level and you take control of the character on stairs again (and can press o for autoexplore)

**Comment by Sandman25DCSS** [comment]
I think I will try to create it as macro and see how it works

**Comment by Sandman25DCSS** [comment]
We don't have food or piety decay so it should be ok.

**Comment by Sandman25DCSS** [comment]
Though it is still possible to run into an enemy so my idea is probably bad :(

**Comment by yrmvgh** [comment]
What if instead of instant-full, or the epically slow vanilla rates, all regen types increase over time when resting or OOC?

Like if you hit ., you get a 1/4teaspoon of resources back, as now. but rest 5 times and your regen rate goes up by 1.1^5 or something? As long as you're not moving or taking any kind of actions?

Then it goes faster, but the rate of increase scales with "how safe you are", so to speak.

**Comment by yrmvgh** [comment]
If you do go with the 10 turn thing, don't let it happen on the move. :wink: :wind_chime: :dash: :man_with_gua_pi_mao:

**Comment by jeremygurr** [comment]
the problem with just increasing the regen rate over time is that the optimal strategy is still to retreat before resting after every encounter.

I do agree that it is sad to lose the occasional surprise monster attack while you are trying to rest, but it is a 2% of the time gain against a 98% of the time savings. That being said... I wonder if there's a way to keep some of that surprise... 

Oh! I got it. As soon as you kill the last monster in an encounter, there is a chance that a new one will immediately spawn at edge of LOS. It will be a fairly low chance so as not to be too annoying (maybe 1/10?). The other 9/10 of the time, you just immediately regen. Of course there is a chance that the monster spawned is a whole band of monsters, and maybe there could even be a small chance that 3 random monsters/bands are chosen instead of 1. But they are always placed to one side of the player, so as to usually give a retreat path (although it isn't guaranteed).

**Comment by Sandman25DCSS** [comment]
I wouldn't like random monsters spawning, leaving current situation is better IMHO. I can decide to spend all my stamina to lure a monster deep into explored territory, for example.

**Comment by Sandman25DCSS** [comment]
Now I see that shortbow reaches min delay 0.4/0.5 turn (power/normal mode)  at skill 18 on nightmare, it is really different from vanilla ([0.6/14](http://crawl.chaosforge.org/Shortbow)). Not sure if it was changed in vanilla.
I think we can remove damage penalty/bonus from all modes. If you want to control damage, it should be done via attack speed. This way you will keep vanilla balance of weapons/monsters (short blades, slings, cursed skull etc.)

**Comment by jeremygurr** [comment]
I lowered the minimum delay a little to allow for further character growth, since CA is much larger than vanilla and needs more room for character growth.

**Comment by Sandman25DCSS** [comment]
> I lowered the minimum delay a little to allow for further character growth, since CA is much larger than vanilla and needs more room for character growth. 

It significantly changes balance late game which becomes easier due to increased damage per turn. I believe we should not change weapon speed, it should be identical to vanilla in normal mode.  Power mode still can have better speed because it has short duration (hopefully).

**Comment by Sandman25DCSS** [comment]
I mean you can control game difficulty by easy/standard/challenging/nightmare mode, there is no need to increase character power. Some guys can enjoy playing nightmare with character who is limited to vanilla crawl options.

**Comment by jeremygurr** [comment]
ok I restored min delay to close to vanilla levels. I had to reduce it in the first place because it was higher than vanilla levels because of other factors.

**Comment by Sandman25DCSS** [comment]
Thank you
