### ISSUE TITLE
Remove stamina cost for normal mode actions

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#554]
Currently it does not matter if I use Power, Focus or Normal mode, I still run out of stamina very fast and cannot escape. I suggest to make stamina be used in Power and Focus modes only (I am ignoring Quick/Slow modes here, Quick mode actions should have extra stamina cost of course). So player can choose:
1) Fight in normal mode and have full stamina just in case, ready to switch to Power/Focus/Quick mode if needed
2) Fight in power/focus mode spending stamina but lose ability to escape
3) Escape spending stamina

As a side effect it will solve problem with resting after trivial fights, players will be able to kill popcorn in normal mode and continue exploring immediately.

**Comment by jeremygurr** [comment]
Why are you running out of stamina quickly in normal mode? More likely the problem lies with this question. Specifically, what does an attack cost in SP (you can look at the description of a weapon to see, even though it's probably easier to just attack something... )

If you can't get through most encounters in normal mode and still have enough stamina to escape, then there's a problem. Assuming reasonable investments in the things that reduce SP usage of course. If you're trying to swing around a great mace with 10 strength and minimal fighting skill, you can expect to have no stamina ever. 

I think the problem may be the pool size. Maybe I'll temper the differences between difficulty levels with respect to sp and mp pools. I've already nerfed the higher difficulty modes pretty hard, it wouldn't hurt to step it down a little.

**Comment by Sandman25DCSS** [comment]
I was playing normally, great mace with str 10 and less than 15 fighting is almost impossible for me.
Crawl fight is very randomized so it can take several attacks to kill even an easy monster like rat or bat. Bat is even expensive stamina-wise because it has very high EV.
If you increase stamina pool, it will make escaping easier unless you change movement cost too.
What is your goal for attacks vs escape? How many tiles should XL 1 HuFi be able to run in quick mode? How many normal attacks (assuming it chose long blades, for example) can it do instead? How many power attacks? Focus attacks? You control all of it with stamina pool/costs...

**Comment by Sandman25DCSS** [comment]
Anecdote: with my current CeHu at nightmare it took me about 24 stamina points to kill a rat (missed 4 times in a row).

**Comment by jeremygurr** [comment]
It's intended that a great mace would be one of the heaviest weapons in the game. But maybe the scale reaches too high and I need to tone it down across the board. To measure this, we need to check various calibration points. To me, it seems like a str 10 character _should_ have a very hard time swinging around a great mace. 

Of course players will just avoid maces, and they will use long blades (which are much lighter) or polearms, which goes away from what I'm trying to accomplish. To compensate, we should probably give the heavier maces a little more base damage. 

Here are some numbers:

great mace:
str 10, fight 0: 40 SP
str 10, fight 5: 20 SP
str 10, fight 10: 13 SP
str 10, fight 15: 10 SP
str 10, fight 30: 5 SP

So if a typical encounter needs around 10 attacks, with a base SP of 100, at 5 SP each that leaves 50 SP after the 10 attacks, which is enough for 16 spaces of escape, which is probably ok. So minimum viable for a str 10 character wielding a great mace is 30 fighting. Of course getting there is insane. Let's look at a better fitting character for a great mace:

starting minotaur fighter, wielding flail
str 18, fight 3: 7 SP
str 22, fight 7: 4 SP

The starting place for a minotaur fighter seems about right. It's a little weaker than the 5 SP for effective attacks, but that can be caught up with easily.

great mace:
str 18, fight 3: 16 SP
str 22, fight 7: 9 SP
str 24, fight 12: 6 SP

So a starting minotaur is not able to wield a great mace effectively. But by around mid lair, they should be able to reasonably. You typically wouldn't find one until after lair anyway. This seems about right to me. 

At the moment, power mode isn't proportional to the attack weight. It probably should be though. But since it isn't, if you're paying 10 SP per turn to attack, might as well make it 13 SP per turn and kill them much faster. Although in the case of having trouble hitting the monster, focus mode may pay off more. 

I think it should cost 50% more for power mode. I'll try and get that change in place soon.

**Comment by Sandman25DCSS** [comment]
Maybe you misunderstood me. I am not paying 10 SP per attack, I am paying just 5-6. Yet due to misses and low damage hits I run out of stamina after killing a couple of goblins early game and after killing a couple of yaks in Lair.
Also I disagree with idea to increase damage for great mace to compensate, I believe it is expected that most fighting is done in normal mode with 0 stamina because many monsters come in packs and floors are crowded with monsters anyway (Orc is a typical example).
I like the idea to punish using heavy weapon with low Str, it will increase variety and will buff 1h weapons.

**Comment by Sandman25DCSS** [comment]
Also great mace is a bad weapon with low weapon skill. Have you used fsim (&F in wizard mode)? It allows to see that for example battleaxe is better than executioner's axe before Axes reach about skill level 22-24, similarly flail is much better than great mace at low M&F.

**Comment by Sandman25DCSS** [comment]
Also fighting skill increases damage almost as much as weapon skill so it is usually recommended to have fighting at least 40% of weapon skill. For great mace it means you should not use it before your M&F is about 16 and Fighting about 7.

**Comment by jeremygurr** [comment]
Ok I agree then about the stamina costs. I will lower normal mode stamina costs and increase power mode stamina costs (by making them cost 50% of the normal mode cost, instead of a flat 3 SP). This should enable you to occasionally have some SP left to escape in normal mode operations with reasonable skill training.

I do want to increase mace damage though. There isn't a reason for me to use maces if I could get just as strong of a weapon from long blades, with a much lower SP cost, and lower attack delay. That reduces choice. 

I think 1h weapons are already significantly buffed by the weight cost as it stands, since 1 handed weapons are always lighter than 2.

**Comment by Sandman25DCSS** [comment]
> I do want to increase mace damage though. There isn't a reason for me to use maces if I could get just as strong of a weapon from long blades, with a much lower SP cost, and lower attack delay. That reduces choice. 

Please don't. M&F is my favorite/default/best weapon category. Flail is quite good as starting weapon, Demon whip is the best weapon with high slaying (the only demon weapon with 0.5 turn per attack), Great Mace has the lowest weapon delay after Lajatang among big weapons and is very common, also Hydra is not an issue.

**Comment by Sandman25DCSS** [comment]
Also Whip has the highest chance to have electro brand.

**Comment by Sandman25DCSS** [comment]
I mean we should not compare weapons in power mode, we should compare them in normal mode with 0 stamina because this is when characters usually die.

**Comment by jeremygurr** [comment]
why should we significantly nerf one class of weapons? Was M&F OP before?

**Comment by jeremygurr** [comment]
And I didn't change whips, because they are the lightest of maces, they didn't need it.

**Comment by jeremygurr** [comment]
Keep in mind that increasing M&F damage basically brings them back to vanilla damage levels in normal mode, on challenge difficulty or higher.

**Comment by Sandman25DCSS** [comment]
> why should we significantly nerf one class of weapons? Was M&F OP before?

Do you mean it is already nerfed because of weight and stamina cost and you want to just compensate it?
As I wrote above I believe power mode does not matter for weapon balance, all weapons must be compared in normal mode with stamina 0 so if you increase base damage, you will buff Great Mace. And as I wrote above I believe Great Mace does not need the buff.

**Comment by Sandman25DCSS** [comment]
> Keep in mind that increasing M&F damage basically brings them back to vanilla damage levels in normal mode, on challenge difficulty or higher. 

I don't see why M&F should be superior to other weapon types. If Long Blades etc. are weaker in normal mode, on challenge difficulty than in vanilla, then the same should apply to M&F, they should not be changed.

**Comment by jeremygurr** [comment]
All weapons are nerfed across the board in normal mode, but M&F are nerfed more than others, because they are heavier and require a higher SP cost, thus making it more difficult to escape even if you are only fighting in normal mode the whole time. 

Example: 
Starting human fighter, str 16, fight 3, challenge difficulty, normal exertion
both flail and longsword have the same base damage and speed. And in vanilla there is no more penalty than that. But here, that flail costs 5 SP, and the longsword costs 3 SP. Why would you ever choose the flail? Left as is, no serious player would ever choose M&F. 

Here's another: 
a starting ogre, challenge difficulty, normal exertion
giant club and triple sword have close to the same damage
yet giant club costs 14 SP, and triple costs 8 SP

This is a bigger deal now that power mode doubles the stamina cost, instead of just adding 3. So now it always cuts in half how many attacks you can make before escaping becomes very difficult.

**Comment by Sandman25DCSS** [comment]
Probably we should use weapon base damage instead of weapon weight. The latter is no longer used as far as I know since item weight was removed. Then you will not need any special casing for large rocks, great maces or anything else.

**Comment by jeremygurr** [comment]
I added the weights to the existing structures, I didn't reuse old code. 

I want the added distinction. I felt like many of the existing weapons were way too similar. Is a mace really much different than a falchion? Except for the fact that a falchion is a no-no against hydras (a very narrow edge case), they are effectively identical weapons, adding nothing but complexity to the game. There's a significant difference between axes, polearms, and everything else. But in the everything else category things blur together. Having this weight dimension added makes it a lot more interesting decision to choose whether to go with a randart great mace you found or to stick with the great sword you've been investing in. 

This also is a big buff to 1 handed weapons, adding them to the choice of what makes a good end game weapon. Previously it was a no brainer that you should go 2 handed if you want an end game weapon. Now there are more factors to consider.

**Comment by Sandman25DCSS** [comment]
Interesting idea indeed but I suspect all good players still will go with highest base damage no matter how much stamina it costs to attack with because as I mentioned above usually players die with 0 stamina.

**Comment by Sandman25DCSS** [comment]
> Previously it was a no brainer that you should go 2 handed if you want an end game weapon. 

 There are many discussions in tavern about it, it depends on character really. I love shields personally and use different weapons in different games.

**Comment by Sandman25DCSS** [comment]
I mean it's hard to die with non-zero stamina because then you are supposed to be in either escape (faster than most monsters) or power (more damage per turn than in vanilla) mode

**Comment by jeremygurr** [comment]
Having 33% more damage _and_ 17% more attack speed is a pretty big incentive to find a way to make power mode work. Could easily put a one handed weapon over the top, depending on training and the particular weapon, and value of the shield. If that's not enough, then we need to add a little more :)

**Comment by Sandman25DCSS** [comment]
No, that's not enough :) Stamina and power mode are limited by design. Also no matter how well and long you can fight in power mode, you will feel lazy to run away and eventually will get to 0 stamina. I know it, I ran out of 233 stamina many times :)

**Comment by Sandman25DCSS** [comment]
I don't mean to increase stamina or bonuses, I mean that I will keep comparing weapons in normal mode only.

**Comment by jeremygurr** [comment]
Do you ever use stamina potions? That could play a big role too. I often forget that I have them. But that's a sign of it being too easy for me to stay in power mode. There needs to be a void before it can be filled. Stamina potions _should_ be quite valuable. It'll get there eventually...

I suppose educating a player to use a stamina potion to escape when they are low would help.

How do you have 233 stamina? Oh on easy mode? Do you have a ring or mut too?

**Comment by Sandman25DCSS** [comment]
No, I don't use stamina potions. It restores 20 stamina and I think the bonus is not enough to waste 1 turn for quaffing.

That was DD (+33% SP) on easy with a ring of stamina.

**Comment by Sandman25DCSS** [comment]
20 stamina allows to move 10 tiles, right? That means I will walk 10 tiles and monster will walk 9 tiles and can catch up on me next turn when I am back to 1.1 turn per move again. Or maybe my math is wrong and I should actually try it :)

**Comment by jeremygurr** [comment]
Really? On easy mode stamina potions should restore 60 stamina. I guess you are thinking of nightmare. That is a good point though. They are worthless if they are never a viable option. 

It actually takes 3 SP for each movement in quick mode. So that means I need to increase that a bit. 

Maybe I will just have them restore a flat 20 steps, so that would be 60 stamina, independent of difficulty mode.

**Comment by Sandman25DCSS** [comment]
I am not used to consumables giving different bonuses depending on difficulty, that's why I didn't try the potion on easy :). Please either change their description and/or make the bonus static. Many small things added together can result in OP things: huge HP + huge stamina pool + bonus damage + XP bonus and you are invincible on easy.
