### ISSUE TITLE
Ranged combat is OP

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#568]
Please see https://crawl.develz.org/tavern/viewtopic.php?f=17&t=19943&p=269739#p269739
I think we should nerf ranged combat somehow, it is extremely powerful, I tabbed everything as DD of Makhleb with arbalest.
Some ideas from tavern threads:
1) Ranged damage scales with distance, the further the less. 100% for adjacent, 90% for 1-2 tiles, 80% for 3-4, 70% for 5-7.
2) Inability to shoot at adjacent monsters
3) Limited range (depends on weapon skill, stats, weapon enchantment, god etc.). Maybe even on stamina so you cannot shoot for long at the edge of your LoS.

**Comment by yrmvgh** [comment]
Delete slings, arrows, and bolts!

Then probably delete player centaurs.

Then probably increase the apts a smidge on any race that is bad at all three of evo, spl, and throw, so that they have at least one decent ranged option.

**Comment by jeremygurr** [comment]
Scaling with range is easiest, and would probably do the trick. 

Thematically, the idea of not being able to shoot adjacent monsters makes the most sense, but I also don't want to force ranged attackers to have to get a decent melee weapon and train those skills too. They might as well be full melee and it would be less tedious. 

I think the "unlimited" range is one of the most distinctive parts of ranged weapons. Spells _sometimes_ give this, but usually not. 

That being said, I think we should make sure that this really is what it appears to be. You used an example of a DD of Makhleb with an arbalest, arguably one of the strongest combos possible for ranged attack. Comparing that to the strongest combos for melee, I'm not sure it's that much different. I'm pretty sure I also could tab through most anything with a MiFi or TrBe of Mak also. I suppose that isn't an excuse though. If TrBe of Mak is too powerful, it needs to be nerfed too. 

The thing I don't like about diminishing damage with range is it forces the players to get close, which diminishes the distinct flavor of ranged combat, which is to stay as far as possible away, focussing on speed and evasion instead of armour, which you'd otherwise have to focus on if you had to be close. It makes them feel a lot more like a melee character. 

I propose if ranged is too powerful, we can nerf speed, accuracy, or damage instead. And it may be that just the arbalest is a bit too much, and we can just tweak that. 

Or we could use diminishing accuracy over distance instead of damage. That has strong flavor congruence, yet still allows a late game player to mostly reduce that penalty (in a similar way that a heavy armour wearer reduces delay or spellcasting penalties). 

So let's say worst case (minimal skills and dex), accuracy is 100% of normal at 1, 50% of normal at 7. So if they have an 88% chance to hit normally, at the edge of their LOS they have a 76% chance to hit. If they have 99% chance to hit normally, they would have 98% chance to hit at edge of LOS, but it should be difficult to get there of course. We can probably cap the accuracy like attack speed is capped, so that distance remains somewhat meaningful. Maybe 95% max, so edge becomes 90%. Twice as likely to miss. 

If that's not enough we could make it 3x fail chance instead of 2x at edge of LOS. So 80% chance to hit becomes 40% chance to hit (triple failure). 66% chance to hit becomes 0% chance to hit at edge (could probably cap at 5%).

**Comment by Sandman25DCSS** [comment]
No character is even close to that DD, all those Ancient Lich, Orb of Fire, Mummy Priests, Draconian packs etc. couldn't even get adjacent to me.

One of the reasons why I linked to that tavern thread: ranged combat should stay more powerful than melee, it just should be limited in some way.

I think damage distance penalty does not change optimal pattern vs melee-only monsters, you still shoot as often as you can and you naturally shoot at closest monsters usually.
Yet the damage distance penalty will make positioning matter vs ranged monsters, you will be interested to lure Stone Giants around a corner, for example, and this is very good IMHO.

Accuracy penalty theoretically might work too but it is less interesting IMHO because there are monsters with really different EV, so the penalty wouldn't matter much vs Stone Giant (EV 2) and would make Spriggan Air Mages (EV 22 AND Deflect Missiles) almost unkillable from distance. I tried Power/Focus modes vs many monsters in that DD game, it didn't make much difference, especially late game (talking about accuracy here). With accuracy penalty at long distance you'd be less likely to use power mode and more likely to use focus mode. With damage penalty you don't have an obvious answer, both focus and power modes are reasonable.

**Comment by yrmvgh** [comment]
> I'm pretty sure I also could tab through most anything with a MiFi or TrBe of Mak also.

That's a good point

> If TrBe of Mak is too powerful, it needs to be nerfed too. 

That's not Crawl. If you want to make a balanced game, you have to have a LOT fewer things to balance... this is nethack, not brogue. It's filled with incomparables and wild dice rolls, scrolls of disappointment and vaults of the best item you could possibly hope for. And it's a game that has both minotaurs for the lazy... and nagas for the tenacious.

**Comment by jeremygurr** [comment]
I totally understand that this game doesn't need to be perfectly balanced like a competitive RPG, and that's not what I'm suggesting. The balance I refer to is fundamentally different. It's okay if the game is significantly easier or harder with a different combo, **if** it is still fun. The point at which a combo become boring because it's too OP, is the point where the kind of balancing I'm talking about comes in. 

re: accuracy vs. damage penalty: I see your point about accuracy penalty possibly tipping the scales too much in the favor of focus mode, which I don't want. But I still like the idea of being able to mostly circumvent the penalty if a player wanted too badly enough (probably wouldn't be optimal play, but it is part of making it "fun" play IMO). With the damage penalty, it's just reduced no matter what. There's nothing you can do about it. 

With fighters, strength is the clear dominant stat. Dex is useful, but strength is typically king. With spellcasters, intelligence is solidly on top, with dex being marginally useful. For a hunter, dex should be equally dominant, IMO. That rounds out the major classes nicely. Dex should be what a hunter pours most of their points into, with possible a few points into str for a melee backup or to increase ranged damage, or int for a little bit of spellcasting on the side. But dex should still be king. 

I'm not against a hybrid approach though. A little damage penalty plus a little accuracy penalty (not enough to be disabling, but enough to be meaningful). It's logical that if you shoot something far away, you're not going to have as much power, and it's not going to be as likely to hit. 

Maybe something like this:

damage: 100% at 1, 80% at 7
accuracy: 100% at 1, 80% at 7

The two compound each other, of course, and significantly reduce total damage done. It also gives the player their most power when they are at the most risk: when a monster is adjacent to them. Which is somewhat satisfying from a player's perspective. 

I've got an active character now (CeAM) that just got it's first rune that would be a great test for this. I should be able to feel an immediate nerf once deployed.

**Comment by Sandman25DCSS** [comment]
I am not sure you understand. Pure melee still can die to ranged monsters or a couple of Juggernaut attacks. My defense was not that great, I just wasn't attacked most of the time. I actually even used harm for quite some time, it was fun.

**Comment by Sandman25DCSS** [comment]
My reply was to yrmvgh

**Comment by Sandman25DCSS** [comment]
> But dex should still be king. 

This can be achieved if ranged attack uses Dex instead of Str for damage bonus.

**Comment by Sandman25DCSS** [comment]
> I'm not against a hybrid approach though

Unfortunately stamina system is against it. I stopped throwing javelins at monsters with my melee characters. It takes less stamina to kill popcorn with melee, it is a good idea to keep stamina for power/quick mode when fighting dangerous monsters.

**Comment by Sandman25DCSS** [comment]
> damage: 100% at 1, 80% at 7
>  accuracy: 100% at 1, 80% at 7

Good idea, I like it.

**Comment by jeremygurr** [comment]
Done. Tell me how it goes in a new issue, I don't like issues to get too long or too old :)
