### ISSUE TITLE
Too many potions of stamina in a stack

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#574]
> e - 34 potions of stamina {!q} (gained 22)

**Comment by jeremygurr** [comment]
Hmm... they can't spawn with more than 3 in a stack. That must mean it was a food vault that had a stack of 22 fruit, which got converted to stamina potions... tricky.

**Comment by jeremygurr** [comment]
My problem is that I'm not fully committed to removing all food. There are so many food themed vaults and aspects of the game. I guess instinctively I don't want to do all the work to remove every trace only to want to bring it back. 

And it's sad to lose so much flavor too. The spriggan baker was so cool!

So maybe I need to figure out a different approach here. This will require a few changes in different aspects of the game at the same time to work. 

Maybe we keep bread, pizza, fruit, and royal jelly. So you still have a little more inventory clutter, but at this point we should have plenty of room. But each needs it's purpose.

fruit: replaces magic potions. Restores 25 mp (typically 1 level 9 spell)
bread: replaces stamina potions. Restores 50 sp (typically enough to run 17 spaces)
meat: replaces stamina potions: Restores 50 sp. 
pizza: more rare than the above, but adds 50 to stamina _and_ magic (because it has fruit and meat toppings :) ).
royal jelly: temporarily removes stamina costs

Meat and bread are exactly the same, except: meat gives higher sp for carnivores, and meat is sometimes dropped by creatures like hides are (but only some kinds, like pigs or sheep). Herbivores get reduced sp from meat, but full sp from bread. Yes, this is obscure and somewhat spoilery (although we will definitely add good explainations to the item descriptions in game). But it preserves a ton of flavor. They are exactly like potions, so this creates some redundancy that I'm usually against. But frankly, it saves work to not have to redo a ton of vaults, and increases ease of merging in future vanilla code. 

So we will need some key command changes to support this. We might as well wrap in our command simplification into the same effort:

c: consume a consumable (quaff a potion, read a scroll, eat food)
w: wield, unwield, wear, unwear, put on, take off, etc. 
q: quit power or focus mode

**Comment by Sandman25DCSS** [comment]
> c: consume a consumable (quaff a potion, read a scroll, eat food)
>  w: wield, unwield, wear, unwear, put on, take off, etc. 
>  q: quit power or focus mode

I remember similar discussion in tavern. Many players  (including me) would like to keep current behavior. It is much easier to read scrolls when the menu contains just scrolls, quaff potions when the menu contains just potions etc.

**Comment by jeremygurr** [comment]
I'm not sure it justifies the extra keys required. The consumables require 3 keys, and the equipables require 5. That's a lot of valuable keyboard space. 

But I'm also a big believer in letting a gamer have a great deal of control over their interface, so they can make these kinds of decisions themselves. So then what really needs to happen is base commands need to be improved to support either philosophy. And then new players are started with a default set of macros that give them classic vanilla behavior. This will be part of my bigger keyboard rework, which I will put off for now.

So for now, I need to bring 'e' back for eating. That means we need to move the exertion mode keys.

I like 'p' for power mode. 'p' is totally meaningless in all other cases except for fedhas corpse sacrifice and praying at altars. When a player is at an altar, 'p' could function normally. Otherwise, it could switch to power mode. Then we need a key for focus mode. Maybe we can use 'F'? Does anyone use CMD_THROW_ITEM_NO_QUIVER? 

Or we could use '[' for focus mode, ']' for power mode, '\' for normal mode. They are used rarely enough it's okay they aren't super easy to reach. Maybe this is better. Do people really need a special key just to look at their armour?

**Comment by Sandman25DCSS** [comment]
'\' is used relatively often. For example, I disable rings of protection from fire when I have 2 of them. Or rings of protection when I don't need them because I found rings of slaying.

**Comment by Sandman25DCSS** [comment]
'F' is useful when you want to throw something without quivering like javelins when blowgun is wielded. Personally I never use it though.

**Comment by Sandman25DCSS** [comment]
Also I am not sure how to throw net when you have a launcher equipped, it cannot be quivered as far as I remember (though I can be wrong here)

**Comment by jeremygurr** [comment]
Hmm, I actually use \ a lot too. I forgot. Maybe setting auto-pickup options can be moved to '|' instead (shifted-'\'), because it's not used often. So []\ seem best for exertion modes then, and I can give 'e' back to eating.

**Comment by Sandman25DCSS** [comment]
Quote from today's conversation in tavern:

> If I want to shoot just one curare needle (very common, since once you hit you don't want to shoot more) it is much easier to use F, since then I don't have to both quiver and then unquiver (possibly forgetting the latter step!) when I use curare.

**Comment by jeremygurr** [comment]
makes sense. I'll leave F alone.

**Comment by yrmvgh** [comment]
I still like the idea of a foodless crawl. Is a loaf of bread a necessary part of the spriggan baker "joke"? Isn't the back room the joke?

**Comment by yrmvgh** [comment]
What about this. You keep "food" in the game... by doing an aggressive find/replace in an external editor, renaming "gold" to "snacks". All food-themed vaults remain, and you can find food on the floor, but it converts into 5, 10, 25, 50 gold or whatever based on arbitrary numbers, or based on its old nutrition value.

**Comment by yrmvgh** [comment]
So "snacks" are the currency of the dungeon residents, like bottle caps in Fallout. And stamina potions now can just drop normally using the potion allotments, they don't have to be derived from food drops in any way.
