### ISSUE TITLE
crazy idea: flexible resistances

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#577]
What if, each time you tried to hex a monster, it's MR weakened a little, much like hp steadily goes down when whacking the monster, making it easier to eventually kill them?

It may or may not go both ways (where the monster could wear down _your_ MR). I can see some advantage in each approach. 

We _could_ even apply it to rF, rC, rN, etc.

It doesn't have to be much. Maybe it just degrades 10% each hit. So unless you are being pummeled by the same kind of attack over and over, it may not make much difference. Or if you are being attacked by a group of the same kind of creatures.

Or we could just throw this onto a particularly nasty rune curse.

**Comment by Sandman25DCSS** [comment]
Can I just say that I don't like it or should I provide arguments? :)

**Comment by yrmvgh** [comment]
conj (and weapons) have a nice thing where if you fail to kill the target outright, you still "increase your chance of killing" with the next bit of damage. you will get there, even if it's by nickels and dimes.

hexes are awesome, but failing twice in a row makes ya wish you'd just done damage. it doesn't count towards your next attempt like damage does - damage makes progress, but MR checks only have the pass/fail binary. 

it's really frustrating to have a 50% success chance, then try and hibernate that hydra, but fail 4 times in a row.

now, crawl's more RPG than roguelike, but in a roguelike, a large amount of symmetry is preferred... players might be uhappy if monsters could "grind away" your MR with say, repeated attempts to banish. but imho why aren't you killing / cc-ing it, don't let it grind your MR down if you don't want your MR ground down ;) get good!

**Comment by Sandman25DCSS** [comment]
Conjurations/weapons can miss or deal 0 damage.

**Comment by Sandman25DCSS** [comment]
Also killing a hydra with conjurations/weapon in 4 turns is awesome, usually it takes more time.

**Comment by Sandman25DCSS** [comment]
It is often a good idea to use confusion at hydra first and only then cast hibernation. This makes it more likely to not die if the hydra wakes up, also usually confuse has higher success chance/power.

**Comment by jeremygurr** [comment]
You _can_ just say you don't like it, but it's not as convincing :)

**Comment by Sandman25DCSS** [comment]
Ok, here are the arguments then :)

About hexes vs monsters:
1) You can reset the fight until you get that high MR (or just dangerous) monster is at the edge of view so you can cast the spell multiple times.
2) Hexes are already one the best tool in the game, especially with increased monster HP and stamina system because you can kill 200+ HP monster with a single cast of level 2 spell. (No, please don't buff monster MR with runes).
3) Hexers are encouraged to have a secondary tool for dealing with monsters. Confusing everything is boring (for me at least).
4) I don't want to check success chance every time I target a hex. It can be especially annoying when you have a pack of identical monsters in view and they swap positions with each other. Maybe it's interesting gameplay for some players though.

About rF+ etc. vs player
1) It's very common to meet a group of Ugly Things of the same colour and they are very dangerous. If they can decrease your resistance with every attack, they will be deadly. Crawl monsters are balanced around player having 50% resistance in all elements I believe.
2) It's annoying/time-consuming to check your resistance after every hit to see if you need to swap resistance when you are fighting monsters with different elemental attacks.
3) It would be yet another reason to retreat after killing a couple of goblins.
4) There are already monsters who reduce resistances (rP-, rF-, rRandom-).

About MR- vs player:
1) Paralysis
2) Banishment
3) Confusion
4) Slow

I can think of more reasons if needed.

**Comment by yrmvgh** [comment]
∆
