### ISSUE TITLE
Nerf spell failure

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#590]
I have Dex 20, Spellcasting 8.9, Hexes 10.3 and wear plate armour with 18.2 skills in Armour and Str 22. Yet Invisibility fail rate is 12% (gray) in Power mode.
I tested vanilla, the same character (with Int 20) would have fail chance 95% (red).

**Comment by jeremygurr** [comment]
I'm glad you said that. I felt fail chance was too easy, but it seemed like people had been complaining so much that things were too hard that I hesitated to increase it. I'll take care of it :)

**Comment by jeremygurr** [comment]
Although keep in mind that I'm not trying to perfectly match vanilla for fail rates. There are too many different variables at this point to have any hope of that. I'm correcting balance now not because vanilla is different, but because the current situation is too easy. But it is still nice to know where vanilla is at for a rough ballpark figure.

**Comment by Sandman25DCSS** [comment]
After thinking a little I think fail rates should be relatively close to vanilla, at least before XL 27. IMHO it is a good idea to require significant investment in schools, especially for level 6-9 spells.
Funnily I have 7% Passwall with 0 transmutation/earth and plate armour in power mode:) http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt

**Comment by jeremygurr** [comment]
I agree completely. The exact fail rates may not match entirely, but we should achieve the same feel, specifically that it should be quite difficult to get level 6-9 spells online before a certain part of the game, even with focus mode. Ideally, non-focus mode should have a little worse failure rates than vanilla, and focus mode should be a little better (since you are paying a much higher price for the spells, double mp in this case). 

Yeah I'm going to need to check out your character. Something's seriously broken there. I must have introduced a new failure rate bug somewhere along the line.

**Comment by jeremygurr** [comment]
fixed.
