### ISSUE TITLE
Use vanilla movement in Abyss

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#592]
Abyss is a special branch, it is full of OOD monsters by design and player is expected to run away from most of them, there are not enough scrolls of teleportation.
So I suggest to use vanilla movement there (1.0). Not sure about Centaur/Felid/Spriggan, maybe they should use 1.0 movement too since they still can use Quick mode if needed.

**Comment by jeremygurr** [comment]
I see the problem. Your solution though is a significant change from how the rest of the game is played, which can throw off players that don't expect to be able to run away without quick mode. I think it would be better to either make less of them, or make them weaker.  Changing the spawn rates would be easiest. 

Oh I have another idea. I never liked the idea of items spawning in abyss, because it creates a temptation to item scum. What if instead of normal items, the abyss only spawned stamina potions. That would make it much easier to stay in quick mode a lot of the time. However, we don't want to spawn so many stamina potions that the player could stay in quick mode all of the time, or even use the abyss for stamina potion scumming. We'd have to get that balance right.

**Comment by Sandman25DCSS** [comment]
What about mummies and Ru characters who sacrificed ability to drink potions?

**Comment by jeremygurr** [comment]
For mummies, I want to just give them high stamina regen (to replace the broken "hungerless" mutation they have now). Basically I can crank their stamina regen to the point that they gain 2 points per turn, making them able to run close to 3x further than normal. The beauty of this approach is that it doesn't make them able to use power or focus mode infinitely because an axe swing that takes 4 SP in normal mode takes 8 SP in power mode, so they will still run out. Or a spell that costs 5 MP in normal mode (the minimum possible) will cost 10 MP in power mode. This _still_ makes things a challenge for a mummy in abyss, but possibly doable.

The Ru case on the other hand I have little sympathy for. If they are willing to make such a huge sacrifice to sacrifice potions, then they get the consequences. 

This should probably be combined with a slight reduction to spawning rates in general in the abyss.

**Comment by Sandman25DCSS** [comment]
Yes, it can work, let's find out ;)

**Comment by jeremygurr** [comment]
Done. We may well need to tweak potion count, spawn rate, etc. But here's a starting point.

**Comment by Sandman25DCSS** [comment]
It does not work, I still spend 1.2 turn per tile (I have hat of poundering also).

**Comment by Sandman25DCSS** [comment]
Also autorest should not happen in Abyss IMHO

**Comment by jeremygurr** [comment]
Autorest is already disabled for abyss. Is it happening?

**Comment by jeremygurr** [comment]
What doesn't work?

**Comment by Sandman25DCSS** [comment]
Now I am not sure if autorest works or not. I got the rune so I don't want to enter Abyss again to check it.

> What doesn't work?

I spent 1.2 turn per tile in Abyss like in all other branches. With vanilla movement it would be 1.1 (1.0 + 0.1 penalty for hat of pondering).

Feel free to copy game file and test it http://crawl.homedns.org/morgue/SlowThinker/SlowThinker.txt, I am in Depths so it is easy to enter Abyss.

**Comment by jeremygurr** [comment]
I never intended to make it move like vanilla. As discussed in this issue, the resolution was to make more stamina potions happen in vanilla to make up for it to some degree. I also reduced the spawn rate in abyss. Is that not enough?

**Comment by Sandman25DCSS** [comment]
It is strange. With stamina potions it is too easy because you are faster than monsters, without stamina potions it is too hard because you are slower than monsters. Vanilla was more interesting IMHO

**Comment by jeremygurr** [comment]
I just took 3 different of characters to the abyss to test things out. It was very difficult. Stamina potions would buy some time to help escape a situation, but they would run out quickly. And many of the monsters in the abyss are designed to even give spriggans at full speed a hard time, so speed doesn't help nearly as much as one would think. 

If anything, abyss is too hard straight across the board. I don't see any case where it is too easy. I even tried a spriggan in challenge mode, which has more effiicient stamina use and moves very quickly, and even then it wasn't easy by any stretch. I still couldn't manage to escape alive. 

I think I will make quick mode cost 1 less sp, Then at least the stamina potions will last slightly longer. Maybe I should turn the spawn rate down a little more too.

**Comment by Sandman25DCSS** [comment]
I meant too easy when you have 0.9 turn per move and monsters have 1.0 turn per move.
I am not sure why you want to change spawn rate again, I think a better solution would be to restore vanilla movement there. I imagine it is not fun to quaff potions of stamina every 20+ turns especially since quaffing takes a turn which compensates previous 10 turns of fast movement.
There are 3 basic ways to manage Abyss: 
1) Be stealthy and run away 
2) Be powerful and silent
3) Be powerful and noisy.
CA movement allows just third way since slow movement means you won't be able to run away and will be swarmed with monsters even if you are powerful.

**Comment by jeremygurr** [comment]
The problem is that it's changing the rules on the player, who has built their character around certain behaviors and expectations. When a player gets to the abyss, they will expect to be able to switch to quick mode as needed, and they will expect to be slower than most monsters. If that suddenly doesn't happen, there's a problem. 

As far as being faster than monsters being too easy, if that were true, then being a spriggan in the abyss in vanilla would be a breeze, right? Or a centaur. Both of which can move quite a bit faster than 0.9 of quick mode. In CA, they both have a significant challenge since they can't stay at their top speed indefinitely. I don't think that's a bad thing, and balanced right, it adds a lot more interest than vanilla had. I find it challenging even if I _could_ stay in quick mode the entire time. 

Bringing the spawn rate down a bit helps to balance out how overwhelmed a character can get. It's an effective balancing tool in this situation I think. This is exactly the strategy that vanilla uses in the abyss to compensate for slower characters. 

As far as being stealthy in the abyss, that seems to work just fine here, from the tests I've done. Stealthiness helps significantly to keep the mobs down in the abyss. So I'm not sure why you are saying that this isn't an option for surviving the abyss. 

I just tried a level 18 felid with blade hands and high stealth in abyss 1. I chopped up a few things that got in my way, but didn't need to even use quick mode most of the time.  I was able to escape without too much difficulty. I might have made it too easy. If so, it's easy to fix. 

Try it a few times and see.

**Comment by Sandman25DCSS** [comment]
> When a player gets to the abyss, they will expect to be able to switch to quick mode as needed, and they will expect to be slower than most monsters. 

I think it is ok. Players get lots of warnings anyway "Beware you cannot shaft on this leve;", "Beware you will not be able to return immediately", warning about being unable to leave Zot without orb etc. Even in vanilla Abyss is unique, what is good in Dungeon is often bad in Abyss and vice versa.

> As far as being faster than monsters being too easy, if that were true, then being a spriggan in the abyss in vanilla would be a breeze, right? 

Right. Abyssal rune is standard third rune for Sp in vanilla.

> I find it challenging even if I could stay in quick mode the entire time. 

Well, I find it too easy for Spriggan, Felid and Centaur in vanilla. [Just yesterday I unintentionally got Abyssal rune as Felid (was banished by Zot trap to Abyss 5)](http://crawl.berotato.org/crawl/morgue//Sandman25/morgue-Sandman25-20160530-005106.txt).
In CA I did Abyss with several characters (including one without quick mode) so I can compare the two.

> Bringing the spawn rate down a bit helps to balance out how overwhelmed a character can get. It's an effective balancing tool in this situation I think. This is exactly the strategy that vanilla uses in the abyss to compensate for slower characters. 

Do you mean that Chei halves spawn rate and  halves walking speed? Reducing vanilla spawn rate by 10%might be good indeed, but no more than that. It should not be a cake walk.

> As far as being stealthy in the abyss, that seems to work just fine here, from the tests I've done. Stealthiness helps significantly to keep the mobs down in the abyss. So I'm not sure why you are saying that this isn't an option for surviving the abyss. 

Because monster HD is increased with runes and stealth is dependent on monster HD. Also sometimes monsters notice you no matter what and while in vanilla I can just keep walking until the monster "forgets" about me, it CA I need to fight or use consumable (no, potions of stamina not always help, you can be a mummy or in lichform).
