### ISSUE TITLE
There is no PC HP penalty

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#593]
It looks like I don't have HP penalty on nightmare. 229 HP is about what I would have in vanilla for XL 25 Centaur with 27 Fighting. 
http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt

**Comment by Sandman25DCSS** [comment]
Or more likely that the penalty is present but is not 33%. As far as I remember Ce has 273 HP max in vanilla.

**Comment by jeremygurr** [comment]
I tempered the pool differences between difficulty levels, since it is such an important balancing factor, and the other differences are enough to produce the difficulty necessary. So standard now has 100% hp, challenge has 90% hp, nightmare has 80% hp (and mp and sp). Easy mode has 150% hp, because it's more for a new player to learn how the game works, but still have something a little more exciting than explore mode.

**Comment by Sandman25DCSS** [comment]
Ok, good to know.
