### ISSUE TITLE
Interruption on stairs might need some tweaking.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#60]
It's nearly impossible to escape a bad situation if you are surrounded on stairs. I don't necessarily disagree with the idea of making it harder, but it seems like it could use a bit of tweaking. It seems like monsters get an almost guaranteed hit on stairs and thus a guaranteed interruption.

**Comment by Sandman25DCSS** [comment]
This happens because EV is reduced significantly while ascending/descending. Also it is possible to be stopped by a melee-only monster which was 2 tiles away when you started using stairs because it takes 2 turns to ascend/descend.
Interaction with Torment and other ranged attacks is fun too :)
Personally I don't mind so probably it should depend on mode, hard one can keep current behavior.

**Comment by G0rg0** [comment]
Leaving current behavior on hard mode makes total sense. Perhaps changing the EV reduction in normal mode and disabling it entirely in easy mode?

**Comment by jeremygurr** [comment]
I'm good with that.

**Comment by jeremygurr** [comment]
Done.
