### ISSUE TITLE
Give slow after berserk ends

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#607]
See title

**Comment by jeremygurr** [comment]
Players are already slow after berserk ends because they have no stamina. Oh, I don't have exhaustion working right there. I'll fix that. It's worse than slow then, since they have reduced movement speed, attack speed, damage, accuracy etc. It's not as slow as the slow status makes the player, but it's still pretty bad.

**Comment by Sandman25DCSS** [comment]
Currently it is always optimal to berserk at 50% stamina because you will be less time in exh status vs a group of monsters. On nightmare I can do 20 attacks in normal mode after getting to 50% stamina and it is usually not enough to kill a group of monsters.

**Comment by jeremygurr** [comment]
I'm not sure what you are saying. 

I can make it just take away 50% sp to berserk, so that it is no more optimal to do it at 50% than 100%.

**Comment by Sandman25DCSS** [comment]
I am saying that if I cannot kill monsters while staying at positive stamina, I should berserk because this way I will lose less HP and will kill them faster. There is no extra penalty for berserk, it doe snot matter if I berserked or not when I am at 0 stamina anyway.
