### ISSUE TITLE
Too low HP

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#616]
I was surprised to have just 134 HP as XL 19 Ogre with 18.8 levels in Fighting on nightmare so I checked vanilla. The same character would have 214 HP, so I have only 62% HP of vanilla character.

**Comment by jeremygurr** [comment]
Fighting no longer gives HP bonuses. That's your raw hp boost from experience and species apt alone. Adjusted for difficulty of course.

**Comment by jeremygurr** [comment]
Maybe I should increase base hp since fighting doesn't add to it any more?

**Comment by jeremygurr** [comment]
Although if I do that I have a feeling you'll say that late game ogre is OP because they have way too much health :p

Let's do a test: 
level 25 vanilla ogre: 145 base, +30% hp apt = 189. Add fighting level 20: +65 = 254. 
level 35 ca ogre (typical late game ogre): 200. +50% hp apt = 300. Adjust for nightmare: 240.

That's actually pretty close for late game stats. And that's in nightmare mode. Challenge would be 270.

**Comment by Sandman25DCSS** [comment]
What is the reason behind removing HP boost from fighting? It was very nice to see some players win with [tiny HP ](http://crawl.xtahua.com/crawl/morgue/Yermak/morgue-Yermak-20160522-164503.txt) while all other players had an extra decision.

**Comment by Sandman25DCSS** [comment]
If there is too much XP in the game, I suggest to reduce number of floors in each branch. Also I think level 35 is fine because it means player has 10+ runes and will get huge penalties for monster damage/HP.

**Comment by jeremygurr** [comment]
I don't think there's too much XP in the game. I was just comparing late game characters. Yes that is part of the reason I removed the level caps, so that players have a way to deal with the rune curses. 

HP boost from fighting doesn't make sense to me since we no longer have mp boost from spellcasting. I find it easier to balance things with more rigid pool sizes (hence the fixed mp and sp pools). Fighting also has plenty of reason to be trained now that it helps sp costs for fighters. 

But I'm happy to increase the hp straight across the board if it feels to be far off from where it should be for a given difficulty level.

**Comment by Sandman25DCSS** [comment]
I don't see why you don't allow player to make decisions about their HP but allow decisions about AC/EV which is basically the same thing before extended. Let's freeze AC/EV and give +N AC and +M EV on every levelup depending on species and difficulty (joke).
Currently Fighting is useless for casters and many hybrids.

**Comment by jeremygurr** [comment]
A few points of fighting at least is critical for casters, more so for hybrids, since they burn all of their stamina quickly otherwise, and can't easily gain strength to make up for it. 

It'd better to limit how much max hp can move outside of known parameters. A player can control hp by limiting damage in a variety of ways, just like they can control mp and sp by reducing their costs. 

Why is it so important that you be able to put points into expanding hp? How does this accomplish our game objectives? It is true that it provides a meaningful choice to the player, but in this case the cost isn't worth the gain. If I recall correctly, one of your biggest arguments against removing the level 27 cap was that players would have ridiculous amounts of hp in extended game. Allowing fighting to further extend their hp contributes to that problem. 

If the problem is that you don't have enough hp, that is easily remedied in several other non-game-balance breaking ways.

**Comment by Sandman25DCSS** [comment]
> A few points of fighting at least is critical for casters, more so for hybrids, since they burn all of their stamina quickly otherwise, and can't easily gain strength to make up for it. 

I stopped training fighting as soon as I learned it does not increase HP and yet it costs me just 2 SP to attack with broad axe with fighting 7 (I am with Chei so have about Str 28). So it looks like training Fighting is as bad as training weapon beyond required level to reach min delay, there are usually much better skills to train.

> Why is it so important that you be able to put points into expanding hp? 

Because it allows to play the same character in different ways. I notice many new players in vanilla go for Fire Storm as Deep Elf with almost zero Fighting, such characters (glass cannons) really differ from Deep Elves who have respectable Fighting and use Bolt of Fire instead.

> If I recall correctly, one of your biggest arguments against removing the level 27 cap was that players would have ridiculous amounts of hp in extended game. 

fixit_friend suggested a very good solution for that, [HP increase should change after XL 27](https://github.com/jeremygurr/dcssca/issues/579). And yes, I still don't like removal of 27 cap.

> If the problem is that you don't have enough hp, that is easily remedied in several other non-game-balance breaking ways. 

The problem is that I have no way of gaining HP. In vanilla you basically never reach Fighting 27 in 3-rune game so you always have the option to get more HP if you want.

**Comment by Sandman25DCSS** [comment]
How about removing Fighting skill since it no longer gives HP? You might use XL instead of Fighting everywhere Fighting is currently used.
I find it very bad that I have 149 HP as XL 27 Naga on nightmare. Vanilla crawl would have about 299 HP Naga, that would be 239 (299 x 0.8) on nightmare.

**Comment by jeremygurr** [comment]
I believe fighting increases damage with weapons and possibly attack speed? But more importantly it reduces stamina cost with heavier weapons. 

I will increase hp growth to compensate if you feel that this nerf is too much.

**Comment by Sandman25DCSS** [comment]
Fighting does not increase attack speed, just damage from melee.
Yes, it is much better now, thank you. Still less HP than in vanilla but I guess this is intended.
