### ISSUE TITLE
Too cheap spells

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#620]
I am Naga before Lair and my spells cost too few MP (I have 80 MP on nightmare as Naga)

```
Your Spells                      Power Range      Fail Level MP  Type
 a - Cure Poison                  56    N/A        1%   2     2   Poison
 b - Olgreb's Toxic Radiance      56    N/A        7%   4     4   Poison
 c + Ignite Poison                31    N/A        7%   3     3   Fire/Transmutation/Poison
 d - Fireball                     39    @---->     24%  5     5   Conjuration/Fire
 m - Mephitic Cloud               35    @--->      5%   3     3   Conjuration/Poison/Air
 z - Sting                        52    @----->    1%   1     2   Conjuration/Poison
```

**Comment by jeremygurr** [comment]
I lowered the spell cost because people were complaining that the sp and mp ran out too quickly. So reducing the cost is effectively the same as increasing the pool size. Wait, are you a naga of chei? If so you shouldn't be terribly surprised. I think it's reasonable that chei characters would be able to cast more spells before having to run away, since they can't really run away at all.

**Comment by Sandman25DCSS** [comment]
Those costs are really close to spell levels so it is like vanilla crawl except I start with 80 MP instead of 6.

**Comment by yrmvgh** [comment]
If casting got made too easy, gorgo can't be far away. :wink: Though there was also a thing where everyone on IRC was saying it takes too long to get your SP back from resting, so costs were slashed in half as a form of solution to that - spells may have been affected?

**Comment by jeremygurr** [comment]
I'm happy to take the costs back up, but people need to make up their mind :)  

It's not the whole story to just compare early game casting here to vanilla, since late game is dramatically different. Late game here your level 9 spells will cost 30 points and you'll still only have that 80 mp capacity. 

Not only that but with high intelligence and spellcasting skills your costs are dramatically reduced, which is obviously not the case in vanilla. Very different experience. What matters is how it actually plays out.

**Comment by Sandman25DCSS** [comment]
> Late game here your level 9 spells will cost 30 points and you'll still only have that 80 mp capacity. 

It means nobody is going for level 9 spells... unless it is a player who does not know the cost in advance which is basically everyone except you :)

**Comment by jeremygurr** [comment]
I can cast level 9 spells perfectly fine. They have a high cost, and require a high investment, and they should. They can even be spammed now with almost no real cost since rot was removed (still not sure about that, but we'll try it out).

**Comment by Sandman25DCSS** [comment]
Maybe I misunderstood you then, I thought you can cast the spell just 3 times before you get into exhausted mode. By the way why are there no penalties for "attack speed" of casters in exhausted mode? Shouldn't it take more than 1 turn to cast a spell similarly to how melee/ranged characters suffer?

**Comment by G0rg0** [comment]
Things have spiraled a bit out of control on this whole issue to be honest. I believe it started because casters were at a huge disadvantage from the reduced ability to lure/kite. 

Melee chars were able to just keep swinging but casters were dead in the water. A lot of the changes since then have been an attempt to balance things out so that a pure casters aren't at a huge disadvantage to melee/hybrid builds. The way I see it, melee should be a a fair bit easier to get off the ground early, casting and melee should start to equal out in the mid game and casters be a bit more powerful in the end game.

Maybe we need to take a step back and come up with a new solution?

**Comment by jeremygurr** [comment]
There are the same attack speed penalties for casters. It actually applies to all modes, just like fighters. In other words, casters can cast spells slightly faster in power mode than normal.
