### ISSUE TITLE
Make Focus bonus additive instead of multiplicative

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#628]
It does not feel right when I have AC 38 in normal mode and AC 48 in focus mode. Some characters (read Ogre) have awful defense and they get insignificant bonus to both AC and EV. So difference between weak and powerful (defense-wise) characters increases.

**Comment by jeremygurr** [comment]
I mix in an additive amount and a multiplicative one, so that both low end and high end gets a noticable boost. Otherwise we lose the choice for one side or the other. In this case you are saying that the focus defense gain for ogres is insignificant, therefore my additive component is too small. 

Ok now a base ogre with ac / ev / sh of 2 / 6 / 7  becomes  4 / 10 / 11 in focus mode.
