### ISSUE TITLE
Everyone should be a hybrid? Chei too strong?

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#629]
Not sure if it is intended but hybrids are much more powerful than other characters. My Naga can use 80 MP to cast spells while still keeping its huge stamina pool (176 on nightmare) at full capacity. After running out of MP it just switches to melee. When it runs out of stamina it has some MP regenerated so it can cast spells again etc. I am basically never in exhausted mode.

**Comment by jeremygurr** [comment]
Yes hybrids are more powerful, because of their ability to use multiple resources. Hybrids are also significantly more powerful in vanilla, since you can switch to melee easily enough if your spells are low. Hybrids are significantly harder to pull off in CA though, because a spellcaster with low strength and nonexistent fighting skills can't just pick up a mace and start bashing an enemy without quickly becoming exhausted. This is intended, and realistic. And I think it adds greater meaning to the choice of whether a player wants to specialize, or attempt a hybrid. Hybrids _should_ be significantly harder to pull off in any game, since they have much greater flexibility than specialists do.

Now a case could be made that nagas have too big of an SP pool. However, they also have a crippling slowness, so the sp pool is intended to partially make up for that. But I'll take the sp pool size down a notch anyway for nagas.

**Comment by Sandman25DCSS** [comment]
I guess we should remove Chei then, it makes hybrids very easy. Or maybe we need to invent another downside for him, not being able to run away is not enough now when you have great weapon attack (Str), great spell power (Int), great spell failure (Dex) and use 2 resources instead of just one.

**Comment by G0rg0** [comment]
As I mentioned in the "too cheap spells" issue (https://github.com/jeremygurr/dcssca/issues/620#issuecomment-221017558) I think there is an underlying problem that needs to be addressed.

The initial goal of removing/reducing the whole kiting/luring/stair dancing mechanic (which _is_ a problem) led to a number of incremental changes which has put things in a bit of a broken state. 

The larger initial MP pool, allowing casting/attacking past zero MP etc. all came from the fact that melee chars could stand and fight while casters are _forced_ to run away once they have no MP, and running away is a lot harder with the base changes to movement.

Again, I don't have an easy solution but I can say that casting when you have no mana does feel wrong (even though it was my idea in the first place). My thinking at the time was: if you are a caster, about to die, out of desperation you would somehow pull from your "ultimate" reserves (loss of max MP/HP/Stat loss) to cast anyway. 

Maybe we should go back to the drawing board?

**Comment by Sandman25DCSS** [comment]
The most interesting thing is that casters actually can easily run away at 0 MP now because they still have full stamina pool. So they don't need to be able to cast at 0 MP. If they don't want to run, don't want to melee, don't want to tele or use other consumable, they deserve to die. Caster should not mean spamming level 9 spell or invincible.

**Comment by G0rg0** [comment]
I agree but having to run away after _every_ fight makes it insanely tedious. If we could just reduce the amount of time you have to run and fully recharge it would go a long way. 

As an example - I was having to run to stairs, hope I could escape up, and fully recharge after _every single individual_ orc in a pack. Was it possible? Yes, barely. Completely tedious and annoying? Very much so.

**Comment by Sandman25DCSS** [comment]
Running away at 0 MP is good for caster, otherwise it is just a ranged attacker like hunter. Obviously something is wrong with MP cost or spell power if you need to do it after every orc (in Orcish Mines and not on D2 I suppose).

**Comment by Sandman25DCSS** [comment]
Oh, I would actually have less stamina without my SP+3 item.
