### ISSUE TITLE
wand of heal wounds isn't good for much

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#63]
Hmm, wand of heal wounds has been a tough problem to solve. In old crawl it is way too easily abused. And most of my attempts to fix it have failed. Maybe it should be changed into something entirely different. Right now, it's main purpose in existence is to make deep dwarves playable, but if a species requires one specific item made just for it to be playable, then maybe something is wrong. 

What if it was a wand of regeneration instead, that worked even for dwarves? It could even be used multiple times to stack the effect, but of course costing more charges in the process. Higher evocations power would increase how much the regeneration is per time unit, and multiple uses of it would extend the duration of the regeneration.

**Comment by Sandman25DCSS** [comment]
Also it allows Mummies to heal in emergency otherwise Mummies are identical to Vine Stalkers in this regard.
Regeneration does not help in emergency, it is used for long fights/Hell branches, also to save some piety. Maybe make the wand similar to potion of heal wounds but weaker unless at Evocations 25+?
Something like max(5, min(25, Evocations))*N% max HP where N is 1 for hard, 2 for normal and 4 for easy? The max is to make the wand useful even at Evocations 0, it would heal 5-10-20% for hard/normal/easy. Not very useful but probably still better than potion of curing.

**Comment by Sandman25DCSS** [comment]
Probably that would still be very strong at high Evo since recharging exists. So here are some other ideas (they assume healing does not depend on Evocations):
1) Decrease max charges from 9 to 5 or even 3.
2) Decrease max charges of a wand of heal wounds by 1-3 every time recharging is used so player cannot use a single wand of heal wounds in 15 rune game.
3) Decrease % max HP the wand heals to be 33% of what potion of heal wounds heals since recharging exists and it is impossible to find more than 3 potions of healing in a single stack on floor. Then fully charged wand would be similar to 3 potions (but would still be worse because with potion it takes 1 turn and not 3 turns to heal the same amount of HP)

**Comment by jeremygurr** [comment]
What if we kept the max charges, but didn't allow recharge scrolls to work on heal wounds. Dwarves could still recharge them with their more powerful charging ability (which costs 3 PMP instead of 1). Or when I create amp scrolls, an amped recharge scroll could potentially recharge a heal wand, but at a much higher cost than just a recharge scroll. 

I'd still like them to behave a bit differently than potions. Maybe they always take 2 uninterruptible turns to use, so you could use them in battle, but they are definitely not as safe as a HW potion. Then, like you said healing amount would be in proportion to evocations.

I like the flavor of a wand that loses max charges each time it is recharged. That may be better than just banning recharge scrolls for heal wounds. Say a wand lost 1/3 of it's max charges each time, with a minimum of 1 charge lost. 9 charges -> 6 charges -> 4 charges -> 2 charges -> 1 charge -> wand crumbles into a pile of dust. You could get a maximum of 22 charges out of a wand of 9 charges, spending 4 recharge scrolls. Probably be best not to waste the last two scrolls on just gaining a few charges. I like that. We could also make the dwarf recharge ability work the same way, then I can do away with my other approach there.

So I'd say lets do
- the recharge diminishing thing 
- 2 turn uninterruptible execution
- health recovery based on evocations

**Comment by Sandman25DCSS** [comment]
Sounds good.

**Comment by jeremygurr** [comment]
This was deployed in v1.1
