### ISSUE TITLE
Make spell failure similar to vanilla

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#640]
I compared my current character to vanilla and found that I have 1% failure in vanilla and 45% in CA.
Str 29, Int 36, Dex 36, IDA, Armour 8.4, Conjurations 19, Fire Magic 18.4, Spellcasting 9.5

**Comment by Sandman25DCSS** [comment]
Even if I take the armour off, I have 13%. And even after that I equip ring of wizardry, I have 8%. This is unplayable.

**Comment by jeremygurr** [comment]
Spell failure works very differently here than in vanilla so it is not comparable. Instead we need to detemine what makes a given spell or situation unplayable. I need to know a specific case. I'm testing cases as quickly as I can and fixing things that are too far off, but there are hundreds. 

Blade hands in particular has received a huge nerf (on purpose). There may well be some high level spells that some combos can never bring online. And I'm okay with that. I don't feel a need for all combos to be able to cast any spell. 

Which spell are you needing to work?

**Comment by Sandman25DCSS** [comment]
> Which spell are you needing to work?

Is it important? I believe spells are quite balanced in vanilla, can you just use Dex instead of Int in vanilla formulae for spell failure? I don't see how vanilla formulae being complicated is a bad thing from player's perspective.
I need all spells to work :)

**Comment by Sandman25DCSS** [comment]
And by the way you disabled a play style (Hill Orc in plate armour using Bolt of Fire in 3-rune game).

**Comment by jeremygurr** [comment]
Yes it matters a lot. Spell failure works dramatically differently here and can't even begin to be  compared with vanilla, and any attempts to line them up would break many things. Spells being balanced in vanilla does nothing for us here, since we have focus mode and spell cost to factor in as well, as well as spell hunger working completely differently, and the fact that spell caps are gone, throwing everything off from how vanilla balances things. 

I have tested several different spell strategies so far, and gotten them to work just fine. So if there are some strategies that don't, I need to know about them to be able to get them balanced right.

Yes you can't play a hill orc with fire bolt in plate armour here as easily. You could do it with Chei, or with some significant enhancers (maybe a couple of wizardry rings). I don't think that's necessarily a bad thing, since you really shouldn't be able to cast a level 6 spell with heavy armour without going to extreme lengths. That being said, I have a HOFE at level 24 here, which can pull off a level 5 (fireball) quite comfortably in heavy armour (17% failure) without any enhancers. So a powerful spellcaster in plate armour is still doable as a HO, just not quite as powerful. Also keep in mind that even low level spells, which can easily be pulled off even in heavy armour are uncapped, and can do significant amounts of damage later in the game.

**Comment by Sandman25DCSS** [comment]
I don't see how stamina or MP costs are important when spells are uncastable. Am I supposed to be able to cast spells in focus mode only? I still believe characters should be balanced in normal mode and focus/power mode can give just a small bonus (less than 10%). I don't like current state, it's unplayable. Vanilla is much better is this regard, sorry.

**Comment by Sandman25DCSS** [comment]
17% for Fireball is unplayable.

**Comment by jeremygurr** [comment]
MP costs are important because they affect the balance of spells, and which would be chosen for a given situation. 

Yes it is expected that if you want to push the limits of a character (trying to cast in heavy armour for example) that you would need to be in focus mode much of the time. Then once you train enough that failure rate is lower, you can switch to power or normal mode. 

Why is 17% fireball unplayable? It doesn't even have any miscast effects. Is an executioner axe unplayable because you miss 20% of the time? I'm not understanding where you are coming from here. 

Normal mode is quite playable, but it shouldn't be expected to be exactly the same as vanilla. There are things you can do in vanilla that you can't do here. And there are many times more things that you can do here that you can't do in vanilla. It's quite a different game, and needs to be played from that perspective. It seems like people spend so much time complaining about one specific strategy that they can no longer effectively use here, that they miss out on the discovery of many new strategies that are only possible here, many of which are a lot more fun and a lot more deep than the particular strategy that they have lost.

**Comment by Sandman25DCSS** [comment]
> MP costs are important because they affect the balance of spells, and which would be chosen for a given situation. 

I was talking about situation when spell is uncastable. Currently MP costs are very low and you seem to "fix" it via spell failure changes resulting in "cure worse than disease" situation

> Yes it is expected that if you want to push the limits of a character (trying to cast in heavy armour for example) that you would need to be in focus mode much of the time. Then once you train enough that failure rate is lower, you can switch to power or normal mode. 

I have 19-20 spell levels in Conj/Fire and medium armour with huge Str/Int/Dex and still get 45% (red miscast) for Bolt of Fire (level 6). Compare to [best score of TeCK](http://crawl.berotato.org/crawl/morgue//agentgt/morgue-agentgt-20150924-142110.txt) which has 2% for Controlled Blink (level 7) while having just 18.9 levels in Transloc and Int 16.

> Why is 17% fireball unplayable? It doesn't even have any miscast effects. Is an executioner axe unplayable because you miss 20% of the time? I'm not understanding where you are coming from here. 

Oh, now I see where you are coming from. We cannot treat miscasts as misses because you still spend MP with miscast. Melee character does not care much if it misses, all it loses is just time. Caster loses MP making it much weaker. Miscast is a disaster, that's why all players try to get it as low as possible unless they are hybrids and/or have huge defense. Also you can notice that if you have 20% miscast and 30% chance to miss, your effective accuracy is just 56% (0.8x0.7).

> Normal mode is quite playable, but it shouldn't be expected to be exactly the same as vanilla. There are things you can do in vanilla that you can't do here. And there are many times more things that you can do here that you can't do in vanilla. It's quite a different game, and needs to be played from that perspective. It seems like people spend so much time complaining about one specific strategy that they can no longer effectively use here, that they miss out on the discovery of many new strategies that are only possible here, many of which are a lot more fun and a lot more deep than the particular strategy that they have lost. 

See OP, 45% makes normal mode unplayable for that character. And focus mode is unplayable too because I have just 80 MP and paying double cost is unacceptable (6 bolts of fire with 23% miscast is much worse than 16 Fireballs with tiny miscast). Yes, I keep complaining about missing strategies because it is impossible to avoid situations when you must fight in normal mode so normal mode should be playable too. If you don't want to make it playable, remove it to make it obvious. So only power/focus modes exist and when stamina/MP end, you get exhausted status. Oh, wait, it already works this way. So yes, normal mode is not expected to be playable, it's just a kind of power mode when you save MP/SP and pay with decreased everything for that.

Have you checked what is required to cast level 9 spells in normal mode?

**Comment by Sandman25DCSS** [comment]
So again, here is my suggestion:
1) Decrease bonuses/penalties for power/focus/exhausted modes to less than 10%, the game should be playable for player who does not switch modes provided it is a powerful combo and standard difficulty. I am talking about everything here, not just spells-related things.
2) Make switching power/focus/normal mode take no time, it is not fun to autoexplore in power mode just in case you meet an Ancient Lich and then switch back to normal for killing standard monsters and then switch back to power for autoexplore. With switching taking no time I would autoexplore with normal and wouldn't need to switch as often.
3) Use vanilla formulae for spell failure/power, they are good because they have been balanced for years. Using Dex for spell failure is fine, though probably it could use average of Int and Dex. Use vanilla MP costs for spells and MP pool too, they are good because they have been balanced for years. It can take literally years for you to achieve good balance with new system and I suspect you will find it pretty close to vanilla.

**Comment by Sandman25DCSS** [comment]
My Naga gets AC from 46 to 58 and EV from 21 to 26 in focus mode, I can imagine that if I were a Summoner, I would create some summons and then switch to focus mode for staying in one place and watching enemy die, the point is to prove that bonuses/penalties should be small.

**Comment by jeremygurr** [comment]
I was considering removing the time cost of switching modes anyway, so it's nice to see that you want that too. 

I can't decrease bonuses without also taking away the strategic value of the different modes. But I am open to an option that makes the game basically function without them, for those who really don't like them. 

Vanilla failure and power will never work here. Removing the spell caps alone broken any weakly held balance vanilla may have had. Add to that the other huge changes, and trying to maintain any balance based on how vanilla does it is a joke. Yes vanilla's balance is weak at best since you clearly have very overpowered spellcasting combos and strategies that can easily be achieved. 

I'm taking this game to places vanilla has never been, and probably will never go. That can't happen while chained to a system that is very broken in the current paradigm. Yes, it will take considerable time to balance and get everything right, but I'm not in any competition or race and I don't have any deadlines, so it doesn't really bother me that it's not going to have every aspect of the spellcasting system (or any other part of the game for that matter) balanced anytime soon. 

Melee characters lose just as much as spellcasters do when missing, since they have to pay the SP cost either way. So I'm not sure what you mean by "Melee character does not care much if it misses, all it loses is just time"

Yes using focus mode for a character and just hiding while your summons do the work is a viable strategy. I don't see any problem with that. It's not a no-brainer though because often you'd be better off in power mode or even normal mode helping your summons out. If the modes didn't provide new and different ways to tackle  a problem, they would be worthless.

**Comment by jeremygurr** [comment]
That being said, Level 6 spells do seem too hard. I'll work on that.

**Comment by Sandman25DCSS** [comment]
> But I am open to an option that makes the game basically function without them, for those who really don't like them.

That would be great, I hope it is not hard to implement/support.

I don't see why removal of spell power cap should affect fail rates or anything else, for example, my character from OP still has all spells under 200 spell power even with 2 enhancers. If you want to nerf 200+ spell power, there are direct ways to do it without affecting most characters who don't reach 200 spell power anyway. Currently the game is still similar to vanilla, even with 9 runes.

**Comment by jeremygurr** [comment]
One way it could be done, is to keep Quick mode, and have it function like normal, but eliminate power and focus mode, and instead make normal mode have normal properties, only slightly adjusted for difficulty. 

Removing the spell power cap throws the balance way off because then with a single level 1 spell a player can dominate lair, for example, among many other issues. Oh I see what you mean. Yeah getting past 200 spell power isn't a big deal. It's the removal of a 40 spellpower cap that an individual spell may have that I'm referring to.

**Comment by Sandman25DCSS** [comment]
Is it hard to add an option to keep spell caps for individual spells (like 25 for Magic Dart)? It assumes the power caps are still in code of course.

**Comment by Sandman25DCSS** [comment]
Also this specific character has problems casting spells which have spell power 200 in vanilla (Bolt of Fire, Dispel Undead, Necromutation) so again buffing low level spells should not affect them.
The character used just a single spell with spell power cap (Sting) and of course it stopped using it.
http://crawl.homedns.org/morgue/SlowThinker/SlowThinker.txt

**Comment by jeremygurr** [comment]
it would be pretty difficult to make spell power caps have any kind of meaning in the current situation. Spell power works quite differently, and there are many other factors. It would just break more things, not bring any kind of balance.

Would it work for you to just have quick mode, and the other exertion modes disabled as described above? It wouldn't be hard to implement that.

**Comment by Sandman25DCSS** [comment]
> it would be pretty difficult to make spell power caps have any kind of meaning in the current situation. Spell power works quite differently, and there are many other factors. It would just break more things, not bring any kind of balance.

Really? I checked spell power for my Naga many times during this game, it was always close to vanilla (slightly less than vanilla in normal mode).

> Would it work for you to just have quick mode, and the other exertion modes disabled as described above? It wouldn't be hard to implement that.

Yes, I would love it, thank you. I assume AC/EV are vanilla ones here and I can melee things indefinitely without getting exhausted because stamina is used in quick mode only.

**Comment by jeremygurr** [comment]
Try this: exertion_disabled=true

**Comment by Sandman25DCSS** [comment]
Thank you

**Comment by Sandman25DCSS** [comment]
Reopening since level 8 Necromancy spell is barely castable (10%) with wizardry without body armour with Dex 38, 24.9 Necromancy and 20.4 Spellcasting. 
http://crawl.homedns.org/morgue/SlowThinker/SlowThinker.txt
26% (light red) without wizardry, 55% (red) in IDA with Str 29 and Armour 8.5. 
No, this is not ok because it means no character can ever cast level 9 spell.

**Comment by jeremygurr** [comment]
I was trying to push level 9 spells to a little later in the game, allowing the player to enjoy more fully the mid level spells, before moving on. That means you wouldn't typically get to pull off level 9 spells easily until you were closer to level 30. If you gain power to cast your level 9 spells easily by xl 23, then what do you have to aim for over the next 7-10 levels? 

However you are playing without focus mode, so I will make the code adapt for that. I also reduced the armour penalty a bit. So things will still be more difficult than what you are used to, but not quite so crazy as before.

**Comment by jeremygurr** [comment]
Deployed.

**Comment by Sandman25DCSS** [comment]
Well, something is weird. Now I have somewhat better fail rate in IDA without wizardry (42% instead of 55%) and with wizardry (25% instead of 26%) but without armour and with wizardy the chance got worse (12% instead of 10%). I still think that level 9 spells will be uncastable. Or it is expected on nightmare?

**Comment by Sandman25DCSS** [comment]
Oh, I actually can buy Fire Storm. It is 82% in IDA (Conj 19, Fire 18.4, Spellcasting 20.4, Dex 44), 71% with wizardry, 43% without armour and with wizardry.
Maybe explicitly describe that level 9 spells cannot be casted on nightmare so players won't waste XP?

**Comment by Sandman25DCSS** [comment]
The only way I was able to cast level 8 spell was via quaffing might, agility and brilliance.

I don't know if you used level 9 spells in extended but having them there does not mean that you have easy time, it is still possible to die easily. Fire Storm trivializes Vaults 1-3 but extended still can kill easily in vanilla. In CA it is even worse since you have lower HP but monsters have higher HP and higher damage.

**Comment by Sandman25DCSS** [comment]
I mean I think it should not be your goal to make level 9 spells unreachable before XL 30.
