### ISSUE TITLE
Too easy early game for Tm

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#653]
I haven't trained Transmutations as OpTm on nightmare and yet I have Spider Form at 18% immediately after reaching XL 3. Also it is a no-brainer to put bonus stat points into Dex since it improves both fail chance and EV. I just don't need Int with the way CA works.

**Comment by jeremygurr** [comment]
You need int for spellpower and lower costs. This may not be as big of a deal with transmuters, since currently power is only used for ac boosts and hydra heads. So if you skip over ice form and hydra form, you can probably ignore power almost entirely, allowing you to put all points into dex. But that is still a significant choice. Especially in the case of an octopode where their int is decent to start with anyway. 

It seems right that you should have a fairly easy time with low level spell failures with that setup. Spider form is unique in that it boosts your dex also, reducing failure significantly. So staying in the form is much easier than some of the others. Blade hands, however, does the opposite, and makes it considerably harder to keep online for very long without investing heavily in spellcasting and transmutations. 

I can increase the low skill penalty a little though.

**Comment by Sandman25DCSS** [comment]
Ice Form's AC bonus does not depend on spell power in vanilla. Have you changed it? Or did you mean Ozocubu's Armour?
My intent is to use Ice Form, some top player suggested it can be as good or even better than Blade Hands so I am going to test it. Later I want to switch to Dragon Form and again spell power will be unimportant.
Staying in form is fun, I was pushed out of Spider Form in long fight with Wraiths who drained me heavily deep into red.

> I can increase the low skill penalty a little though. 

I hope it won't affect high level spells, currently they are too hard to cast with disable_exhaustion=true.

**Comment by Sandman25DCSS** [comment]
I edited previous message changing its meaning in the opposite way.

**Comment by jeremygurr** [comment]
I'm talking about AC bonus of ice form being based on spell power, which I haven't changed. Which is one of the only ways in which spell power affects transmutations at this time. 

I see your concerns with the spell failure, and have an idea that might take care of things. Give me 30 minutes to fix...

**Comment by Sandman25DCSS** [comment]
Thank you, this is not urgent, I cannot play until evening anyway.

**Comment by Sandman25DCSS** [comment]
You are right, I forgot that Ice Form's bonus depends on spell power.

**Comment by Sandman25DCSS** [comment]
Not sure if it was deployed, I didn't see significant changes.

**Comment by jeremygurr** [comment]
The exact spot you are at may not appear that different. You will notice quite a difference though as you gain skills. 

Here's a specific example: given a level 8 spell, with 10 spellcasting, 10 spell schools, and 25 dex.

The old way has a fail rate of 27%. In the old way, if you added 5 to dex, you'd take the fail rate down 4 points. But if you added 5 points to spellcasting, you'd take the rate down 8 points. In other words, optimal path would always be to add to the lowest factor, since it had a greater influence on the result. 

The new way, if you added 5 to dex, you'd go down 13 points. If you added 5 to spellcasting, you'd also go down 13 points, if you added 5 to spell schools, you'd also go down 13 points. So you have a little more flexibility on how you want to bring that failure rate down.

**Comment by Sandman25DCSS** [comment]
Thank you for the explanation
