### ISSUE TITLE
Allow all species worship Beogh?

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#654]
What do you think about allowing other species to worship Beogh?

The god's author said:

> I am responsible for Beogh, and I have defended the decision to restrict followers to orcs. It's pure flavour. I assume that's "virtually no reason" but I don't mind.

https://crawl.develz.org/tavern/viewtopic.php?f=17&t=20025&p=270731#p270731

**Comment by jeremygurr** [comment]
The flavor is pretty significant. On the other hand, orcs already have plenty of reason to choose them, and they are quite powerful as is, and so don't need a niche god to encourage people to play it. It would definitely add options to open up Beogh. My only deal is that someone would need to rework the flavor a bit so that it isn't totally inconsistent.

Maybe the flavour could be along the lines of Beogh still considering orcs to be the superior race, but allowing other "lesser" races to serve him in the quest to eliminate all enemies of the orcs. A bit weak, but maybe a starting point.

**Comment by yrmvgh** [comment]
Currently we have three species who can join Bog, that's already a lot more than vanilla!

**Comment by Sandman25DCSS** [comment]
Hill Orc, Lava Orc and ?

**Comment by Sandman25DCSS** [comment]
Ok, no changes then. Thank you.

**Comment by yrmvgh** [comment]
Sludge Elf! I already updated their species select description, but in hindsight no one reads that, so now the readme is updated too

**Comment by Sandman25DCSS** [comment]
Interesting, I'll try Sludge Elf then.
