### ISSUE TITLE
Revert commit and make Weapon skill useful again.

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#674]
Either remove all weapon skills or make them the only factor for attack speed. Current situation is very bad because I can use all weapons at min delay or very close to it. A character with fighting 26 should not have min delay for executioner's axe, bardiche, triple sword, lajatang, great mace.

**Comment by jeremygurr** [comment]
So you are saying that the weapon damage boost and accuracy increase from training weapon skills isn't enough to justify training the skill? Seems like that should still be a good idea, but I can see how speed maybe is more important. 

I'm fine with swapping the two. So weapon skill will contribute to attack speed reduction, and not damage, and fighting will affect damage increases, but not weapon skill. Accuracy will still come from weapon skill, like before. 

To keep things symmetric, I would make spellcasting speed come from spell skill (=avg spell schools), and spell damage (=power) come from spellcasting, but not spell skill. Failure will still be affected by spell skill as before. 

Hopefully you read the latest change log and/or commit descriptions and know that you can no longer get attack to min delay with 0 weapons skill, nor can you get spell failure to 1% with 0 spell skill. That will still apply here of course.

**Comment by Sandman25DCSS** [comment]
Sorry, I cannot stop myself from saying again that I don't see why you are breaking perfect vanilla system :( Experimenting is fun but the game should stay balanced and flavourful.

> I'm fine with swapping the two. So weapon skill will contribute to attack speed reduction, and not damage, and fighting will affect damage increases, but not weapon skill. Accuracy will still come from weapon skill, like before. 

It means heavy weapons will have much higher accuracy than light weapons. Also it means light weapon users will never train fighting.

> To keep things symmetric, I would make spellcasting speed come from spell skill (=avg spell schools), and spell damage (=power) come from spellcasting, but not spell skill. Failure will still be affected by spell skill as before.

It means I can get Discord to max spell power by training Spellcasting alone with 0 Hexes. It reminds my current OpTm who has 17% Invisibility with 0 hexes. Ok, I would train Hexes to 8 to get reasonable spell failure for Discord.

> Hopefully you read the latest change log and/or commit descriptions and know that you can no longer get attack to min delay with 0 weapons skill, nor can you get spell failure to 1% with 0 spell skill. That will still apply here of course. 

Thank you, I have just read. Now CA mechanic is more complicated than vanilla because I don't see how player can know about "Minimum failure of level 5 spell with 0 spell school average is 50%".

**Comment by jeremygurr** [comment]
Sorry, the cost of experimenting is that balance may be lost while the kinks are being worked out. But sometimes experimenting results in something better than you started with. Therefore it is worth the risk.

> It means heavy weapons will have much higher accuracy than light weapons. Also it means light weapon users will never train fighting.

I don't understand this. Why would heavy weapons have higher accuracy? Because only players with heavy weapons would train weapon skills? Why? And if it indeed resulted in different combos training different things, I think that is a step in the right direction, because it means there is more meaningful choices available to optimize different fighting styles. If optimal path for all fighters was to train their weapon skill as much as possible down to min delay, and then fighting, then why even give the choice to the player? There is no fun in repeating a pattern that is exactly the same every time and requires no thought or strategy.

> It means I can get Discord to max spell power by training Spellcasting alone with 0 Hexes.

And that is bad? If all you increased was spellcasting, you'd need to train it to level 40 to get 200 spellpower (which is fairly difficult). Or you could train it to 30 and add 10 more points of intelligence. You still need to train the other things if you want decent success rate and spell cost. Discord can be an expensive spell otherwise. 

As far as the minimum failure cap, I made it as simple as it could be to accomplish the purpose. And it's quite easy for a typical crawl player to understand: minimum spell failure is 10% for every (spell level - spell school average) point. Not that complicated. Nowhere near as complicated as the dozen or spoilery things you'd need to know to calculate vanilla spellpower.

**Comment by Sandman25DCSS** [comment]
> Sorry, the cost of experimenting is that balance may be lost while the kinks are being worked out. But sometimes experimenting results in something better than you started with. Therefore it is worth the risk.

Right, but some things don't even need to be tested. Having a single skill to affect attack speed of all weapons is one of them, having spellcasting as useful as average of magic skills is another, having stat points be as useful as average of magic skills is third.

> I don't understand this. Why would heavy weapons have higher accuracy? Because only players with heavy weapons would train weapon skills? Why? 

Because light weapons have too low base damage and rely on additional brand damage mostly.

> If optimal path for all fighters was to train their weapon skill as much as possible down to min delay, and then fighting, then why even give the choice to the player? 

It would be true, if there existed just a single weapon type (not even category). But player picks mornignstar instead of great mace, for example, exactly to save XP for other things. This is a choice, spend huge amount of XP and get an awesome weapon or spend less amount on not so awesome weapon. Weapon categories make the decision even more interesting.

> And that is bad? If all you increased was spellcasting, you'd need to train it to level 40 to get 200 spellpower (which is fairly difficult). 

It is extremely bad. Discord is cast just once, you don't need to spam it so spellcasting speed is irrelevant. Spell power is still a subject of stepdown so max power is not even necessary because it is very hard to get. Also robe of archmagi and power mode exist. An ogre (+1 aptitude in spellcasting) casting Discord in Orc would be hilarious. Add Sif Muna for protection from miscast for double fun: some players cast Dragon Call at 50% failure in vanilla, in CA 50% failure would be with just 4 levels in Summoning if I understand correctly.

> As far as the minimum failure cap, I made it as simple as it could be to accomplish the purpose. 

It proves that current formula for spell failure is bad, it does not work without extra limitations. 
Also what if I get 60 Dex? Does it mean I can get level 9 spells to 10% with just 8 levels in corresponding skills?
