### ISSUE TITLE
Tomb 2 has downstairs to Tomb 3 immediately

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#677]
As you probably know to reach Tomb 3 from Tomb 2 without teleportation players need to return to Tomb 1 first.

> You'll find several doors off to the side of this open chamber, leading to a series of small rooms that envelops half of the map. These will contain mummies, guardians, and priests, as well as many traps. Eventually you'll find a staircase back up to Tomb:1. Go up it to continue exploring normally. Alternatively, at this point it is fairly safe to attempt to skip ahead through random teleportation; doing so lets you avoid one of the more dangerous areas of the Tomb. Keep teleporting (with teleport traps if available or a ring of teleportation) until you find yourself in a new area (see #6). 

http://crawl.chaosforge.org/Tomb

But it is not needed in CA, downstairs to Tomb 3 are accessible immediately.
I paused my game so you can explore it if necessary.
http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt

**Comment by jeremygurr** [comment]
Ok I grabbed your save. I will look at it when I get a chance.

**Comment by Sandman25DCSS** [comment]
Oh, I cannot enter Tomb 3, crash when trying.
http://crawl.homedns.org/morgue/Sandman25/crash-Sandman25-20160528-131814.txt
Nothing urgent, I will switch to vanilla for a while.

**Comment by jeremygurr** [comment]
I looked into it for a while. Unfortunately it seems to be beyond my "quick fix" skill level. I'll eventually sort it out, but unless we can get a des expert to help us out, it may take some time. Someone that understands how des files works well could probably fix it for us fairly quickly, since the tomb.des file isn't that big. 

As far as the tomb 3 requiring going to tomb:1 first, that won't work until we actually add more floors to tomb. Because it's 4 floors now instead of 3, the hard-coded 3 floor mechanisms don't work. The intention is to eventually refine that, but for now to just let the auto-generation code fill in the gaps, which it mostly does pretty well.

**Comment by Sandman25DCSS** [comment]
Can we revert the changes to des file and have it with 3 floors like in vanilla?

**Comment by jeremygurr** [comment]
Nah, that ruins the whole everything is 4 floors simplification. Plus it wouldn't take effect until a new game anyway.

**Comment by jeremygurr** [comment]
fixed. Now the 3 floors are just like vanilla, except with an extra floor added on top, so no mechanic is broken.
