### ISSUE TITLE
Zombie allies can use stairs

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#699]
See title. 
I used Animate Dead on doom hound and it followed me via stairs from Tar:3 to Tar:4

**Comment by jeremygurr** [comment]
Since monsters don't spawn, and monsters can't follow you up the stairs, leaving undead minions behind on an empty floor is meaningless. And since they time out anyway (not sure I want to keep that, but we'll see), it's not too big of a deal for them to follow the player down to the next floor.

**Comment by Sandman25DCSS** [comment]
That's the point of zombies, they help you on current floor only and are meaningless on other floors.

**Comment by Sandman25DCSS** [comment]
It is huge deal to follow you. If you are familiar with crawl history, you can know that some undead could follow you and it was removed as OP.

**Comment by jeremygurr** [comment]
Yes that was back when you could just walk up the stairs and take a few bad guys with you so that the zombies on the floor above you can help finish them off. Of course they'd be OP in that scenario. That scenario doesn't exist here. And zombies stayed forever before also. Here they time out, greatly limiting how OP they can become.

**Comment by Sandman25DCSS** [comment]
No, I meant http://crawl.chaosforge.org/Twisted_Resurrection_(player_spell)

The spell allowed you to create an army on one floor and use it on next floors which was completely broken. CA has similar problem with zombies now that they can use stairs

**Comment by jeremygurr** [comment]
I fail to see how this is any different than having summons follow you between floors. Except that summons are far more powerful since they don't expire. Is it because you can basically animate dead without any long term limits or consequence, unlike summons? If that's the case, then that will be solved soon enough. 

I will eventually shift to necromancy and get the kinks worked out there. I'll probably make it work the same way as summoning, where mp is frozen but they stick around until they die otherwise. Right now I'm concentrating on melee refinement. I reduced spellpower quite a bit with spellcasters, which should help get them closer to proper balance.

**Comment by Sandman25DCSS** [comment]
Last time I tried summons they expired instantly when I entered a new floor with monsters in view.
Summons are not even close, I hope you tried Simulacra + Death Channel + Animate Dead combo.

**Comment by jeremygurr** [comment]
Yeah that's definitely true in the case of arriving in a new floor with monsters there. I will apply the same limitations that summoning has, and that should be much better.

**Comment by Sandman25DCSS** [comment]
I assume you want to automatically expire zombies and I think it is a bad idea. Summoner can summon the creatures again, Necromancer cannot so the difficulty of next floor will be determined by pure luck. I suggest to prevent derived undead from using stairs (unless they are permanent allies from Yred of course), basically how vanilla works.

**Comment by jeremygurr** [comment]
Yeah good point. No I didn't intend to make zombies expire when reaching a floor with monsters in sight. They would just stay behind until the coast is clear. Maybe they could even automatically appear around the player next time they "instarest".

**Comment by Sandman25DCSS** [comment]
I saw a commit about telling to wait to I am closing the issue
