### ISSUE TITLE
potions and scrolls aren't stacking properly, sometimes a single type occupies more than one slot

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#7]

**Comment by Sandman25DCSS** [comment]
Also sometimes weird things happen like equipping ring mail as helmet. 
http://tinypic.com/r/2957i4l/9
I am not sure how it happened, I did have helmet displayed in % screen at previous XL.

**Comment by Sandman25DCSS** [comment]
Oh, I suspect what happened. I use "item_slot += scroll of identify:q" which assigns scrolls of identify to letter q and it looks like that ring mail got assigned to "q" first so when I picked up the scroll, it was swapped with the ring mail which went into wrong category of consumables. Now I get a crash when trying to pickup a scroll of identify.

Edit. Yes, the issue was resolved when I removed all "item_slot +=" from my settings.

**Comment by jeremygurr** [comment]
Fixed. Equipment swapping was happening when consumables were being swapped, creating some weird effects. This can be fixed in existing games by swapping consumables that have the same letters as the confused equipped items, with the old code. Then updating to the latest code will prevent this from happening again.
