### ISSUE TITLE
Guardian spirit should scale with XL

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#710]
I found the amulet and ring of magic power on D2, now I have 28 normal HP and 48 HP from guardian spirit (96 MP), that's on nightmare.

**Comment by jeremygurr** [comment]
I'm not sure about going down the path of XL based items. This changes the nature of the game significantly, making it a lot more diablo like, where everything just scales with your player, and everything gets a lot more boring IMO. I like being able to rarely get overpowered items that make parts of the game much easier, or sometimes not getting powerful items that are sorely needed, making the game a lot harder, and just having to deal with each circumstance randomly as a real roguelike would require. 

For this kind of situation, we could make certain items just not appear too early, but again this messes with the whole XL-agnostic philosophy, but at least it's better than the first case. 

In this case, I think a simpler solution is to change the guardian spirit mechanics to be completely independent of magic pool size. I know this is very different than how it works in vanilla, and I don't particularly care. I think guardian spirit should just cause 1/3 of all damage to be taken from mp (or 1/2 if that's not useful enough to make guardian spirit a valuable choice). It works as a simple magic armour, that's easy to understand and isn't overpowered even if you get it very early game. Yes this means for players with low hp, they don't get as much benefit, and players with high hp will get more benefit, and this certainly changes the strategies involved in those situations. It seems to balance out overall though. 

To make things more interesting, we should have multiple levels of magic-shield, allowing vine stalker in particular to be more distinctly set apart from a normal player wearing the amulet. Level 1 takes 1/3 from mp, level 2 takes 1/2, level 3 takes 2/3. Then maybe we can remove the amulet and make rings and artifacts have the property instead, which can then stack.

**Comment by jeremygurr** [comment]
Ok I've made significant improvements to guardian spirit. It has been renamed to magic shield, to distinguish it from stamina shield (a new amulet). The first level isn't too powerful, only providing 25% damage shaving, which isn't guaranteed since it's randomized (0-50% damage shaving, weighted towards 25%). Vine stalkers, on the other hand, eventually gain level 2 and 3 later in the game, which diverts 50 and 75% of damage from MP. 

The standard amulet only provides the first level of magic shield, but it may be combined with other magic or stamina shield artifact properties, providing some serious auxiliary armour if a player is lucky enough to come across them.

**Comment by Sandman25DCSS** [comment]
Ok, thank you.
