### ISSUE TITLE
Torment damage behaves strangely:

### ISSUE THREAD

**Issue by MattConrad** [jeremygurr/dcssca#727]
I don't have a repro or good details, but torment was doing a lot less damage than it used to.

I had rN++ only, and I could basically ignore torment, it did some damage but I think at most 25% and probably more like 10%. I do remember one message that went:

> You were prevented from receiving too much damage! (53 -> 1).

which might be a hint about what's happening here.

**Comment by jeremygurr** [comment]
That is the damage protection. Depending on difficulty, it limits how much damage can be done in a single turn, preventing one-shot kills. If things are too easy, you can play a harder difficulty mode, or you can turn off damage protection entirely if you prefer.  

> disable_instakill_protection=true

**Comment by MattConrad** [comment]
I was playing on Challenge at the time. 53 -> 1 seemed like a drastic reduction. I guessed it was not intentional. Sounds like it is understood and intentional, no further concerns.

**Comment by jeremygurr** [comment]
Yeah it was because you had already received damage in that round, which wasn't reduced. For example, on standard mode you aren't allowed to receive more than 30% of your max hp in damage between times when you can actually respond to the situation. So if your max hp is 20, and you receive 5 damage you get the full 5. But then another attack causes 5 more damage before you can have a turn, and since 30% of 20 is 6, and you've already received 5, the next 5 gets reduced to 1, adding up to a total of 6 damage between turns. Any damage after that, before you get a chance to act, gets reduced to 0.

**Comment by MattConrad** [comment]
Ah, thank you for the clarification, it makes more sense now.
