### ISSUE TITLE
Naga does not have move penalty in v1.1

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#90]
See title, is it expected?

**Comment by jeremygurr** [comment]
The move penalty is a fixed time, and doesn't vary with the species speed. So the naga should take either 2.0 or it's own speed, whichever is the slower value. So a slowed chei naga slower than 2.0 wouldn't show any penalty at all. This is intended, since the naga is still not going to be able to kite, and doesn't really need to be slower.

**Comment by Sandman25DCSS** [comment]
I am Na of Chei indeed. I am not at max piety yet but I guess that using 2.0 (first move) instead of 2.8 (standard cost for Na of Chei at max piety) can result in weird behavior when for retreating I may want to wield/unwield weapon (0.3 turn) and walk a tile (2.0), then again wield/unwield weapon (0.3 turn) and  walk a tile (2.0) and so on.

**Comment by jeremygurr** [comment]
Yes, that is why it uses the max of it's normal speed and 2.0, so you never have to deal with that weirdness.

**Comment by Sandman25DCSS** [comment]
Oh, slower value. My bad. Thank you for explanations.
